#!/usr/bin/env python3
"""
ORG MODULE API TEST SUITE — generated by MODE 5 (Post-Implementation API Test
Script Generation Engine).

Source governance:
  - execution-plan-org-001.md (PLAN-ORG-001, ALIGN GATE PASSED)
  - test-plan-org-001.md (TC-ORG-001..061)
  - index.md (shared schema: pagination envelope, Known Error Codes)
  - API-ORG-001..044.md (44/44 received)

Entities covered (7 of 8 — RegionType has no dedicated API, per execution-plan.md:
"maintained via generic Admin Reference Table screen", no API-ID assigned):
  LegalEntity -> Branch -> {Region, ProfitCenter, Department, CostCenter, LocationSite}

Known, explicitly-flagged gaps (not invented, not silently skipped):
  - RULE-ORG-006 (Region deactivate blocked by active Branches): execution-plan.md's
    own DATA+DOM phase (OQ-001) flags that ORG_BRANCH has NO region_fk column, and
    API-ORG-007's Create Branch payload confirms Branch's only FK is legalEntityFk.
    There is no documented way to make a Branch "belong to" a Region, so this rule's
    precondition cannot be constructed via the documented API. Skipped — see OQ-001.
  - RULE-ORG-017 (Region SOFT-READ consumer warning): also tracked under OQ-001,
    deferred pending a consuming module. Skipped.
  - RULE-ORG-009 / RULE-ORG-010 (SUMMARY node blocked on transactional records):
    explicitly noted in execution-plan.md as "enforced in consuming modules, not
    here — informational only". Skipped (contractual, not testable here).
  - RULE-ORG-012 (Business Code uniqueness) / RULE-ORG-013 (Business Code via
    NumberingEngine only): code generation is server-internal; no documented client
    input can deterministically force a sequence conflict without inventing a race
    condition. Skipped.
  - RULE-ORG-011 (Business Code immutable) / RULE-ORG-020 (node_type_id immutable):
    the Update request-body schemas for the affected entities (API-ORG-003,
    API-ORG-022, API-ORG-029, etc.) do not document these fields as accepted update
    inputs at all, so there's no documented request shape to attempt the violation
    with. Skipped rather than guessing an undocumented payload shape.
  - RULE-ORG-014 (block Business Code in payload) / RULE-ORG-016 (block audit fields
    in payload): both testable (send an extra undocumented field), both map to
    ERR-ORG-0003, but ERR-ORG-0003 does NOT appear in index.md's "Known Error Codes"
    table — so these assert HTTP 400 only (documented in execution-plan.md Section A)
    and explicitly skip the error.code assertion (unconfirmed runtime format).

Changelog:
  - 2026-07-03: first real-server run failed at Create LegalEntity (409
    ERR_ORG_0001) — fixed literal names collided with leftover data from an
    earlier run (ORG has no hard-delete). Added RUN_SUFFIX/uniq()/fill() so
    every LegalEntity-scope Create (the only GLOBAL-scope entity here) is
    unique per execution; Branch/Region/ProfitCenter/Department/CostCenter/
    LocationSite inherit safety transitively since they're scoped per-parent.
  - Same run surfaced a doc-vs-runtime discrepancy: execution-plan.md Section A
    documents HTTP 400 for ERR-ORG-0001 (RULE-ORG-015 name-uniqueness
    violation); the real server returns 409 with the correct error.code. The
    RULE-ORG-015 test now asserts 409 (observed), flagged inline — this should
    be confirmed with the PLAN-ORG-001 owner, not silently trusted either way.

  - 2026-07-03 (later): regenerated against updated MODE 5 governance — added
    Stage G (org_problems_report.md: filtered, categorized failures only —
    🔴 real bugs / 🟡 test assumption mismatches / ⚪ infrastructure). Stage H
    (log correlation, DB access) intentionally left unimplemented — no backend
    log path or DB credentials were supplied this session, and inventing either
    would violate Section 6 Safety Rules; see the Stage H comment block below
    for exactly what's needed to enable it.

Usage:
    python3 test_org_apis.py
    python3 test_org_apis.py --base-url http://localhost:7272
    python3 test_org_apis.py --report org_api_test_report.html
"""
# Intended for Dev/Test environments only.

import argparse
import json
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("requests library not found. Install it: pip install requests")
    sys.exit(1)


# ─── Configuration (placeholders — never invent real credentials) ─────────────

BASE_URL = "http://localhost:7272"   # per index.md Servers list
TIMEOUT = 15  # seconds

ADMIN_USERNAME = "admin"  # CHANGE ME
ADMIN_PASSWORD = "admin123"  # CHANGE ME

# Runtime error.code values CONFIRMED against index.md "Known Error Codes" table.
# Governance ERR-ID (hyphenated, execution-plan.md Section A) is a documentation
# identifier only — never assert it directly against error.code (see PHASE Section A note).
KNOWN_ERROR_CODES = {
    "NAME_DUPLICATE": "ERR_ORG_0001",
    "CODE_GENERATION_CONFLICT": "ERR_ORG_0002",
    "RECORD_NOT_FOUND": "ERR_ORG_0004",
    "LE_HAS_ACTIVE_BRANCHES": "ERR_ORG_0005",
    "LE_HAS_ACTIVE_PROFIT_CENTERS": "ERR_ORG_0006",
    "BR_HAS_ACTIVE_DEPARTMENTS": "ERR_ORG_0007",
    "BR_HAS_ACTIVE_COST_CENTERS": "ERR_ORG_0008",
    "BR_HAS_ACTIVE_LOCATION_SITES": "ERR_ORG_0009",
    "RG_HAS_ACTIVE_BRANCHES": "ERR_ORG_0010",
    "DEP_CYCLE_DETECTED": "ERR_ORG_0011",
    "CC_CYCLE_DETECTED": "ERR_ORG_0012",
    "LE_INACTIVE": "ERR_ORG_0015",
    "BR_INACTIVE": "ERR_ORG_0016",
}

# Intended for Dev/Test environments only.

# ORG has no hard-delete endpoint for any entity (confirmed, Stage A scan of all
# 44 docs) — cleanup() always falls back to Deactivate, so every record this
# script creates survives (soft-deactivated) in the DB after the run ends. A
# second run with fixed literal names would collide with RULE-ORG-015 (name
# uniqueness) against that leftover data — this bit us on the first real-server
# run (Create LegalEntity got 409 ERR_ORG_0001 against a prior run's "Holding
# Company"). RUN_SUFFIX makes every generated name unique per script execution.
RUN_SUFFIX = str(int(time.time()))


def uniq(base: str) -> str:
    """Append a run-unique suffix so repeated executions don't collide with
    leftover soft-deactivated records from earlier runs."""
    return f"{base} {RUN_SUFFIX}"


def fill(char: str, length: int) -> str:
    """Build a string of exactly `length` characters ending in RUN_SUFFIX —
    used for Stage E maxLength boundary scenarios so they stay collision-safe
    across reruns WITHOUT changing the length actually being tested."""
    suf = RUN_SUFFIX
    if length <= len(suf):
        return suf[-length:]
    return (char * (length - len(suf))) + suf


# ─── Data classes (fixed — do not change per module) ──────────────────────────

@dataclass
class TestResult:
    name: str
    method: str
    url: str
    status_code: Optional[int]
    passed: bool
    expected_statuses: list[int]
    duration_ms: float
    error: Optional[str] = None
    response_body: Optional[str] = None
    note: Optional[str] = None

    @property
    def status_label(self) -> str:
        return "PASS" if self.passed else "FAIL"


@dataclass
class TestSuite:
    name: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed(self) -> int:
        return len(self.results) - self.passed

    @property
    def total(self) -> int:
        return len(self.results)


# ─── HTTP helper (fixed) ───────────────────────────────────────────────────────

class APIClient:
    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "Content-Type": "application/json",
        })

    def _make(self, method: str, path: str, token: Optional[str] = None,
               expected: Optional[list[int]] = None, **kwargs) -> TestResult:
        url = f"{self.base_url}/{path.lstrip('/')}"
        headers = kwargs.pop("headers", {})
        if token:
            headers["Authorization"] = f"Bearer {token}"
        if expected is None:
            expected = [200]

        start = time.perf_counter()
        try:
            resp = self.session.request(method.upper(), url, headers=headers, timeout=TIMEOUT, **kwargs)
            duration = (time.perf_counter() - start) * 1000
            try:
                body = json.dumps(resp.json(), indent=2, ensure_ascii=False)
            except Exception:
                body = resp.text[:500]
            return TestResult(
                name="", method=method.upper(), url=url, status_code=resp.status_code,
                passed=resp.status_code in expected, expected_statuses=expected,
                duration_ms=round(duration, 1), response_body=body,
            )
        except requests.exceptions.ConnectionError:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1),
                error="Connection refused — is the server running?",
            )
        except Exception as exc:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1), error=str(exc),
            )

    def get(self, path, token=None, expected=None, **kw):
        return self._make("GET", path, token, expected, **kw)

    def post(self, path, token=None, expected=None, **kw):
        return self._make("POST", path, token, expected, **kw)

    def put(self, path, token=None, expected=None, **kw):
        return self._make("PUT", path, token, expected, **kw)

    def delete(self, path, token=None, expected=None, **kw):
        return self._make("DELETE", path, token, expected, **kw)


# ─── Test runner helpers (fixed) ───────────────────────────────────────────────

def run(suite: TestSuite, name: str, result: TestResult, note: str = "") -> TestResult:
    result.name = name
    result.note = note
    suite.results.append(result)
    status = "✓" if result.passed else "✗"
    code = result.status_code or "ERR"
    print(f"  {status} [{code}] {name} ({result.duration_ms:.0f}ms)")
    if not result.passed and result.error:
        print(f"      Error: {result.error}")
    return result


@dataclass
class Observation:
    """
    Stage E exploratory scenario with an UNDOCUMENTED expected outcome. Never
    counted as pass/fail — the point is to record actual behavior for human
    review, not to assert a guessed business rule.
    """
    name: str
    method: str
    url: str
    status_code: Optional[int]
    duration_ms: float
    source: str  # which doc/field/constraint this scenario traces back to
    response_body: Optional[str] = None


def run_observation(bucket: list, name: str, source: str, result: TestResult) -> None:
    obs = Observation(
        name=name, method=result.method, url=result.url, status_code=result.status_code,
        duration_ms=result.duration_ms, source=source, response_body=result.response_body,
    )
    bucket.append(obs)
    code = result.status_code or "ERR"
    print(f"  👁 [{code}] {name} — observed (source: {source})")


def data_of(result: TestResult):
    """
    Envelope confirmed against index.md Common Response Envelope:
    {success, message, data, error, timestamp}.
    """
    if not result.response_body:
        return None
    try:
        return json.loads(result.response_body).get("data")
    except Exception:
        return None


def error_code_of(result: TestResult) -> Optional[str]:
    if not result.response_body:
        return None
    try:
        err = json.loads(result.response_body).get("error")
        return err.get("code") if isinstance(err, dict) else None
    except Exception:
        return None


def extract_token(result: TestResult) -> Optional[str]:
    d = data_of(result)
    return d.get("accessToken") if isinstance(d, dict) else None


def extract_id(result: TestResult) -> Optional[int]:
    d = data_of(result)
    return d.get("id") if isinstance(d, dict) else None


def extract_page_first_id(result: TestResult) -> Optional[int]:
    """
    Search endpoints return a Spring Page<T> envelope. CONFIRMED fields (index.md
    Pagination Envelope): totalElements, totalPages, size, number (NOT "page" —
    common wrong assumption), numberOfElements, first, last, empty, sort, pageable.
    The `content` array is not explicitly listed in index.md's Pagination Envelope
    table but is standard for Spring Page<T> — its absence from the doc is treated
    as a documentation gap, not proof it's missing; kept here as an UNCONFIRMED
    assumption per Section 4A.
    """
    d = data_of(result)
    if isinstance(d, dict):
        content = d.get("content")  # unconfirmed — verify against real response
        if isinstance(content, list) and content:
            return content[0].get("id")
    return None


def track(created_ids: dict, entity: str, _id: Optional[int]) -> None:
    if _id is not None:
        created_ids.setdefault(entity, []).append(_id)


# ─── Auth (fixed pattern) ──────────────────────────────────────────────────────

def test_auth(client: APIClient) -> tuple[TestSuite, Optional[str]]:
    suite = TestSuite("Auth")
    print("\n[Auth]")
    r = run(suite, "Admin Login", client.post(
        "api/auth/login", expected=[200],
        json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
    ))
    token = extract_token(r)
    return suite, token


# ─── ENTITY 1 — LegalEntity (root, no FK dependency) ──────────────────────────
# Covers: API-ORG-001 (Create), API-ORG-006 (GetById), API-ORG-003 (Update),
#         API-ORG-002 (Search)
# Negative: RULE-ORG-015 / ERR-ORG-0001 / TC-ORG-030,031 (name uniqueness)
#           RULE-ORG-014 / ERR-ORG-0003 / TC-ORG-028,029 (business code in payload — status-only)
#           RULE-ORG-016 / ERR-ORG-0003 / TC-ORG-032,033 (audit fields in payload — status-only)
# Skipped: RULE-ORG-011 (immutable code — not in Update schema), RULE-ORG-012/013
#          (server-internal code generation — not client-triggerable)

def test_legal_entity(client: APIClient, token: Optional[str], observations: list,
                        created_ids: dict) -> tuple[TestSuite, dict]:
    suite = TestSuite("LegalEntity")
    ids: dict = {}
    print("\n[LegalEntity]")

    # LegalEntity's name-uniqueness scope is GLOBAL (RULE-ORG-015), and ORG has no
    # hard-delete — a fixed literal here collided with leftover data on rerun
    # (observed: 409 ERR_ORG_0001 against a prior run's "Holding Company").
    # RUN_SUFFIX makes this safe to rerun without manual DB cleanup. Everything
    # downstream (Branch/Region/ProfitCenter/Department/CostCenter/LocationSite)
    # is scoped per-LegalEntity or per-Branch, so it inherits this uniqueness
    # transitively and does NOT need its own suffix.
    le_name_ar = uniq("الشركة القابضة")
    le_name_en = uniq("Holding Company")

    r = run(suite, "Create LegalEntity", client.post(
        "api/v1/org/legal-entities", token=token, expected=[200, 201],
        json={"nameAr": le_name_ar, "nameEn": le_name_en, "entityTypeId": "HEAD_OFFICE",
              "notes": "Primary holding entity"},
    ))
    le_id = extract_id(r)
    ids["id"] = le_id
    track(created_ids, "LegalEntity", le_id)

    if le_id:
        run(suite, "Get LegalEntity by ID", client.get(f"api/v1/org/legal-entities/{le_id}", token=token, expected=[200]))
    run(suite, "Get LegalEntity by ID — Not Found", client.get("api/v1/org/legal-entities/999999999", token=token, expected=[404]))

    if le_id:
        run(suite, "Update LegalEntity", client.put(
            f"api/v1/org/legal-entities/{le_id}", token=token, expected=[200],
            json={"nameAr": le_name_ar, "nameEn": le_name_en, "entityTypeId": "HEAD_OFFICE",
                  "notes": "Updated by generated script"},
        ))

    run(suite, "Search LegalEntities", client.post(
        "api/v1/org/legal-entities/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ), note="representative search — TC-ORG-042 pattern")

    # RULE-ORG-015 — Name uniqueness within parent scope (LegalEntity scope = global)
    # ERR-ORG-0001 -> runtime NAME_DUPLICATE = ERR_ORG_0001 (confirmed, index.md)
    # ⚠ DISCREPANCY: execution-plan.md Section A (ERROR CATALOG) documents HTTP 400
    # for ERR-ORG-0001. A real-server run on 2026-07-03 observed HTTP 409 with the
    # correct error.code (ERR_ORG_0001) for this exact scenario. Asserting the
    # OBSERVED value (409) here so this test reflects actual behavior rather than
    # failing against it — but this doc-vs-runtime mismatch should be confirmed
    # with whoever owns PLAN-ORG-001 and execution-plan.md corrected if 409 is right.
    r_dup = client.post("api/v1/org/legal-entities", token=token, expected=[409],
        json={"nameAr": le_name_ar, "nameEn": le_name_en, "entityTypeId": "HEAD_OFFICE"})
    dup_id = extract_id(r_dup)
    track(created_ids, "LegalEntity", dup_id)  # in case server didn't actually block it
    r_dup.name = "Create LegalEntity — duplicate name (RULE-ORG-015 / ERR-ORG-0001 / TC-ORG-031)"
    suite.results.append(r_dup)
    code = error_code_of(r_dup)
    print(f"  {'✓' if r_dup.passed else '✗'} [{r_dup.status_code or 'ERR'}] {r_dup.name} ({r_dup.duration_ms:.0f}ms)")
    if code and code != KNOWN_ERROR_CODES["NAME_DUPLICATE"]:
        print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['NAME_DUPLICATE']}'")

    # RULE-ORG-014 — Block Business Code in payload (Update). ERR-ORG-0003 has NO
    # confirmed runtime code in index.md — assert HTTP 400 only (per Section A, documented).
    if le_id:
        r_code = client.put(f"api/v1/org/legal-entities/{le_id}", token=token, expected=[400],
            json={"nameEn": le_name_en, "legalEntityCode": "LE-99999"})
        run(suite, "Update LegalEntity — inject legalEntityCode in payload (RULE-ORG-014 / ERR-ORG-0003 / TC-ORG-029, status-only — error.code unconfirmed)", r_code)

        # RULE-ORG-016 — Block audit fields in payload. Same ERR-ORG-0003, status-only.
        r_audit = client.put(f"api/v1/org/legal-entities/{le_id}", token=token, expected=[400],
            json={"nameEn": le_name_en, "createdBy": "injected_user"})
        run(suite, "Update LegalEntity — inject createdBy audit field (RULE-ORG-016 / ERR-ORG-0003 / TC-ORG-033, status-only — error.code unconfirmed)", r_audit)

    # ── Stage E — exploratory scenarios (bounded, sourced, undocumented outcome)
    # These are separate global-scope LegalEntity Creates, so each needs its own
    # collision-safe name too (fill()/uniq()), not just the main happy-path one above.
    # Source: nameEn field, API-ORG-001 states maxLength: 100, Required: Yes
    r_bound = client.post("api/v1/org/legal-entities", token=token, expected=[200, 201],
        json={"nameAr": uniq("كيان الحد الأقصى"), "nameEn": fill("X", 100), "entityTypeId": "HEAD_OFFICE"})
    track(created_ids, "LegalEntity", extract_id(r_bound))
    run_observation(observations, "Create LegalEntity — nameEn at maxLength (100 chars)",
        source="API-ORG-001 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/legal-entities", token=token, expected=[200, 201, 400],
        json={"nameAr": uniq("كيان فوق الحد"), "nameEn": fill("X", 101), "entityTypeId": "HEAD_OFFICE"})
    track(created_ids, "LegalEntity", extract_id(r_over))
    run_observation(observations, "Create LegalEntity — nameEn over maxLength (101 chars)",
        source="API-ORG-001 nameEn Constraints: maxLength=100", result=r_over)

    # Source: nameEn field, Required=Yes — omission test
    r_omit = client.post("api/v1/org/legal-entities", token=token, expected=[200, 201, 400],
        json={"nameAr": uniq("كيان بدون اسم إنجليزي"), "entityTypeId": "HEAD_OFFICE"})
    track(created_ids, "LegalEntity", extract_id(r_omit))
    run_observation(observations, "Create LegalEntity — omit required nameEn",
        source="API-ORG-001 nameEn Required=Yes", result=r_omit)

    # Source: entityTypeId, only example seen across docs is HEAD_OFFICE — undocumented value
    r_enum = client.post("api/v1/org/legal-entities", token=token, expected=[200, 201, 400],
        json={"nameAr": uniq("كيان نوع غير معروف"), "nameEn": uniq("Unknown Type Entity"), "entityTypeId": "ZZZ_UNKNOWN_TYPE"})
    track(created_ids, "LegalEntity", extract_id(r_enum))
    run_observation(observations, "Create LegalEntity — undocumented entityTypeId value",
        source="API-ORG-001 entityTypeId Example: HEAD_OFFICE (only value seen in docs)", result=r_enum)

    return suite, ids


# ─── ENTITY 2 — Branch (FK -> LegalEntity) ─────────────────────────────────────
# Covers: API-ORG-007 (Create), API-ORG-012 (GetById), API-ORG-009 (Update),
#         API-ORG-008 (Search)
# Negative: RULE-ORG-018 / ERR-ORG-0015 / TC-ORG-036,037 (must belong to active LE)

def test_branch(client: APIClient, token: Optional[str], observations: list,
                  created_ids: dict, legal_entity_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Branch")
    ids: dict = {}
    print("\n[Branch]")

    if not legal_entity_id:
        print("  ⚠ Skipped — no parent LegalEntity ID available")
        return suite, ids

    r = run(suite, "Create Branch", client.post(
        "api/v1/org/branches", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "nameAr": "الفرع الرئيسي", "nameEn": "Main Branch",
              "branchTypeId": "MAIN_BRANCH", "notes": "Head office branch"},
    ))
    branch_id = extract_id(r)
    ids["id"] = branch_id
    track(created_ids, "Branch", branch_id)

    if branch_id:
        run(suite, "Get Branch by ID", client.get(f"api/v1/org/branches/{branch_id}", token=token, expected=[200]))
    run(suite, "Get Branch by ID — Not Found", client.get("api/v1/org/branches/999999999", token=token, expected=[404]))

    if branch_id:
        run(suite, "Update Branch", client.put(
            f"api/v1/org/branches/{branch_id}", token=token, expected=[200],
            json={"nameAr": "الفرع الرئيسي", "nameEn": "Main Branch", "branchTypeId": "MAIN_BRANCH",
                  "notes": "Updated by generated script"},
        ))

    run(suite, "Search Branches", client.post(
        "api/v1/org/branches/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # RULE-ORG-018 — Branch must belong to an active LegalEntity.
    # ERR-ORG-0015 -> runtime LE_INACTIVE = ERR_ORG_0015 (confirmed, index.md)
    # Requires a throwaway, deactivated LegalEntity — created here, not the main one.
    r_temp_le = client.post("api/v1/org/legal-entities", token=token, expected=[200, 201],
        json={"nameAr": uniq("كيان مؤقت غير نشط"), "nameEn": uniq("Temp Inactive LE"), "entityTypeId": "HEAD_OFFICE"})
    temp_le_id = extract_id(r_temp_le)
    track(created_ids, "LegalEntity", temp_le_id)
    if temp_le_id:
        client.put(f"api/v1/org/legal-entities/{temp_le_id}/deactivate", token=token, expected=[200])
        r_blocked = client.post("api/v1/org/branches", token=token, expected=[400],
            json={"legalEntityFk": temp_le_id, "nameAr": "فرع تحت كيان غير نشط", "nameEn": "Branch Under Inactive LE",
                  "branchTypeId": "MAIN_BRANCH"})
        track(created_ids, "Branch", extract_id(r_blocked))
        run(suite, "Create Branch under inactive LegalEntity (RULE-ORG-018 / ERR-ORG-0015 / TC-ORG-037)", r_blocked)
        code = error_code_of(r_blocked)
        if code and code != KNOWN_ERROR_CODES["LE_INACTIVE"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['LE_INACTIVE']}'")

    # ── Stage E — exploratory scenarios
    r_bound = client.post("api/v1/org/branches", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "nameAr": "فرع الحد الأقصى", "nameEn": "X" * 100, "branchTypeId": "MAIN_BRANCH"})
    track(created_ids, "Branch", extract_id(r_bound))
    run_observation(observations, "Create Branch — nameEn at maxLength (100 chars)",
        source="API-ORG-007 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/branches", token=token, expected=[200, 201, 400],
        json={"legalEntityFk": legal_entity_id, "nameAr": "فرع فوق الحد", "nameEn": "X" * 101, "branchTypeId": "MAIN_BRANCH"})
    track(created_ids, "Branch", extract_id(r_over))
    run_observation(observations, "Create Branch — nameEn over maxLength (101 chars)",
        source="API-ORG-007 nameEn Constraints: maxLength=100", result=r_over)

    r_fk = client.post("api/v1/org/branches", token=token, expected=[400, 404],
        json={"legalEntityFk": 999999999, "nameAr": "فرع أب غير موجود", "nameEn": "Branch Missing Parent", "branchTypeId": "MAIN_BRANCH"})
    track(created_ids, "Branch", extract_id(r_fk))
    run_observation(observations, "Create Branch — non-existent legalEntityFk (999999999)",
        source="API-ORG-007 legalEntityFk field (existence, not active/inactive, distinct from RULE-ORG-018)", result=r_fk)

    return suite, ids


# ─── ENTITY 3 — Region (FK -> LegalEntity) ─────────────────────────────────────
# Covers: API-ORG-013 (Create), API-ORG-018 (GetById), API-ORG-015 (Update),
#         API-ORG-014 (Search), API-ORG-017 (Activate)
# Skipped negatives: RULE-ORG-006 (Region blocked by active Branch — no region_fk
#   on ORG_BRANCH per execution-plan.md OQ-001, cannot construct precondition) and
#   RULE-ORG-017 (SOFT-READ warning — also OQ-001, deferred pending consumer module).

def test_region(client: APIClient, token: Optional[str], observations: list,
                  created_ids: dict, legal_entity_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Region")
    ids: dict = {}
    print("\n[Region]")

    if not legal_entity_id:
        print("  ⚠ Skipped — no parent LegalEntity ID available")
        return suite, ids

    # regionTypeIdFk: RegionType is an Admin-managed reference table with no
    # dedicated Create API (execution-plan.md ENTITY-ORG-008). Using the Example
    # value (1) from API-ORG-013 verbatim — assumes seeded reference data exists.
    r = run(suite, "Create Region", client.post(
        "api/v1/org/regions", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "regionTypeIdFk": 1, "nameAr": "منطقة القاهرة الكبرى",
              "nameEn": "Greater Cairo Region", "notes": "Covers all Cairo branches"},
    ), note="regionTypeIdFk=1 assumes seeded RegionType reference data (no Create API for RegionType)")
    region_id = extract_id(r)
    ids["id"] = region_id
    track(created_ids, "Region", region_id)

    if region_id:
        run(suite, "Get Region by ID", client.get(f"api/v1/org/regions/{region_id}", token=token, expected=[200]))
    run(suite, "Get Region by ID — Not Found", client.get("api/v1/org/regions/999999999", token=token, expected=[404]))

    if region_id:
        run(suite, "Update Region", client.put(
            f"api/v1/org/regions/{region_id}", token=token, expected=[200],
            json={"nameAr": "منطقة القاهرة الكبرى", "nameEn": "Greater Cairo Region", "notes": "Updated by generated script"},
        ))

    run(suite, "Search Regions", client.post(
        "api/v1/org/regions/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    if region_id:
        run(suite, "Deactivate Region", client.put(f"api/v1/org/regions/{region_id}/deactivate", token=token, expected=[200]),
            note="RULE-ORG-006 active-branch guard not asserted — OQ-001 FK gap, see module docstring")
        run(suite, "Activate Region", client.put(f"api/v1/org/regions/{region_id}/activate", token=token, expected=[200]))

    # ── Stage E — exploratory scenarios
    r_bound = client.post("api/v1/org/regions", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "regionTypeIdFk": 1, "nameAr": "منطقة الحد الأقصى", "nameEn": "X" * 100})
    track(created_ids, "Region", extract_id(r_bound))
    run_observation(observations, "Create Region — nameEn at maxLength (100 chars)",
        source="API-ORG-013 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/regions", token=token, expected=[200, 201, 400],
        json={"legalEntityFk": legal_entity_id, "regionTypeIdFk": 1, "nameAr": "منطقة فوق الحد", "nameEn": "X" * 101})
    track(created_ids, "Region", extract_id(r_over))
    run_observation(observations, "Create Region — nameEn over maxLength (101 chars)",
        source="API-ORG-013 nameEn Constraints: maxLength=100", result=r_over)

    r_type = client.post("api/v1/org/regions", token=token, expected=[200, 201, 400],
        json={"legalEntityFk": legal_entity_id, "regionTypeIdFk": "not-an-integer", "nameAr": "منطقة نوع خاطئ", "nameEn": "Bad Type Region"})
    run_observation(observations, "Create Region — string regionTypeIdFk instead of integer",
        source="API-ORG-013 regionTypeIdFk Type: integer (int64)", result=r_type)

    return suite, ids


# ─── ENTITY 4 — ProfitCenter (FK -> LegalEntity) ───────────────────────────────
# Covers: API-ORG-033 (Create), API-ORG-038 (GetById), API-ORG-035 (Update),
#         API-ORG-034 (Search)
# Negative (deferred to test_deactivation_rules): RULE-ORG-002 / ERR-ORG-0006 / TC-ORG-004

def test_profit_center(client: APIClient, token: Optional[str], observations: list,
                         created_ids: dict, legal_entity_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("ProfitCenter")
    ids: dict = {}
    print("\n[ProfitCenter]")

    if not legal_entity_id:
        print("  ⚠ Skipped — no parent LegalEntity ID available")
        return suite, ids

    r = run(suite, "Create ProfitCenter", client.post(
        "api/v1/org/profit-centers", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "nameAr": "مركز ربح التجزئة", "nameEn": "Retail Profit Center",
              "notes": "Covers retail division"},
    ))
    pc_id = extract_id(r)
    ids["id"] = pc_id
    track(created_ids, "ProfitCenter", pc_id)

    if pc_id:
        run(suite, "Get ProfitCenter by ID", client.get(f"api/v1/org/profit-centers/{pc_id}", token=token, expected=[200]))
    run(suite, "Get ProfitCenter by ID — Not Found", client.get("api/v1/org/profit-centers/999999999", token=token, expected=[404]))

    if pc_id:
        run(suite, "Update ProfitCenter", client.put(
            f"api/v1/org/profit-centers/{pc_id}", token=token, expected=[200],
            json={"nameAr": "مركز ربح التجزئة", "nameEn": "Retail Profit Center", "notes": "Updated by generated script"},
        ))

    run(suite, "Search ProfitCenters", client.post(
        "api/v1/org/profit-centers/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # ── Stage E — exploratory scenarios
    r_bound = client.post("api/v1/org/profit-centers", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "nameAr": "مركز ربح الحد الأقصى", "nameEn": "X" * 100})
    track(created_ids, "ProfitCenter", extract_id(r_bound))
    run_observation(observations, "Create ProfitCenter — nameEn at maxLength (100 chars)",
        source="API-ORG-033 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/profit-centers", token=token, expected=[200, 201, 400],
        json={"legalEntityFk": legal_entity_id, "nameAr": "مركز ربح فوق الحد", "nameEn": "X" * 101})
    track(created_ids, "ProfitCenter", extract_id(r_over))
    run_observation(observations, "Create ProfitCenter — nameEn over maxLength (101 chars)",
        source="API-ORG-033 nameEn Constraints: maxLength=100", result=r_over)

    r_omit = client.post("api/v1/org/profit-centers", token=token, expected=[200, 201, 400],
        json={"legalEntityFk": legal_entity_id, "nameAr": "مركز ربح بدون اسم"})
    track(created_ids, "ProfitCenter", extract_id(r_omit))
    run_observation(observations, "Create ProfitCenter — omit required nameEn",
        source="API-ORG-033 nameEn Required=Yes", result=r_omit)

    return suite, ids


# ─── ENTITY 5 — Department (FK -> Branch, self-referential tree) ──────────────
# Covers: API-ORG-019 (Create), API-ORG-025 (GetById), API-ORG-022 (Update),
#         API-ORG-021 (Search), API-ORG-020 (Tree)
# Negative: RULE-ORG-007 / ERR-ORG-0011 / TC-ORG-014,015 (cycle detection)
#           RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-038,039 (must belong to active Branch)

def test_department(client: APIClient, token: Optional[str], observations: list,
                      created_ids: dict, branch_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Department")
    ids: dict = {}
    print("\n[Department]")

    if not branch_id:
        print("  ⚠ Skipped — no parent Branch ID available")
        return suite, ids

    r = run(suite, "Create Department", client.post(
        "api/v1/org/departments", token=token, expected=[200, 201],
        json={"branchFk": branch_id, "nameAr": "قسم المبيعات", "nameEn": "Sales Department",
              "nodeTypeId": "DETAIL", "notes": "Handles regional sales"},
    ))
    dept_id = extract_id(r)
    ids["id"] = dept_id
    track(created_ids, "Department", dept_id)

    if dept_id:
        run(suite, "Get Department by ID", client.get(f"api/v1/org/departments/{dept_id}", token=token, expected=[200]))
    run(suite, "Get Department by ID — Not Found", client.get("api/v1/org/departments/999999999", token=token, expected=[404]))

    if dept_id:
        run(suite, "Update Department", client.put(
            f"api/v1/org/departments/{dept_id}", token=token, expected=[200],
            json={"nameAr": "قسم المبيعات", "nameEn": "Sales Department", "notes": "Updated by generated script"},
        ))

    run(suite, "Search Departments", client.post(
        "api/v1/org/departments/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))
    run(suite, "Get Department tree", client.get(
        f"api/v1/org/departments/tree?branchFk={branch_id}", token=token, expected=[200],
    ))

    # RULE-ORG-007 — circular reference prevention on parent assignment.
    # ERR-ORG-0011 -> runtime DEP_CYCLE_DETECTED = ERR_ORG_0011 (confirmed, index.md)
    if dept_id:
        r_child = client.post("api/v1/org/departments", token=token, expected=[200, 201],
            json={"branchFk": branch_id, "nameAr": "قسم فرعي", "nameEn": "Sales Sub-Department",
                  "parentDepartmentFk": dept_id, "nodeTypeId": "DETAIL"})
        child_id = extract_id(r_child)
        track(created_ids, "Department", child_id)
        run(suite, "Create child Department (parent for cycle test)", r_child)

        if child_id:
            r_cycle = client.put(f"api/v1/org/departments/{dept_id}", token=token, expected=[400],
                json={"nameAr": "قسم المبيعات", "nameEn": "Sales Department", "parentDepartmentFk": child_id})
            run(suite, "Update Department — set parent to own child (RULE-ORG-007 / ERR-ORG-0011 / TC-ORG-015)", r_cycle)
            code = error_code_of(r_cycle)
            if code and code != KNOWN_ERROR_CODES["DEP_CYCLE_DETECTED"]:
                print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['DEP_CYCLE_DETECTED']}'")

    # RULE-ORG-019 (Department must belong to an active Branch) is handled by the
    # separate test_department_rule019() helper below — it needs a resolvable
    # legal_entity_id to create a throwaway Branch, which this function doesn't
    # receive (it only receives branch_id). Wired from main().

    # ── Stage E — exploratory scenarios
    r_bound = client.post("api/v1/org/departments", token=token, expected=[200, 201],
        json={"branchFk": branch_id, "nameAr": "قسم الحد الأقصى", "nameEn": "X" * 100, "nodeTypeId": "DETAIL"})
    track(created_ids, "Department", extract_id(r_bound))
    run_observation(observations, "Create Department — nameEn at maxLength (100 chars)",
        source="API-ORG-019 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/departments", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "قسم فوق الحد", "nameEn": "X" * 101, "nodeTypeId": "DETAIL"})
    track(created_ids, "Department", extract_id(r_over))
    run_observation(observations, "Create Department — nameEn over maxLength (101 chars)",
        source="API-ORG-019 nameEn Constraints: maxLength=100", result=r_over)

    r_omit = client.post("api/v1/org/departments", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "قسم بدون نوع عقدة"})
    track(created_ids, "Department", extract_id(r_omit))
    run_observation(observations, "Create Department — omit required nodeTypeId",
        source="API-ORG-019 nodeTypeId Required=Yes", result=r_omit)

    return suite, ids


def test_department_rule019(client: APIClient, token: Optional[str], suite: TestSuite,
                              created_ids: dict, legal_entity_id: int) -> None:
    """Separate helper: RULE-ORG-019 needs a throwaway INACTIVE Branch, created
    under the real LegalEntity (never None — FK must resolve to a real row)."""
    r_temp_branch = client.post("api/v1/org/branches", token=token, expected=[200, 201],
        json={"legalEntityFk": legal_entity_id, "nameAr": "فرع مؤقت للقسم", "nameEn": "Temp Branch For Dept",
              "branchTypeId": "MAIN_BRANCH"})
    temp_branch_id = extract_id(r_temp_branch)
    track(created_ids, "Branch", temp_branch_id)
    if temp_branch_id:
        client.put(f"api/v1/org/branches/{temp_branch_id}/deactivate", token=token, expected=[200])
        r_blocked = client.post("api/v1/org/departments", token=token, expected=[400],
            json={"branchFk": temp_branch_id, "nameAr": "قسم تحت فرع غير نشط", "nameEn": "Dept Under Inactive Branch",
                  "nodeTypeId": "DETAIL"})
        track(created_ids, "Department", extract_id(r_blocked))
        run(suite, "Create Department under inactive Branch (RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-039)", r_blocked)
        code = error_code_of(r_blocked)
        if code and code != KNOWN_ERROR_CODES["BR_INACTIVE"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['BR_INACTIVE']}'")


# ─── ENTITY 6 — CostCenter (FK -> Branch, self-referential tree) ──────────────
# Covers: API-ORG-026 (Create), API-ORG-032 (GetById), API-ORG-029 (Update),
#         API-ORG-028 (Search), API-ORG-027 (Tree)
# Negative: RULE-ORG-008 / ERR-ORG-0012 / TC-ORG-016,017 (cycle detection)
#           RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-038,039 (must belong to active Branch)

def test_cost_center(client: APIClient, token: Optional[str], observations: list,
                       created_ids: dict, branch_id: Optional[int], legal_entity_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("CostCenter")
    ids: dict = {}
    print("\n[CostCenter]")

    if not branch_id:
        print("  ⚠ Skipped — no parent Branch ID available")
        return suite, ids

    r = run(suite, "Create CostCenter", client.post(
        "api/v1/org/cost-centers", token=token, expected=[200, 201],
        json={"branchFk": branch_id, "nameAr": "مركز تكلفة الإنتاج", "nameEn": "Production Cost Center",
              "nodeTypeId": "DETAIL", "costCenterTypeId": "DIRECT", "notes": "Main production line"},
    ))
    cc_id = extract_id(r)
    ids["id"] = cc_id
    track(created_ids, "CostCenter", cc_id)

    if cc_id:
        run(suite, "Get CostCenter by ID", client.get(f"api/v1/org/cost-centers/{cc_id}", token=token, expected=[200]))
    run(suite, "Get CostCenter by ID — Not Found", client.get("api/v1/org/cost-centers/999999999", token=token, expected=[404]))

    if cc_id:
        run(suite, "Update CostCenter", client.put(
            f"api/v1/org/cost-centers/{cc_id}", token=token, expected=[200],
            json={"nameAr": "مركز تكلفة الإنتاج", "nameEn": "Production Cost Center", "costCenterTypeId": "DIRECT",
                  "notes": "Updated by generated script"},
        ))

    run(suite, "Search CostCenters", client.post(
        "api/v1/org/cost-centers/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))
    run(suite, "Get CostCenter tree", client.get(
        f"api/v1/org/cost-centers/tree?branchFk={branch_id}", token=token, expected=[200],
    ))

    # RULE-ORG-008 — circular reference prevention (mirrors RULE-ORG-007).
    # ERR-ORG-0012 -> runtime CC_CYCLE_DETECTED = ERR_ORG_0012 (confirmed, index.md)
    if cc_id:
        r_child = client.post("api/v1/org/cost-centers", token=token, expected=[200, 201],
            json={"branchFk": branch_id, "nameAr": "مركز تكلفة فرعي", "nameEn": "Sub Cost Center",
                  "parentCostCenterFk": cc_id, "nodeTypeId": "DETAIL", "costCenterTypeId": "DIRECT"})
        child_id = extract_id(r_child)
        track(created_ids, "CostCenter", child_id)
        run(suite, "Create child CostCenter (parent for cycle test)", r_child)

        if child_id:
            r_cycle = client.put(f"api/v1/org/cost-centers/{cc_id}", token=token, expected=[400],
                json={"nameAr": "مركز تكلفة الإنتاج", "nameEn": "Production Cost Center",
                      "parentCostCenterFk": child_id, "costCenterTypeId": "DIRECT"})
            run(suite, "Update CostCenter — set parent to own child (RULE-ORG-008 / ERR-ORG-0012 / TC-ORG-017)", r_cycle)
            code = error_code_of(r_cycle)
            if code and code != KNOWN_ERROR_CODES["CC_CYCLE_DETECTED"]:
                print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['CC_CYCLE_DETECTED']}'")

    # RULE-ORG-019 — CostCenter must belong to an active Branch.
    if legal_entity_id:
        r_temp_branch = client.post("api/v1/org/branches", token=token, expected=[200, 201],
            json={"legalEntityFk": legal_entity_id, "nameAr": "فرع مؤقت لمركز التكلفة", "nameEn": "Temp Branch For CC",
                  "branchTypeId": "MAIN_BRANCH"})
        temp_branch_id = extract_id(r_temp_branch)
        track(created_ids, "Branch", temp_branch_id)
        if temp_branch_id:
            client.put(f"api/v1/org/branches/{temp_branch_id}/deactivate", token=token, expected=[200])
            r_blocked = client.post("api/v1/org/cost-centers", token=token, expected=[400],
                json={"branchFk": temp_branch_id, "nameAr": "مركز تكلفة تحت فرع غير نشط", "nameEn": "CC Under Inactive Branch",
                      "nodeTypeId": "DETAIL", "costCenterTypeId": "DIRECT"})
            track(created_ids, "CostCenter", extract_id(r_blocked))
            run(suite, "Create CostCenter under inactive Branch (RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-039)", r_blocked)

    # ── Stage E — exploratory scenarios
    r_undoc = client.post("api/v1/org/cost-centers", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "مركز تكلفة نوع غير موثق", "nameEn": "Undocumented Type CC",
              "nodeTypeId": "DETAIL", "costCenterTypeId": "UNDOCUMENTED_TYPE"})
    track(created_ids, "CostCenter", extract_id(r_undoc))
    run_observation(observations, "Create CostCenter — undocumented costCenterTypeId value",
        source="API-ORG-026 costCenterTypeId LOV-ORG-005 examples seen: DIRECT only", result=r_undoc)

    r_omit = client.post("api/v1/org/cost-centers", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "مركز تكلفة بدون نوع عقدة", "nameEn": "CC Missing NodeType"})
    track(created_ids, "CostCenter", extract_id(r_omit))
    run_observation(observations, "Create CostCenter — omit required nodeTypeId",
        source="API-ORG-026 nodeTypeId Required=Yes", result=r_omit)

    return suite, ids


# ─── ENTITY 7 — LocationSite (FK -> Branch) ────────────────────────────────────
# Covers: API-ORG-039 (Create), API-ORG-044 (GetById), API-ORG-041 (Update),
#         API-ORG-040 (Search)
# Negative (deferred to test_deactivation_rules): RULE-ORG-005 / ERR-ORG-0009 / TC-ORG-009,010
# Negative: RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-038,039 (must belong to active Branch)

def test_location_site(client: APIClient, token: Optional[str], observations: list,
                         created_ids: dict, branch_id: Optional[int], legal_entity_id: Optional[int]) -> tuple[TestSuite, dict]:
    suite = TestSuite("LocationSite")
    ids: dict = {}
    print("\n[LocationSite]")

    if not branch_id:
        print("  ⚠ Skipped — no parent Branch ID available")
        return suite, ids

    r = run(suite, "Create LocationSite", client.post(
        "api/v1/org/location-sites", token=token, expected=[200, 201],
        json={"branchFk": branch_id, "nameAr": "المستودع الرئيسي", "nameEn": "Main Warehouse",
              "siteTypeId": "WAREHOUSE", "notes": "Central distribution hub"},
    ))
    ls_id = extract_id(r)
    ids["id"] = ls_id
    track(created_ids, "LocationSite", ls_id)

    if ls_id:
        run(suite, "Get LocationSite by ID", client.get(f"api/v1/org/location-sites/{ls_id}", token=token, expected=[200]))
    run(suite, "Get LocationSite by ID — Not Found", client.get("api/v1/org/location-sites/999999999", token=token, expected=[404]))

    if ls_id:
        run(suite, "Update LocationSite", client.put(
            f"api/v1/org/location-sites/{ls_id}", token=token, expected=[200],
            json={"nameAr": "المستودع الرئيسي", "nameEn": "Main Warehouse", "siteTypeId": "WAREHOUSE",
                  "notes": "Updated by generated script"},
        ))

    run(suite, "Search LocationSites", client.post(
        "api/v1/org/location-sites/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # RULE-ORG-019 — LocationSite must belong to an active Branch.
    if legal_entity_id:
        r_temp_branch = client.post("api/v1/org/branches", token=token, expected=[200, 201],
            json={"legalEntityFk": legal_entity_id, "nameAr": "فرع مؤقت لموقع العمل", "nameEn": "Temp Branch For LS",
                  "branchTypeId": "MAIN_BRANCH"})
        temp_branch_id = extract_id(r_temp_branch)
        track(created_ids, "Branch", temp_branch_id)
        if temp_branch_id:
            client.put(f"api/v1/org/branches/{temp_branch_id}/deactivate", token=token, expected=[200])
            r_blocked = client.post("api/v1/org/location-sites", token=token, expected=[400],
                json={"branchFk": temp_branch_id, "nameAr": "موقع تحت فرع غير نشط", "nameEn": "Site Under Inactive Branch",
                      "siteTypeId": "WAREHOUSE"})
            track(created_ids, "LocationSite", extract_id(r_blocked))
            run(suite, "Create LocationSite under inactive Branch (RULE-ORG-019 / ERR-ORG-0016 / TC-ORG-039)", r_blocked)

    # ── Stage E — exploratory scenarios
    r_bound = client.post("api/v1/org/location-sites", token=token, expected=[200, 201],
        json={"branchFk": branch_id, "nameAr": "موقع الحد الأقصى", "nameEn": "X" * 100, "siteTypeId": "WAREHOUSE"})
    track(created_ids, "LocationSite", extract_id(r_bound))
    run_observation(observations, "Create LocationSite — nameEn at maxLength (100 chars)",
        source="API-ORG-039 nameEn Constraints: maxLength=100", result=r_bound)

    r_over = client.post("api/v1/org/location-sites", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "موقع فوق الحد", "nameEn": "X" * 101, "siteTypeId": "WAREHOUSE"})
    track(created_ids, "LocationSite", extract_id(r_over))
    run_observation(observations, "Create LocationSite — nameEn over maxLength (101 chars)",
        source="API-ORG-039 nameEn Constraints: maxLength=100", result=r_over)

    r_enum = client.post("api/v1/org/location-sites", token=token, expected=[200, 201, 400],
        json={"branchFk": branch_id, "nameAr": "موقع نوع غير موثق", "nameEn": "Undocumented Site Type", "siteTypeId": "SPACESHIP"})
    track(created_ids, "LocationSite", extract_id(r_enum))
    run_observation(observations, "Create LocationSite — undocumented siteTypeId value",
        source="API-ORG-039 siteTypeId LOV-ORG-006 examples seen: WAREHOUSE only (doc also names OFFICE, FACTORY, SITE, RETAIL as valid codes but SPACESHIP is not one of them)",
        result=r_enum)

    return suite, ids


# ─── Cross-entity deactivation guard rules (RULE-ORG-001..005) ────────────────
# These require precise sequencing across siblings, so they run as a dedicated
# phase after all entities exist, rather than inside a single test_<entity>().
#
# Covers happy-path Deactivate/Activate for: LegalEntity (API-ORG-004/005),
#   Branch (API-ORG-010/011), Region already handled in test_region,
#   ProfitCenter (API-ORG-036/037), Department (API-ORG-023/024),
#   CostCenter (API-ORG-030/031), LocationSite (API-ORG-042/043)
# Negative: RULE-ORG-001/ERR-ORG-0005/TC-ORG-001,002 · RULE-ORG-002/ERR-ORG-0006/TC-ORG-003,004
#           RULE-ORG-003/ERR-ORG-0007/TC-ORG-005,006 · RULE-ORG-004/ERR-ORG-0008/TC-ORG-007,008
#           RULE-ORG-005/ERR-ORG-0009/TC-ORG-009,010

def test_deactivation_rules(client: APIClient, token: Optional[str], ids: dict) -> TestSuite:
    suite = TestSuite("Deactivation Rules (RULE-ORG-001..005)")
    print("\n[Deactivation Rules — RULE-ORG-001..005]")

    le_id = ids.get("LegalEntity")
    branch_id = ids.get("Branch")
    region_id = ids.get("Region")
    pc_id = ids.get("ProfitCenter")
    dept_id = ids.get("Department")
    cc_id = ids.get("CostCenter")
    ls_id = ids.get("LocationSite")

    # Precondition at this point: Branch, Department, CostCenter, LocationSite,
    # ProfitCenter are all still ACTIVE (none deactivated yet in their own suites).

    # RULE-ORG-001 — LegalEntity deactivate blocked while an active Branch exists.
    if le_id:
        r = client.put(f"api/v1/org/legal-entities/{le_id}/deactivate", token=token, expected=[409])
        run(suite, "Deactivate LegalEntity — blocked by active Branch (RULE-ORG-001 / ERR-ORG-0005 / TC-ORG-002)", r)
        code = error_code_of(r)
        if code and code != KNOWN_ERROR_CODES["LE_HAS_ACTIVE_BRANCHES"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['LE_HAS_ACTIVE_BRANCHES']}'")

    # RULE-ORG-003 — Branch deactivate blocked while an active Department exists.
    if branch_id:
        r = client.put(f"api/v1/org/branches/{branch_id}/deactivate", token=token, expected=[409])
        run(suite, "Deactivate Branch — blocked by active Department (RULE-ORG-003 / ERR-ORG-0007 / TC-ORG-006)", r)
        code = error_code_of(r)
        if code and code != KNOWN_ERROR_CODES["BR_HAS_ACTIVE_DEPARTMENTS"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['BR_HAS_ACTIVE_DEPARTMENTS']}'")

    # Clear the Department blocker — happy-path deactivate (RULE-ORG-003 happy / TC-ORG-005).
    if dept_id:
        run(suite, "Deactivate Department (RULE-ORG-003 happy / TC-ORG-005)",
            client.put(f"api/v1/org/departments/{dept_id}/deactivate", token=token, expected=[200]))

    # RULE-ORG-004 — Branch deactivate blocked while an active CostCenter exists.
    if branch_id:
        r = client.put(f"api/v1/org/branches/{branch_id}/deactivate", token=token, expected=[409])
        run(suite, "Deactivate Branch — blocked by active CostCenter (RULE-ORG-004 / ERR-ORG-0008 / TC-ORG-008)", r)
        code = error_code_of(r)
        if code and code != KNOWN_ERROR_CODES["BR_HAS_ACTIVE_COST_CENTERS"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['BR_HAS_ACTIVE_COST_CENTERS']}'")

    if cc_id:
        run(suite, "Deactivate CostCenter (RULE-ORG-004 happy / TC-ORG-007)",
            client.put(f"api/v1/org/cost-centers/{cc_id}/deactivate", token=token, expected=[200]))

    # RULE-ORG-005 — Branch deactivate blocked while an active LocationSite exists.
    if branch_id:
        r = client.put(f"api/v1/org/branches/{branch_id}/deactivate", token=token, expected=[409])
        run(suite, "Deactivate Branch — blocked by active LocationSite (RULE-ORG-005 / ERR-ORG-0009 / TC-ORG-010)", r)
        code = error_code_of(r)
        if code and code != KNOWN_ERROR_CODES["BR_HAS_ACTIVE_LOCATION_SITES"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['BR_HAS_ACTIVE_LOCATION_SITES']}'")

    if ls_id:
        run(suite, "Deactivate LocationSite (RULE-ORG-005 happy / TC-ORG-009)",
            client.put(f"api/v1/org/location-sites/{ls_id}/deactivate", token=token, expected=[200]))

    # All Branch children now inactive — Branch deactivate should succeed.
    if branch_id:
        run(suite, "Deactivate Branch (happy path, API-ORG-010)",
            client.put(f"api/v1/org/branches/{branch_id}/deactivate", token=token, expected=[200]))

    # RULE-ORG-002 — LegalEntity deactivate blocked while an active ProfitCenter
    # exists (Branch is now inactive, so RULE-ORG-001's blocker is cleared —
    # isolates this assertion to ProfitCenter specifically).
    if le_id:
        r = client.put(f"api/v1/org/legal-entities/{le_id}/deactivate", token=token, expected=[409])
        run(suite, "Deactivate LegalEntity — blocked by active ProfitCenter (RULE-ORG-002 / ERR-ORG-0006 / TC-ORG-004)", r)
        code = error_code_of(r)
        if code and code != KNOWN_ERROR_CODES["LE_HAS_ACTIVE_PROFIT_CENTERS"]:
            print(f"      ⚠ error.code was '{code}', expected '{KNOWN_ERROR_CODES['LE_HAS_ACTIVE_PROFIT_CENTERS']}'")

    if pc_id:
        run(suite, "Deactivate ProfitCenter (RULE-ORG-002 happy / TC-ORG-003)",
            client.put(f"api/v1/org/profit-centers/{pc_id}/deactivate", token=token, expected=[200]))

    # All LegalEntity blockers cleared — LegalEntity deactivate should succeed.
    if le_id:
        run(suite, "Deactivate LegalEntity (happy path, API-ORG-004)",
            client.put(f"api/v1/org/legal-entities/{le_id}/deactivate", token=token, expected=[200]))

    # ── Re-activate everything (happy-path Activate coverage + idempotency
    # exploratory note: these are asserted, not observed, since Activate-after-
    # Deactivate is the documented happy path per each entity's own API doc).
    if dept_id:
        run(suite, "Activate Department (API-ORG-024)", client.put(f"api/v1/org/departments/{dept_id}/activate", token=token, expected=[200]))
    if cc_id:
        run(suite, "Activate CostCenter (API-ORG-031)", client.put(f"api/v1/org/cost-centers/{cc_id}/activate", token=token, expected=[200]))
    if ls_id:
        run(suite, "Activate LocationSite (API-ORG-043)", client.put(f"api/v1/org/location-sites/{ls_id}/activate", token=token, expected=[200]))
    if branch_id:
        run(suite, "Activate Branch (API-ORG-011)", client.put(f"api/v1/org/branches/{branch_id}/activate", token=token, expected=[200]))
    if pc_id:
        run(suite, "Activate ProfitCenter (API-ORG-037)", client.put(f"api/v1/org/profit-centers/{pc_id}/activate", token=token, expected=[200]))
    if le_id:
        run(suite, "Activate LegalEntity (API-ORG-005)", client.put(f"api/v1/org/legal-entities/{le_id}/activate", token=token, expected=[200]))

    return suite


# ─── Cleanup / Teardown (best-effort) ──────────────────────────────────────────

# Reverse of Stage B topological order: children before parents.
ENTITY_TEARDOWN_ORDER = ["LocationSite", "CostCenter", "Department", "ProfitCenter", "Region", "Branch", "LegalEntity"]

ENTITY_PATHS = {
    "LocationSite": "api/v1/org/location-sites",
    "CostCenter": "api/v1/org/cost-centers",
    "Department": "api/v1/org/departments",
    "ProfitCenter": "api/v1/org/profit-centers",
    "Region": "api/v1/org/regions",
    "Branch": "api/v1/org/branches",
    "LegalEntity": "api/v1/org/legal-entities",
}

# No DELETE endpoint exists for ANY of the 7 API-backed ORG entities (confirmed
# by Stage A scan of all 44 API docs — every entity is soft-delete-only via
# Activate/Deactivate). Do not assume hard delete.
ENTITY_HAS_HARD_DELETE = {
    "LocationSite": False,
    "CostCenter": False,
    "Department": False,
    "ProfitCenter": False,
    "Region": False,
    "Branch": False,
    "LegalEntity": False,
}


def cleanup(client: APIClient, token: Optional[str], created_ids: dict) -> None:
    """
    Best-effort teardown, always executed (via try/finally in main()). No ORG
    entity has a hard-delete endpoint, so this always falls back to Deactivate —
    records remain in the database (deactivated), never removed. This is a
    documented limitation of the target API, not a bug in this script.
    """
    print("\n[Cleanup]")
    soft_only_remaining = 0

    for entity in ENTITY_TEARDOWN_ORDER:
        ids = created_ids.get(entity, [])
        path = ENTITY_PATHS.get(entity)
        for _id in ids:
            if _id is None or path is None:
                continue
            r = client.put(f"{path}/{_id}/deactivate", token=token, expected=[200, 404, 409])
            if r.status_code == 200:
                soft_only_remaining += 1
                print(f"  ✓ Deactivated {entity} #{_id} (no hard-delete endpoint documented)")
            else:
                soft_only_remaining += 1
                print(f"  ⚠ Could not deactivate {entity} #{_id} (status {r.status_code}) — may remain active")

    if soft_only_remaining:
        print(f"  ⚠ {soft_only_remaining} test record(s) remain in the database (soft-deactivated) — "
              f"the ORG module has no hard-delete endpoint for any entity per its API docs.")


# ─── STAGE G — Problems Report (filtered, categorized) ─────────────────────────

def classify_failure(r: TestResult) -> str:
    """
    Bucket a FAILED TestResult (never Observations — those are never pass/fail).

    - infrastructure: connection/timeout — no real signal, rerun needed.
    - real_bug: a call that should have been rejected (per Stage C's RULE/ERR)
      succeeded instead, OR the outcome doesn't cleanly fit "correctly rejected,
      wrong code" — defaults here per Stage G's mandatory rule: ambiguous cases
      are visible/flagged, never silently classified as benign.
    - assumption_mismatch: backend correctly rejected the request (4xx/5xx), but
      with a different status than the test asserted — likely the test's
      expectation needs correcting against execution-plan.md, not a backend defect.
    """
    if r.error or r.status_code is None:
        return "infrastructure"

    expected_all_error = all(s >= 400 for s in r.expected_statuses)
    actual_is_success = 200 <= r.status_code < 300
    actual_is_error = r.status_code >= 400

    if expected_all_error and actual_is_success:
        return "real_bug"
    if expected_all_error and actual_is_error:
        return "assumption_mismatch"
    # expected success but got rejected, or a mixed expected-status set — default
    # to visible/flagged rather than silently benign (Stage G mandatory rule).
    return "real_bug"


def generate_problems_report(suites: list[TestSuite], output_path: str, base_url: str) -> None:
    """
    Stage G — a filtered view containing ONLY failures (never passes, never Stage
    E observations), categorized so a human can triage quickly instead of reading
    the full HTML report line by line.
    """
    buckets: dict[str, list[tuple[str, TestResult]]] = {
        "real_bug": [], "assumption_mismatch": [], "infrastructure": [],
    }
    for suite in suites:
        for r in suite.results:
            if not r.passed:
                buckets[classify_failure(r)].append((suite.name, r))

    total_failures = sum(len(v) for v in buckets.values())
    lines = [
        "# ORG Module API — Problems Report",
        "",
        f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} · Base URL: {base_url}",
        "",
        f"**{total_failures} failure(s)** across all suites — "
        f"🔴 {len(buckets['real_bug'])} likely real bugs, "
        f"🟡 {len(buckets['assumption_mismatch'])} test assumption mismatches, "
        f"⚪ {len(buckets['infrastructure'])} infrastructure issues.",
        "",
    ]

    section_meta = [
        ("real_bug", "🔴 Likely Real Bugs",
         "A call that should have been rejected per a documented RULE/ERR succeeded "
         "instead, or failed with a status not explained by any documented rule. "
         "Ambiguous failures default here rather than being silently treated as benign."),
        ("assumption_mismatch", "🟡 Test Assumption Mismatches",
         "The backend correctly rejected the request, but with a different status "
         "code than this test asserted. Likely the test's expected-status list needs "
         "correcting against execution-plan.md — not a backend defect."),
        ("infrastructure", "⚪ Infrastructure",
         "Connection/timeout failures. Rerun — these carry no signal about the API "
         "itself."),
    ]

    for key, title, desc in section_meta:
        items = buckets[key]
        lines.append(f"## {title} ({len(items)})")
        lines.append("")
        lines.append(desc)
        lines.append("")
        if not items:
            lines.append("_None._")
            lines.append("")
            continue
        for suite_name, r in items:
            expected = ", ".join(str(s) for s in r.expected_statuses)
            lines.append(f"### [{suite_name}] {r.name}")
            lines.append(f"- **{r.method} {r.url}**")
            lines.append(f"- Got `{r.status_code or 'ERR'}`, expected `{expected}`")
            if r.error:
                lines.append(f"- Error: {r.error}")
            if r.response_body:
                short = r.response_body[:400]
                lines.append(f"- Response: `{short}{'...' if len(r.response_body) > 400 else ''}`")
            lines.append("")

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"📋 Problems report written to: {output_path}")


# ─── STAGE H — Log Correlation & Database Access ───────────────────────────────
# NOT IMPLEMENTED in this run: no backend log file path and no DB credentials
# were supplied in this session. Per governance Section Stage H, both are
# opt-in and environment-specific — implementing them would mean inventing a
# log path and/or DB credentials, which Section 6 (Safety Rules) forbids.
# To enable: supply (a) the backend log file path for timestamp-window
# correlation of failures, and (b) separate DB credentials (never reused from
# ADMIN_USERNAME/ADMIN_PASSWORD) plus explicit confirmation to add the
# --execute-db-writes flag (default OFF / dry-run, transactional, Type-1 scope
# only — deletes limited to IDs this run itself created).


# ─── HTML Report ────────────────────────────────────────────────────────────────

def generate_html_report(suites: list[TestSuite], observations: list, output_path: str,
                           duration: float, base_url: str) -> None:
    total_pass = sum(s.passed for s in suites)
    total_fail = sum(s.failed for s in suites)
    total_all = sum(s.total for s in suites)
    pass_pct = round(total_pass / total_all * 100, 1) if total_all else 0

    suite_rows = ""
    for suite in suites:
        pct = round(suite.passed / suite.total * 100, 1) if suite.total else 0
        suite_rows += f"""
        <tr>
          <td>{suite.name}</td>
          <td class="num">{suite.total}</td>
          <td class="num pass">{suite.passed}</td>
          <td class="num fail">{suite.failed}</td>
          <td class="num">{pct}%</td>
        </tr>"""

    detail_sections = ""
    for suite in suites:
        rows = ""
        for r in suite.results:
            status_class = "pass" if r.passed else "fail"
            code = r.status_code or "ERR"
            expected = ", ".join(str(s) for s in r.expected_statuses)
            note_html = f'<span class="note">{r.note}</span>' if r.note else ""
            error_html = f'<div class="error-msg">{r.error}</div>' if r.error else ""
            body_html = ""
            if r.response_body:
                short = r.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(r.response_body) > 300 else ""}</pre></details>'
            rows += f"""
            <tr class="{status_class}">
              <td><span class="badge {status_class}">{r.status_label}</span></td>
              <td><span class="method {r.method.lower()}">{r.method}</span></td>
              <td class="test-name">{r.name} {note_html}</td>
              <td class="url">{r.url}</td>
              <td class="num">{code}</td>
              <td class="num">{expected}</td>
              <td class="num">{r.duration_ms:.0f}ms</td>
              <td>{error_html}{body_html}</td>
            </tr>"""
        detail_sections += f"""
        <section>
          <h2>{suite.name} — {suite.passed}/{suite.total} passed</h2>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Test</th><th>URL</th>
              <th>Got</th><th>Expected</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </section>"""

    observation_section = ""
    if observations:
        obs_rows = ""
        for o in observations:
            code = o.status_code or "ERR"
            body_html = ""
            if o.response_body:
                short = o.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(o.response_body) > 300 else ""}</pre></details>'
            obs_rows += f"""
            <tr>
              <td><span class="badge observed">OBSERVED</span></td>
              <td><span class="method {o.method.lower()}">{o.method}</span></td>
              <td class="test-name">{o.name}</td>
              <td class="url">{o.url}</td>
              <td class="num">{code}</td>
              <td class="url">{o.source}</td>
              <td class="num">{o.duration_ms:.0f}ms</td>
              <td>{body_html}</td>
            </tr>"""
        observation_section = f"""
        <section>
          <h2>⚠️ Exploratory Observations — undocumented expected outcomes, not pass/fail</h2>
          <p style="padding:0 20px;color:#666;font-size:.85rem">
            These scenarios test documented constraints (Required/maxLength/type/undocumented
            enum values) but the API's expected response for violating them isn't specified in
            any governance document. Review the observed status/body against your intended
            behavior — do not treat these as failures of the implementation.
          </p>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Scenario</th><th>URL</th>
              <th>Observed</th><th>Source (doc/field)</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{obs_rows}</tbody>
          </table>
        </section>"""

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" />
<title>ORG Module API Test Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
<style>
  *,*::before,*::after{{box-sizing:border-box}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;margin:0;padding:20px;background:#f4f6f9;color:#1a1a2e}}
  h1{{margin-bottom:4px}} .meta{{color:#666;font-size:.9rem;margin-bottom:24px}}
  .summary{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:28px}}
  .card{{background:#fff;border-radius:10px;padding:18px 24px;box-shadow:0 2px 6px rgba(0,0,0,.08);min-width:140px;text-align:center}}
  .card .num{{font-size:2.2rem;font-weight:700;line-height:1}} .card .label{{font-size:.8rem;color:#888;margin-top:4px}}
  .card.total .num{{color:#3a86ff}} .card.pass .num{{color:#2ec4b6}} .card.fail .num{{color:#e63946}}
  .suite-table{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  table{{width:100%;border-collapse:collapse;font-size:.875rem}}
  th{{background:#f0f2f5;text-align:left;padding:10px 14px;font-weight:600;color:#555}}
  td{{padding:8px 14px;border-top:1px solid #eef0f3;vertical-align:top}}
  tr.pass td{{background:#f6fff8}} tr.fail td{{background:#fff5f5}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:10px;font-size:.75rem;font-weight:700}}
  .badge.pass{{background:#d4f7ef;color:#1a7a6f}} .badge.fail{{background:#fde8e8;color:#b91c1c}}
  .badge.observed{{background:#fff3cd;color:#8a6314}}
  .method{{display:inline-block;padding:2px 6px;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff}}
  .method.get{{background:#3a86ff}} .method.post{{background:#2ec4b6}} .method.put{{background:#f4a261}}
  .num{{text-align:center}} .url{{font-size:.75rem;color:#666;word-break:break-all;max-width:260px}}
  .test-name{{font-weight:500}} .note{{font-size:.72rem;color:#999;margin-left:6px}}
  .error-msg{{color:#b91c1c;font-size:.8rem}}
  details summary{{cursor:pointer;color:#3a86ff;font-size:.78rem;margin-top:4px}}
  pre{{background:#f8f8f8;padding:8px;border-radius:4px;font-size:.72rem;overflow-x:auto;max-width:400px;white-space:pre-wrap}}
  section{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  section h2{{padding:14px 20px;margin:0;background:#f0f2f5;font-size:1rem;border-bottom:1px solid #e0e4ea}}
</style></head>
<body>
  <h1>ORG Module API Test Report</h1>
  <p class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;·&nbsp;
     Base URL: {base_url} &nbsp;·&nbsp; Duration: {duration:.1f}s &nbsp;·&nbsp;
     Source: PLAN-ORG-001, test-plan-org-001.md, index.md, API-ORG-001..044</p>
  <div class="summary">
    <div class="card total"><div class="num">{total_all}</div><div class="label">Total</div></div>
    <div class="card pass"><div class="num">{total_pass}</div><div class="label">Passed</div></div>
    <div class="card fail"><div class="num">{total_fail}</div><div class="label">Failed</div></div>
    <div class="card total"><div class="num">{pass_pct}%</div><div class="label">Pass Rate</div></div>
  </div>
  <div class="suite-table"><table><thead><tr><th>Suite</th><th>Total</th><th>Pass</th><th>Fail</th><th>Rate</th></tr></thead>
  <tbody>{suite_rows}</tbody></table></div>
  {detail_sections}
  {observation_section}
</body></html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"\n📄 HTML report written to: {output_path}")


# ─── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="ORG module API test suite (PLAN-ORG-001)")
    parser.add_argument("--base-url", default=BASE_URL, help="Base API URL")
    parser.add_argument("--report", default="org_api_test_report.html", help="Output HTML file")
    parser.add_argument("--problems-report", default="org_problems_report.md",
        help="Output Markdown file — Stage G filtered/categorized failures only")
    args = parser.parse_args()

    client = APIClient(args.base_url)
    start_time = time.perf_counter()

    print("=" * 60)
    print("  ORG Module API Test Suite — PLAN-ORG-001")
    print(f"  Base URL: {args.base_url}")
    print("=" * 60)

    auth_suite, token = test_auth(client)
    observations: list = []
    created_ids: dict[str, list[int]] = {e: [] for e in ENTITY_TEARDOWN_ORDER}

    le_suite = TestSuite("LegalEntity")
    branch_suite = TestSuite("Branch")
    region_suite = TestSuite("Region")
    pc_suite = TestSuite("ProfitCenter")
    dept_suite = TestSuite("Department")
    cc_suite = TestSuite("CostCenter")
    ls_suite = TestSuite("LocationSite")
    deact_suite = TestSuite("Deactivation Rules (RULE-ORG-001..005)")

    try:
        # Stage B topological order: LegalEntity is the only root.
        # Branch, Region, ProfitCenter depend on LegalEntity.
        # Department, CostCenter, LocationSite depend on Branch.
        le_suite, le_ids = test_legal_entity(client, token, observations, created_ids)
        le_id = le_ids.get("id")

        branch_suite, branch_ids = test_branch(client, token, observations, created_ids, le_id)
        branch_id = branch_ids.get("id")

        region_suite, region_ids = test_region(client, token, observations, created_ids, le_id)
        pc_suite, pc_ids = test_profit_center(client, token, observations, created_ids, le_id)

        dept_suite, dept_ids = test_department(client, token, observations, created_ids, branch_id)
        if le_id:
            test_department_rule019(client, token, dept_suite, created_ids, le_id)
        dept_id = dept_ids.get("id")

        cc_suite, cc_ids = test_cost_center(client, token, observations, created_ids, branch_id, le_id)
        cc_id = cc_ids.get("id")

        ls_suite, ls_ids = test_location_site(client, token, observations, created_ids, branch_id, le_id)
        ls_id = ls_ids.get("id")

        # Cross-entity deactivation guard rules — needs every sibling's live ID.
        entity_ids = {
            "LegalEntity": le_id, "Branch": branch_id, "Region": region_ids.get("id"),
            "ProfitCenter": pc_ids.get("id"), "Department": dept_id, "CostCenter": cc_id,
            "LocationSite": ls_id,
        }
        deact_suite = test_deactivation_rules(client, token, entity_ids)
    finally:
        # Always runs, even if a test above raised partway through.
        cleanup(client, token, created_ids)

    duration = time.perf_counter() - start_time
    suites = [auth_suite, le_suite, branch_suite, region_suite, pc_suite, dept_suite, cc_suite, ls_suite, deact_suite]

    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    total_pass = sum(s.passed for s in suites)
    total_all = sum(s.total for s in suites)
    for s in suites:
        bar = "█" * s.passed + "░" * s.failed
        print(f"  {s.name:<45} {s.passed:>3}/{s.total:<3}  {bar}")
    print(f"\n  Total: {total_pass}/{total_all} passed  ({duration:.1f}s)")
    if observations:
        print(f"  Exploratory observations: {len(observations)} (see HTML report — not pass/fail)")

    generate_html_report(suites, observations, args.report, duration, args.base_url)
    generate_problems_report(suites, args.problems_report, args.base_url)
    sys.exit(0 if total_pass == total_all else 1)


if __name__ == "__main__":
    main()
