"""
sync.py — documentation synchronization layer
════════════════════════════════════════════════════════════════════
Sits strictly AFTER rendering. It never extracts anything from the backend
and never formats markdown — it only compares an already-rendered
{path: content} dict against whatever this tool previously wrote to
--output, then decides what to write, delete, or leave alone.

Rendering is deterministic (same backend state -> same rendered text), so
this layer never needs to diff DTOs/permissions/validations/error-codes
individually: any backend change already shows up as a content difference
in the relevant rendered file. Endpoint-level granularity falls out of the
existing one-file-per-endpoint layout; shared-doc granularity falls out of
diffing index.md's own "## " sections.

Every file this layer writes is stamped with MARKER as its first line. A
file only counts as "ours to manage" if it already starts with that exact
line — anything else on disk (hand-written docs, unrelated files) is never
overwritten or deleted, only reported as a conflict.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

from models.api_doc_model import Endpoint
from renderers.markdown_renderer import _slugify

MARKER = "<!-- AUTO-GENERATED by api-doc-generator — do not edit manually -->"


def _is_managed(text: str) -> bool:
    return text.startswith(MARKER)


def _unstamp(text: str) -> str:
    if not _is_managed(text):
        return text
    return text[len(MARKER):].lstrip("\n")


def _stamp(content: str) -> str:
    return MARKER + "\n" + content


def endpoint_path(ep: Endpoint) -> str:
    """Same path a Endpoint's file gets from MarkdownRenderer.render() — kept
    in one place here so the sync layer can label changes without the
    renderer needing to expose anything extra."""
    return f"endpoints/{_slugify(ep.group or 'Ungrouped')}/{ep.slug()}.md"


def is_managed_output(output: Path) -> bool:
    index = output / "index.md"
    if not index.exists():
        return False
    try:
        return _is_managed(index.read_text(encoding="utf-8"))
    except OSError:
        return False


def detect_mode(output: Path) -> str:
    return "update" if is_managed_output(output) else "generate"


def read_existing(output: Path) -> dict[str, str]:
    """Every .md file currently under output, raw (marker included if present).
    Does not distinguish managed vs. unmanaged — compare() does that."""
    existing: dict[str, str] = {}
    if not output.exists():
        return existing
    for path in output.rglob("*.md"):
        existing[path.relative_to(output).as_posix()] = path.read_text(encoding="utf-8")
    return existing


@dataclass
class EndpointChange:
    method: str
    path: str
    label: str
    file_path: str
    status: str  # "added" | "removed" | "updated" | "unchanged"


@dataclass
class SharedSectionChange:
    name: str
    status: str  # "added" | "removed" | "changed" | "unchanged"


@dataclass
class Conflict:
    file_path: str
    reason: str


@dataclass
class SyncReport:
    mode: str
    endpoint_changes: list[EndpointChange] = field(default_factory=list)
    shared_changes: list[SharedSectionChange] = field(default_factory=list)
    conflicts: list[Conflict] = field(default_factory=list)

    def by_status(self, status: str) -> list[EndpointChange]:
        return [c for c in self.endpoint_changes if c.status == status]


def _split_sections(text: str) -> dict[str, str]:
    if not text:
        return {}
    parts = re.split(r"(?m)^## (.+)$", text)
    sections: dict[str, str] = {}
    preamble = parts[0].strip()
    if preamble:
        sections["Overview"] = preamble
    it = iter(parts[1:])
    for name, body in zip(it, it):
        sections[name.strip()] = body.strip()
    return sections


def _diff_sections(old_text: str, new_text: str) -> list[SharedSectionChange]:
    old_sections = _split_sections(old_text)
    new_sections = _split_sections(new_text)
    names = list(dict.fromkeys([*old_sections.keys(), *new_sections.keys()]))
    changes = []
    for name in names:
        old = old_sections.get(name)
        new = new_sections.get(name)
        if old is None:
            status = "added"
        elif new is None:
            status = "removed"
        elif old == new:
            status = "unchanged"
        else:
            status = "changed"
        changes.append(SharedSectionChange(name=name, status=status))
    return changes


def _label_from_removed_path(path: str) -> str:
    return f"{Path(path).stem} (no longer present in the backend)"


def compare(
    existing: dict[str, str],
    new_files: dict[str, str],
    endpoints: list[Endpoint],
    mode: str,
) -> SyncReport:
    managed = {p: _unstamp(c) for p, c in existing.items() if _is_managed(c)}
    unmanaged = {p for p, c in existing.items() if not _is_managed(c)}

    report = SyncReport(mode=mode)
    seen_paths: set[str] = set()

    for ep in endpoints:
        path = endpoint_path(ep)
        seen_paths.add(path)
        label = f"{ep.method} {ep.path}"
        if path in unmanaged:
            report.conflicts.append(
                Conflict(path, f"unmanaged file already exists at this path; {label} left undocumented here")
            )
            continue
        old = managed.get(path)
        new = new_files.get(path)
        if old is None:
            status = "added"
        elif old == new:
            status = "unchanged"
        else:
            status = "updated"
        report.endpoint_changes.append(EndpointChange(ep.method, ep.path, label, path, status))

    for path in managed:
        if path.startswith("endpoints/") and path not in seen_paths:
            report.endpoint_changes.append(
                EndpointChange("", "", _label_from_removed_path(path), path, "removed")
            )

    if "index.md" in unmanaged:
        report.conflicts.append(Conflict("index.md", "unmanaged index.md already exists; shared docs left untouched"))
    else:
        report.shared_changes = _diff_sections(managed.get("index.md", ""), new_files.get("index.md", ""))

    return report


def apply(
    output: Path,
    existing: dict[str, str],
    new_files: dict[str, str],
    report: SyncReport,
) -> tuple[list[str], list[str]]:
    """Writes only added/updated files, deletes only files this run knows to
    be removed endpoints, and never touches unmanaged (conflicting) paths."""
    managed = {p: _unstamp(c) for p, c in existing.items() if _is_managed(c)}
    unmanaged = {p for p, c in existing.items() if not _is_managed(c)}

    written: list[str] = []
    for path, content in new_files.items():
        if path in unmanaged:
            continue
        if managed.get(path) == content:
            continue
        target = output / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_stamp(content), encoding="utf-8")
        written.append(path)

    deleted: list[str] = []
    for change in report.by_status("removed"):
        if change.file_path in unmanaged:
            continue
        target = output / change.file_path
        if target.exists():
            target.unlink()
            deleted.append(change.file_path)

    return written, deleted


def write_all(output: Path, new_files: dict[str, str]) -> None:
    """Generate mode: write everything, stamped, unconditionally."""
    for path, content in new_files.items():
        target = output / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_stamp(content), encoding="utf-8")


def format_report(report: SyncReport) -> str:
    added = report.by_status("added")
    removed = report.by_status("removed")
    updated = report.by_status("updated")
    unchanged = report.by_status("unchanged")

    lines = [f"Mode        : {report.mode.capitalize()}"]

    lines.append(f"Added       : {len(added)}")
    for c in added:
        lines.append(f"  + {c.label}")
    lines.append(f"Removed     : {len(removed)}")
    for c in removed:
        lines.append(f"  - {c.label}")
    lines.append(f"Updated     : {len(updated)}")
    for c in updated:
        lines.append(f"  ~ {c.label}")
    lines.append(f"Unchanged   : {len(unchanged)}")

    changed_sections = [s for s in report.shared_changes if s.status != "unchanged"]
    if changed_sections:
        lines.append("Shared docs : " + ", ".join(f"{s.name} ({s.status})" for s in changed_sections))
    else:
        lines.append("Shared docs : unchanged")

    if report.conflicts:
        lines.append(f"Conflicts   : {len(report.conflicts)} (left untouched, not regenerated)")
        for c in report.conflicts:
            lines.append(f"  ! {c.file_path}: {c.reason}")

    return "\n".join(lines)
