#!/usr/bin/env python3
"""
SECURITY module API verification script — generated by MODE 5 Engine.

Covers: Authentication, Menu Management, Page Management, Permission
Management, Role Access Control, User Management (44/44 catalog endpoints
per index.md's API Catalog).

Tier: negative tests (Stage C) ARE generated — RULE-ID + ERR-ID are fully
resolved from registry-security.md (§3 RULE REGISTRY) cross-checked against
index.md's runtime "Known Error Codes" table. NO test-plan.md was supplied,
so there are no TC-IDs; per explicit user instruction, negative tests are
still generated and tagged "TC-ID: none — no test-plan.md" rather than
skipped. Stage E exploratory scenarios run by default (API-doc-derived only).

Intended for Dev/Test environments only.
"""

import argparse
import json
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("requests library not found. Install it: pip install requests")
    sys.exit(1)


# ─── Configuration (placeholders — never invent real credentials) ─────────────

BASE_URL = "http://localhost:7272"
TIMEOUT = 15  # seconds

ADMIN_USERNAME = "admin"  # CHANGE ME
ADMIN_PASSWORD = "admin"  # CHANGE ME

# Intended for Dev/Test environments only.

# Unique per-run suffix — avoids collisions with unique-constrained fields
# (pageCode, route, roleCode, roleName, username, permission name) across
# repeated runs against the same database.
RUN_ID = str(int(time.time()))[-8:]


# ─── Data classes (fixed pattern — do not change per module) ──────────────────

@dataclass
class TestResult:
    name: str
    method: str
    url: str
    status_code: Optional[int]
    passed: bool
    expected_statuses: list[int]
    duration_ms: float
    error: Optional[str] = None
    response_body: Optional[str] = None
    note: Optional[str] = None

    @property
    def status_label(self) -> str:
        return "PASS" if self.passed else "FAIL"


@dataclass
class TestSuite:
    name: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed(self) -> int:
        return len(self.results) - self.passed

    @property
    def total(self) -> int:
        return len(self.results)


@dataclass
class Observation:
    """
    Stage E exploratory scenario with an UNDOCUMENTED expected outcome. Never
    counted as pass/fail — the point is to record actual behavior for human
    review, not to assert a guessed business rule.
    """
    name: str
    method: str
    url: str
    status_code: Optional[int]
    duration_ms: float
    source: str
    response_body: Optional[str] = None


@dataclass
class ProblemEntry:
    bucket: str  # "real_bug" | "assumption_mismatch" | "infrastructure"
    name: str
    detail: str
    result: "TestResult"


# ─── HTTP helper (fixed) ───────────────────────────────────────────────────────

class APIClient:
    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "Content-Type": "application/json",
        })

    def _make(self, method: str, path: str, token: Optional[str] = None,
              expected: Optional[list[int]] = None, **kwargs) -> TestResult:
        url = f"{self.base_url}/{path.lstrip('/')}"
        headers = kwargs.pop("headers", {})
        if token:
            headers["Authorization"] = f"Bearer {token}"
        if expected is None:
            expected = [200]

        start = time.perf_counter()
        try:
            resp = self.session.request(method.upper(), url, headers=headers, timeout=TIMEOUT, **kwargs)
            duration = (time.perf_counter() - start) * 1000
            try:
                body = json.dumps(resp.json(), indent=2, ensure_ascii=False)
            except Exception:
                body = resp.text[:500]
            return TestResult(
                name="", method=method.upper(), url=url, status_code=resp.status_code,
                passed=resp.status_code in expected, expected_statuses=expected,
                duration_ms=round(duration, 1), response_body=body,
            )
        except requests.exceptions.ConnectionError:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1),
                error="Connection refused — is the server running?",
            )
        except Exception as exc:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1), error=str(exc),
            )

    def get(self, path, token=None, expected=None, **kw):
        return self._make("GET", path, token, expected, **kw)

    def post(self, path, token=None, expected=None, **kw):
        return self._make("POST", path, token, expected, **kw)

    def put(self, path, token=None, expected=None, **kw):
        return self._make("PUT", path, token, expected, **kw)

    def delete(self, path, token=None, expected=None, **kw):
        return self._make("DELETE", path, token, expected, **kw)


# ─── Test runner helpers (fixed) ───────────────────────────────────────────────

def run(suite: TestSuite, name: str, result: TestResult, note: str = "") -> TestResult:
    result.name = name
    result.note = note
    suite.results.append(result)
    status = "✓" if result.passed else "✗"
    code = result.status_code or "ERR"
    print(f"  {status} [{code}] {name} ({result.duration_ms:.0f}ms)")
    if not result.passed and result.error:
        print(f"      Error: {result.error}")
    return result


def run_observation(bucket: list, name: str, source: str, result: TestResult) -> None:
    obs = Observation(
        name=name, method=result.method, url=result.url, status_code=result.status_code,
        duration_ms=result.duration_ms, source=source, response_body=result.response_body,
    )
    bucket.append(obs)
    code = result.status_code or "ERR"
    print(f"  👁 [{code}] {name} — observed (source: {source})")


def data_of(result: TestResult):
    """
    Envelope shape {success, message, data, error, timestamp, correlationId}
    confirmed against index.md's "Common Response Envelope" (Schema:
    ApiResponseUserDto).
    """
    if not result.response_body:
        return None
    try:
        return json.loads(result.response_body).get("data")
    except Exception:
        return None


def error_code_of(result: TestResult) -> Optional[str]:
    if not result.response_body:
        return None
    try:
        err = json.loads(result.response_body).get("error")
        return err.get("code") if isinstance(err, dict) else None
    except Exception:
        return None


def extract_token(result: TestResult) -> Optional[str]:
    d = data_of(result)
    return d.get("accessToken") if isinstance(d, dict) else None


def extract_id(result: TestResult) -> Optional[int]:
    d = data_of(result)
    return d.get("id") if isinstance(d, dict) else None


def extract_page_first_id(result: TestResult) -> Optional[int]:
    """
    Pagination envelope per index.md: totalElements, totalPages, size,
    number (NOT "page"), numberOfElements, first, last, empty, sort,
    pageable. `content` array is standard for Page<T> but not explicitly
    tabulated in index.md's Pagination Envelope section — treated as a
    documentation gap, not proof it's absent from the real response.
    """
    d = data_of(result)
    if isinstance(d, dict):
        content = d.get("content")  # unconfirmed in table — flagged, not asserted on
        if isinstance(content, list) and content:
            return content[0].get("id")
    return None


# ─── Auth (fixed pattern, extended: loginWithToken / refresh / logout) ────────
# Covers: API login, loginWithToken, refresh, logout
# (Authentication group — all 4/4 catalog endpoints)

def test_auth(client: APIClient) -> tuple[TestSuite, Optional[str]]:
    suite = TestSuite("Auth")
    print("\n[Auth]")
    r = run(suite, "Admin Login", client.post(
        "api/auth/login", expected=[200],
        json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
    ))
    token = extract_token(r)

    # loginWithToken — separate call, doesn't affect `token` used for the rest
    # of the script; asserts the richer UserInfo shape (roles/permissions).
    run(suite, "Login With Token (full UserInfo)", client.post(
        "api/auth/login-token", expected=[200],
        json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
    ))

    # refresh — relies on the refresh_token HttpOnly cookie set by the Login
    # call above (requests.Session retains cookies automatically).
    run(suite, "Refresh Access Token", client.post("api/auth/refresh", token=token, expected=[200]))

    # logout — revokes tokens via the same session cookie. Performed last in
    # this suite; does not invalidate the already-issued `token` string used
    # for Bearer auth in the rest of the script (stateless JWT, only the
    # refresh token/cookie is revoked — Rule 3/Rule 4/Rule 5 all describe
    # refresh-token rotation/revocation, not access-token blacklisting).
    run(suite, "Logout", client.post("api/auth/logout", token=token, expected=[204]))

    return suite, token


# ─── Menu (read-only, no FK dependency) ────────────────────────────────────────
# Covers: getUserMenu, getUserMenuById (Menu Management group — 2/2)

def test_menu(client: APIClient, token: Optional[str], admin_user_id: Optional[int]) -> TestSuite:
    suite = TestSuite("Menu")
    print("\n[Menu]")
    run(suite, "Get User Menu (self)", client.get("api/menu/user-menu", token=token, expected=[200]))
    if admin_user_id:
        run(suite, "Get User Menu By ID (admin)", client.get(
            f"api/menu/user-menu/{admin_user_id}", token=token, expected=[200]))
    else:
        print("  ⚠ Skipped Get User Menu By ID — admin user ID not resolved")
    return suite


# ─── Page (root entity, no FK dependency) ──────────────────────────────────────
# Covers: createPage, getPageById, updatePage, deactivatePage, reactivatePage,
#         searchPages, getActivePages (Page Management group — 7/7)
# Negative: RULE-SEC-019/DUPLICATE_ROUTE, RULE-SEC-016/INVALID_PAGE_CODE_FORMAT,
#           RULE-SEC-017+018/INVALID_ROUTE_FORMAT, RULE-SEC-020/PARENT_PAGE_NOT_FOUND
#           (TC-ID: none — no test-plan.md)
# Also: DUPLICATE_PAGE_CODE tested but flagged — inferred from UK_PAGES_CODE
# constraint + createPage's "Unique page code" field description; no explicit
# numbered RULE-ID in registry-security.md §3 covers pageCode duplication
# specifically (only route duplication is numbered — rule 19).

def test_page(client: APIClient, token: Optional[str], observations: list,
              created_ids: dict[str, list[int]]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Page")
    ids: dict = {}
    print("\n[Page]")

    page_code = f"TESTPAGE{RUN_ID}"
    route = f"/test/page{RUN_ID}"

    r = run(suite, "Create Page", client.post(
        "api/pages", token=token, expected=[200, 201],
        json={
            "pageCode": page_code, "nameAr": "صفحة تجريبية", "nameEn": "Test Page",
            "route": route, "icon": "pi pi-file", "module": "SECURITY",
            "displayOrder": 10, "active": True, "description": "Created by generated test script",
        },
    ))
    page_id = extract_id(r)
    ids["id"] = page_id
    ids["pageCode"] = page_code
    if page_id:
        created_ids.setdefault("Page", []).append(page_id)

    if page_id:
        run(suite, "Get Page by ID", client.get(f"api/pages/{page_id}", token=token, expected=[200]))
    run(suite, "Get Page by ID — Not Found", client.get("api/pages/999999999", token=token, expected=[404]))

    if page_id:
        run(suite, "Update Page", client.put(
            f"api/pages/{page_id}", token=token, expected=[200],
            json={
                "nameAr": "صفحة محدثة", "nameEn": "Updated Test Page", "route": route,
                "icon": "pi pi-file", "module": "SECURITY", "displayOrder": 20,
                "description": "Updated by generated test script",
            },
        ))

    run(suite, "Search Pages", client.post(
        "api/pages/search", token=token, expected=[200],
        json={"filters": [{"field": "pageCode", "operator": "EQUALS", "value": page_code}], "page": 0, "size": 20},
    ))
    run(suite, "Get Active Pages", client.get("api/pages/active", token=token, expected=[200]))

    # ── Stage C — governed negative tests (RULE-ID + ERR-ID, TC-ID: none) ──
    r_dup_route = run(suite, "Create Page — duplicate route (RULE-SEC-019 / DUPLICATE_ROUTE) [TC-ID: none — no test-plan.md]",
        client.post("api/pages", token=token, expected=[409],
            json={"pageCode": f"TESTPAGE2{RUN_ID}", "nameAr": "صفحة", "nameEn": "Dup Route Page",
                  "route": route, "active": True}))
    if error_code_of(r_dup_route) not in (None, "DUPLICATE_ROUTE"):
        print(f"      ⚠ error.code was {error_code_of(r_dup_route)!r}, expected 'DUPLICATE_ROUTE'")

    r_dup_code = run(suite, "Create Page — duplicate pageCode (inferred from UK_PAGES_CODE, no explicit RULE-ID) [TC-ID: none]",
        client.post("api/pages", token=token, expected=[409],
            json={"pageCode": page_code, "nameAr": "صفحة", "nameEn": "Dup Code Page",
                  "route": f"/test/page-dup{RUN_ID}", "active": True}))
    if error_code_of(r_dup_code) not in (None, "DUPLICATE_PAGE_CODE"):
        print(f"      ⚠ error.code was {error_code_of(r_dup_code)!r}, expected 'DUPLICATE_PAGE_CODE'")

    r_bad_code = run(suite, "Create Page — invalid pageCode format (RULE-SEC-016 / INVALID_PAGE_CODE_FORMAT) [TC-ID: none]",
        client.post("api/pages", token=token, expected=[400],
            json={"pageCode": "bad-code!", "nameAr": "صفحة", "nameEn": "Bad Code Page",
                  "route": f"/test/badcode{RUN_ID}", "active": True}))
    if error_code_of(r_bad_code) not in (None, "INVALID_PAGE_CODE_FORMAT"):
        print(f"      ⚠ error.code was {error_code_of(r_bad_code)!r}, expected 'INVALID_PAGE_CODE_FORMAT'")

    run(suite, "Create Page — route missing leading slash (RULE-SEC-017 / INVALID_ROUTE_FORMAT) [TC-ID: none]",
        client.post("api/pages", token=token, expected=[400],
            json={"pageCode": f"NOSLASH{RUN_ID}", "nameAr": "صفحة", "nameEn": "No Slash Page",
                  "route": f"test-no-slash{RUN_ID}", "active": True}))

    run(suite, "Create Page — route contains spaces (RULE-SEC-018 / INVALID_ROUTE_FORMAT) [TC-ID: none]",
        client.post("api/pages", token=token, expected=[400],
            json={"pageCode": f"SPACEY{RUN_ID}", "nameAr": "صفحة", "nameEn": "Spacey Route Page",
                  "route": f"/test with space{RUN_ID}", "active": True}))

    r_parent = run(suite, "Create Page — parentId not found (RULE-SEC-020 / PARENT_PAGE_NOT_FOUND) [TC-ID: none]",
        client.post("api/pages", token=token, expected=[404],
            json={"pageCode": f"ORPHAN{RUN_ID}", "nameAr": "صفحة", "nameEn": "Orphan Page",
                  "route": f"/test/orphan{RUN_ID}", "parentId": 999999999, "active": True}))
    if error_code_of(r_parent) not in (None, "PARENT_PAGE_NOT_FOUND"):
        print(f"      ⚠ error.code was {error_code_of(r_parent)!r}, expected 'PARENT_PAGE_NOT_FOUND'")

    # Track any Create calls above that unexpectedly *succeeded* (2xx) so
    # Stage F cleanup doesn't leak them, even though they were meant to fail.
    for r_neg in (r_dup_route, r_dup_code, r_bad_code):
        if (nid := extract_id(r_neg)):
            created_ids.setdefault("Page", []).append(nid)

    # ── Stage E — exploratory scenarios (bounded to Required=Yes / maxLength
    # fields per createPage.md's Constraints column). nameAr skipped as a
    # boundary target — shares nameEn's identical maxLength=100/Required=Yes
    # constraint; testing both would exercise the same validator twice.

    # pageCode maxLength: 50
    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": "A" * 50, "nameAr": "صفحة", "nameEn": "Boundary Page",
              "route": f"/test/bound50{RUN_ID}", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — pageCode at maxLength (50 chars)",
        source="createPage.md pageCode Constraints: maxLength=50", result=r)

    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": "A" * 51, "nameAr": "صفحة", "nameEn": "Over Boundary Page",
              "route": f"/test/bound51{RUN_ID}", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — pageCode over maxLength (51 chars)",
        source="createPage.md pageCode Constraints: maxLength=50", result=r)

    # nameEn maxLength: 100
    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": f"NAMEBOUND{RUN_ID}", "nameAr": "صفحة", "nameEn": "X" * 100,
              "route": f"/test/namebound{RUN_ID}", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — nameEn at maxLength (100 chars)",
        source="createPage.md nameEn Constraints: maxLength=100", result=r)

    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": f"NAMEOVER{RUN_ID}", "nameAr": "صفحة", "nameEn": "X" * 101,
              "route": f"/test/nameover{RUN_ID}", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — nameEn over maxLength (101 chars)",
        source="createPage.md nameEn Constraints: maxLength=100", result=r)

    # route maxLength: 200 (kept slash-prefixed, no spaces, to isolate the
    # length boundary from the format rules already covered in Stage C)
    route_200 = "/" + ("a" * 199)
    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": f"ROUTEBOUND{RUN_ID}", "nameAr": "صفحة", "nameEn": "Route Boundary Page",
              "route": route_200, "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — route at maxLength (200 chars)",
        source="createPage.md route Constraints: maxLength=200", result=r)

    # Required-field omission
    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"nameAr": "صفحة بدون كود", "nameEn": "No Code Page", "route": f"/test/nocode{RUN_ID}", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — omit required pageCode",
        source="createPage.md pageCode Required=Yes", result=r)

    r = client.post("api/pages", token=token, expected=[200, 201, 400],
        json={"pageCode": f"NOROUTE{RUN_ID}", "nameAr": "صفحة", "nameEn": "No Route Page", "active": True})
    if (bid := extract_id(r)):
        created_ids.setdefault("Page", []).append(bid)
    run_observation(observations, "Create Page — omit required route",
        source="createPage.md route Required=Yes", result=r)

    return suite, ids


# ─── Permission (optional FK -> Page via pageId) ───────────────────────────────
# Covers: create_1, update_1, searchPermissions (Permission Management — 3/3)
# NOTE: catalog has no getById/deactivate/delete for Permission — pattern is
# necessarily Create -> Update -> Search only.
# Negative: PERMISSION_ALREADY_EXISTS tested but flagged — inferred from
# UK_PERMS_NAME constraint (§1.4); no explicit numbered RULE-ID in §3 covers
# permission-name duplication. (TC-ID: none — no test-plan.md)

def test_permission(client: APIClient, token: Optional[str], page_id: Optional[int],
                     observations: list, created_ids: dict[str, list[int]]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Permission")
    ids: dict = {}
    print("\n[Permission]")

    perm_name = f"PERM_TEST_{RUN_ID}"

    r = run(suite, "Create Permission", client.post(
        "api/permissions", token=token, expected=[200, 201],
        json={"name": perm_name, "pageId": page_id, "permissionType": "VIEW"},
    ))
    perm_id = extract_id(r)
    ids["id"] = perm_id
    if perm_id:
        created_ids.setdefault("Permission", []).append(perm_id)

    if perm_id:
        run(suite, "Update Permission", client.put(
            f"api/permissions/{perm_id}", token=token, expected=[200],
            json={"name": f"{perm_name}_UPDATED"},
        ))

    run(suite, "Search Permissions", client.post(
        "api/permissions/search", token=token, expected=[200],
        json={"filters": [{"field": "name", "operator": "CONTAINS", "value": "PERM_TEST"}], "page": 0, "size": 20},
    ))

    # ── Stage C — inferred negative (flagged, no explicit RULE-ID) ──
    # Uses the post-Update name: `perm_name` itself was freed up by the
    # "Update Permission" rename above, so checking against it would no
    # longer collide with anything.
    dup_check_name = f"{perm_name}_UPDATED" if perm_id else perm_name
    r_dup = run(suite, "Create Permission — duplicate name (inferred from UK_PERMS_NAME, no explicit RULE-ID) [TC-ID: none]",
        client.post("api/permissions", token=token, expected=[409],
            json={"name": dup_check_name, "permissionType": "VIEW"}))
    if error_code_of(r_dup) not in (None, "PERMISSION_ALREADY_EXISTS"):
        print(f"      ⚠ error.code was {error_code_of(r_dup)!r}, expected 'PERMISSION_ALREADY_EXISTS'")
    if (nid := extract_id(r_dup)):
        created_ids.setdefault("Permission", []).append(nid)

    # ── Stage E — exploratory. `name` is Required=Yes but create_1.md states
    # no maxLength — DB column is VARCHAR(150) (registry §1.4) but that's a
    # schema fact, not a documented API-doc constraint, so no boundary test
    # is generated per the scope cap (constraint must be stated in the doc's
    # own Constraints column). Omission + type-mismatch only.
    r = client.post("api/permissions", token=token, expected=[200, 201, 400],
        json={"pageId": page_id, "permissionType": "VIEW"})
    if (nid := extract_id(r)):
        created_ids.setdefault("Permission", []).append(nid)
    run_observation(observations, "Create Permission — omit required name",
        source="create_1.md name Required=Yes", result=r)

    r = client.post("api/permissions", token=token, expected=[200, 201, 400],
        json={"name": f"PERM_TYPEMISMATCH_{RUN_ID}", "pageId": "not-an-integer", "permissionType": "VIEW"})
    if (nid := extract_id(r)):
        created_ids.setdefault("Permission", []).append(nid)
    run_observation(observations, "Create Permission — pageId type mismatch (string instead of int64)",
        source="create_1.md pageId Type: integer (int64)", result=r)

    return suite, ids


# ─── Role (FK -> Page via pageCode for page-assignment endpoints) ─────────────
# Covers: createRole, getRoleById, updateRole, deleteRole, toggleRoleActive,
#         getRolePages, syncRolePages, addPageToRole, copyFromRole,
#         searchRoles, removePageFromRole (Role Access Control — 11/11)
# Negative: RULE-SEC-009/DUPLICATE_ROLE_NAME, RULE-SEC-009a/DUPLICATE_ROLE_CODE,
#           RULE-SEC-013/PAGE_ALREADY_ASSIGNED_TO_ROLE,
#           RULE-SEC-014/INVALID_PERMISSION_TYPE, RULE-SEC-024/NO_PERMISSIONS_TO_COPY,
#           RULE-SEC-010/ROLE_IN_USE (TC-ID: none — no test-plan.md)
# Also: copyFromRole(targetRoleId==sourceRoleId) tested for its documented
# 400 status (API doc prose, §2.3) but the error.code (INVALID_OPERATION) is
# NOT in index.md's Known Error Codes table — asserting only the status,
# per "state that the assertion is skipped/unconfirmed rather than guessing".

def test_role(client: APIClient, token: Optional[str], page_code: Optional[str],
              observations: list, created_ids: dict[str, list[int]]) -> tuple[TestSuite, dict]:
    suite = TestSuite("Role")
    ids: dict = {}
    print("\n[Role]")

    role_code = f"TESTROLE{RUN_ID}"
    role_name = f"Test Role {RUN_ID}"

    r = run(suite, "Create Role", client.post(
        "api/roles", token=token, expected=[200, 201],
        json={"roleCode": role_code, "roleName": role_name, "description": "Created by generated test script", "active": True},
    ))
    role_id = extract_id(r)
    ids["id"] = role_id
    ids["roleName"] = role_name
    if role_id:
        created_ids.setdefault("Role", []).append(role_id)

    if role_id:
        run(suite, "Get Role by ID", client.get(f"api/roles/{role_id}", token=token, expected=[200]))
    run(suite, "Get Role by ID — Not Found", client.get("api/roles/999999999", token=token, expected=[404]))

    if role_id:
        run(suite, "Update Role", client.put(
            f"api/roles/{role_id}", token=token, expected=[200],
            json={"roleName": role_name, "description": "Updated by generated test script", "active": True},
        ))
        run(suite, "Toggle Role Active (deactivate)", client.put(
            f"api/roles/{role_id}/toggle-active", token=token, expected=[200], json={"active": False}))
        run(suite, "Toggle Role Active (reactivate)", client.put(
            f"api/roles/{role_id}/toggle-active", token=token, expected=[200], json={"active": True}))

    run(suite, "Search Roles", client.post(
        "api/roles/search", token=token, expected=[200],
        json={"filters": [{"field": "roleName", "operator": "EQUALS", "value": role_name}], "page": 0, "size": 20},
    ))

    if role_id and page_code:
        run(suite, "Add Page to Role", client.post(
            f"api/roles/{role_id}/pages", token=token, expected=[200, 201],
            json={"pageCode": page_code, "permissions": ["CREATE", "UPDATE"]},
        ))
        run(suite, "Get Role Pages Matrix", client.get(f"api/roles/{role_id}/pages", token=token, expected=[200]))

        # Stage C — page already assigned (RULE-SEC-013)
        r_dup_assign = run(suite, "Add Page to Role — already assigned (RULE-SEC-013 / PAGE_ALREADY_ASSIGNED_TO_ROLE) [TC-ID: none]",
            client.post(f"api/roles/{role_id}/pages", token=token, expected=[409],
                json={"pageCode": page_code, "permissions": ["CREATE"]}))
        if error_code_of(r_dup_assign) not in (None, "PAGE_ALREADY_ASSIGNED_TO_ROLE"):
            print(f"      ⚠ error.code was {error_code_of(r_dup_assign)!r}, expected 'PAGE_ALREADY_ASSIGNED_TO_ROLE'")

        run(suite, "Sync Role Pages (full replace)", client.put(
            f"api/roles/{role_id}/pages", token=token, expected=[200],
            json={"assignments": [{"pageCode": page_code, "permissions": ["CREATE", "UPDATE", "DELETE"]}]},
        ))

        run(suite, "Remove Page from Role", client.delete(
            f"api/roles/{role_id}/pages/{page_code}", token=token, expected=[204, 200]))
    else:
        print("  ⚠ Skipped page-assignment endpoints — no page_code available from Page suite")

    # ── Stage C — duplicate name / duplicate code ──
    r_dup_name = run(suite, "Create Role — duplicate roleName (RULE-SEC-009 / DUPLICATE_ROLE_NAME) [TC-ID: none]",
        client.post("api/roles", token=token, expected=[409],
            json={"roleCode": f"OTHERCODE{RUN_ID}", "roleName": role_name, "active": True}))
    if error_code_of(r_dup_name) not in (None, "DUPLICATE_ROLE_NAME"):
        print(f"      ⚠ error.code was {error_code_of(r_dup_name)!r}, expected 'DUPLICATE_ROLE_NAME'")
    if (nid := extract_id(r_dup_name)):
        created_ids.setdefault("Role", []).append(nid)

    r_dup_code = run(suite, "Create Role — duplicate roleCode (RULE-SEC-009a / DUPLICATE_ROLE_CODE) [TC-ID: none]",
        client.post("api/roles", token=token, expected=[409],
            json={"roleCode": role_code, "roleName": f"Other Name {RUN_ID}", "active": True}))
    if error_code_of(r_dup_code) not in (None, "DUPLICATE_ROLE_CODE"):
        print(f"      ⚠ error.code was {error_code_of(r_dup_code)!r}, expected 'DUPLICATE_ROLE_CODE'")
    if (nid := extract_id(r_dup_code)):
        created_ids.setdefault("Role", []).append(nid)

    # ── Stage C — invalid permission type (RULE-SEC-014). Only meaningful
    # if we have a second, unassigned page_code; reuses page_code but on a
    # role with no prior assignment for it would be ideal — since page_code
    # was already removed above (Remove Page from Role), it's available again.
    if role_id and page_code:
        r_invalid_type = run(suite, "Add Page to Role — VIEW explicitly in permissions (RULE-SEC-014 / INVALID_PERMISSION_TYPE) [TC-ID: none]",
            client.post(f"api/roles/{role_id}/pages", token=token, expected=[400],
                json={"pageCode": page_code, "permissions": ["VIEW"]}))
        if error_code_of(r_invalid_type) not in (None, "INVALID_PERMISSION_TYPE"):
            print(f"      ⚠ error.code was {error_code_of(r_invalid_type)!r}, expected 'INVALID_PERMISSION_TYPE'")

    # ── Stage C — copy permissions: zero page-scoped permissions on source
    # (RULE-SEC-024 / NO_PERMISSIONS_TO_COPY). Use a second freshly-created,
    # page-less role as the source.
    r_src = client.post("api/roles", token=token, expected=[200, 201],
        json={"roleCode": f"EMPTYSRC{RUN_ID}", "roleName": f"Empty Source Role {RUN_ID}", "active": True})
    empty_src_id = extract_id(r_src)
    if empty_src_id:
        created_ids.setdefault("Role", []).append(empty_src_id)
    if role_id and empty_src_id:
        r_no_perms = run(suite, "Copy From Role — source has zero page-scoped perms (RULE-SEC-024 / NO_PERMISSIONS_TO_COPY) [TC-ID: none]",
            client.post(f"api/roles/{role_id}/copy-from/{empty_src_id}", token=token, expected=[409]))
        if error_code_of(r_no_perms) not in (None, "NO_PERMISSIONS_TO_COPY"):
            print(f"      ⚠ error.code was {error_code_of(r_no_perms)!r}, expected 'NO_PERMISSIONS_TO_COPY'")

        # copyFromRole(target == source) — documented 400 in API prose (§2.3),
        # but INVALID_OPERATION is not in index.md's Known Error Codes table,
        # so status only is asserted; error.code is NOT asserted (unconfirmed).
        run(suite, "Copy From Role — target == source (documented 400 in API spec prose, error.code unconfirmed) [TC-ID: none]",
            client.post(f"api/roles/{role_id}/copy-from/{role_id}", token=token, expected=[400]))

    # ── Stage C — delete role that has an active user assignment
    # (RULE-SEC-010 / ROLE_IN_USE). Throwaway role + throwaway user, cleaned
    # up (unassigned) immediately after the assertion so Stage F teardown's
    # hard-delete of both records isn't blocked afterward.
    riu_role_code = f"RIUROLE{RUN_ID}"
    riu_role_name = f"RIU Role {RUN_ID}"
    r_riu_role = client.post("api/roles", token=token, expected=[200, 201],
        json={"roleCode": riu_role_code, "roleName": riu_role_name, "active": True})
    riu_role_id = extract_id(r_riu_role)
    if riu_role_id:
        created_ids.setdefault("Role", []).append(riu_role_id)

    riu_username = f"riu_user_{RUN_ID}"
    r_riu_user = client.post("api/users", token=token, expected=[200, 201],
        json={"username": riu_username, "password": "TestPass123"})
    riu_user_id = extract_id(r_riu_user)
    if riu_user_id:
        created_ids.setdefault("User", []).append(riu_user_id)

    if riu_role_id and riu_user_id:
        client.put(f"api/users/{riu_user_id}/roles", token=token, expected=[200], json={"roleNames": [riu_role_name]})
        r_blocked = run(suite, "Delete Role — blocked by active user assignment (RULE-SEC-010 / ROLE_IN_USE) [TC-ID: none]",
            client.delete(f"api/roles/{riu_role_id}", token=token, expected=[409]))
        if error_code_of(r_blocked) not in (None, "ROLE_IN_USE"):
            print(f"      ⚠ error.code was {error_code_of(r_blocked)!r}, expected 'ROLE_IN_USE'")
        # Unblock for Stage F teardown: full-replace the user's roles to empty.
        client.put(f"api/users/{riu_user_id}/roles", token=token, expected=[200], json={"roleNames": []})

    # ── Stage E — exploratory (roleCode: Required=Yes + pattern constraint;
    # roleName: Required=Yes, no length constraint stated -> omission only)
    r = client.post("api/roles", token=token, expected=[200, 201, 400],
        json={"roleCode": f"lowercase{RUN_ID}", "roleName": f"Lowercase Code Role {RUN_ID}", "active": True})
    if (nid := extract_id(r)):
        created_ids.setdefault("Role", []).append(nid)
    run_observation(observations, "Create Role — roleCode violates pattern (lowercase, not ^[A-Z][A-Z0-9_]*$)",
        source="createRole.md roleCode Constraints: pattern=^[A-Z][A-Z0-9_]*$", result=r)

    r = client.post("api/roles", token=token, expected=[200, 201, 400],
        json={"roleName": f"No Code Role {RUN_ID}", "active": True})
    if (nid := extract_id(r)):
        created_ids.setdefault("Role", []).append(nid)
    run_observation(observations, "Create Role — omit required roleCode",
        source="createRole.md roleCode Required=Yes", result=r)

    r = client.post("api/roles", token=token, expected=[200, 201, 400],
        json={"roleCode": f"NONAME{RUN_ID}", "active": True})
    if (nid := extract_id(r)):
        created_ids.setdefault("Role", []).append(nid)
    run_observation(observations, "Create Role — omit required roleName",
        source="createRole.md roleName Required=Yes", result=r)

    return suite, ids


# ─── User (FK -> Role via roleNames for assignRoles) ──────────────────────────
# Covers: create, all, search, assignRoles, getUserRoles, update, delete
# (User Management — 7/7)
# Negative: RULE-SEC-006/USERNAME_ALREADY_EXISTS,
#           RULE-SEC-007/USER_HAS_ACTIVE_REFRESH_TOKENS
#           (TC-ID: none — no test-plan.md)

def test_user(client: APIClient, token: Optional[str], role_name: Optional[str],
              observations: list, created_ids: dict[str, list[int]]) -> tuple[TestSuite, dict]:
    suite = TestSuite("User")
    ids: dict = {}
    print("\n[User]")

    username = f"testuser_{RUN_ID}"
    password = "TestPass123"

    r = run(suite, "Create User", client.post(
        "api/users", token=token, expected=[200, 201],
        json={"username": username, "password": password},
    ))
    user_id = extract_id(r)
    ids["id"] = user_id
    if user_id:
        created_ids.setdefault("User", []).append(user_id)

    run(suite, "List All Users", client.get("api/users", token=token, expected=[200], params={"pageable": "id,asc"}))

    run(suite, "Search Users", client.post(
        "api/users/search", token=token, expected=[200],
        json={"filters": [{"field": "username", "operator": "EQ", "value": username}], "page": 0, "size": 20},
    ))

    if user_id and role_name:
        run(suite, "Assign Roles to User", client.put(
            f"api/users/{user_id}/roles", token=token, expected=[200], json={"roleNames": [role_name]}))
        run(suite, "Get User Roles", client.get(f"api/users/{user_id}/roles", token=token, expected=[200]))

    if user_id:
        run(suite, "Update User", client.put(
            f"api/users/{user_id}", token=token, expected=[200], json={"enabled": True}))

    # ── Stage C — duplicate username (RULE-SEC-006) ──
    r_dup = run(suite, "Create User — duplicate username (RULE-SEC-006 / USERNAME_ALREADY_EXISTS) [TC-ID: none]",
        client.post("api/users", token=token, expected=[409],
            json={"username": username, "password": password}))
    if error_code_of(r_dup) not in (None, "USERNAME_ALREADY_EXISTS"):
        print(f"      ⚠ error.code was {error_code_of(r_dup)!r}, expected 'USERNAME_ALREADY_EXISTS'")
    if (nid := extract_id(r_dup)):
        created_ids.setdefault("User", []).append(nid)

    # ── Stage C — delete blocked by active refresh token (RULE-SEC-007).
    # A throwaway user logs in (via a separate APIClient/session so the main
    # admin session's cookies are untouched), which creates a REFRESH_TOKENS
    # row; admin's delete attempt should then be blocked. Unblocked via
    # logout immediately after the assertion so Stage F teardown can
    # hard-delete this user later.
    art_username = f"art_user_{RUN_ID}"
    art_password = "TestPass123"
    r_art_create = client.post("api/users", token=token, expected=[200, 201],
        json={"username": art_username, "password": art_password})
    art_user_id = extract_id(r_art_create)
    if art_user_id:
        created_ids.setdefault("User", []).append(art_user_id)

    if art_user_id:
        temp_client = APIClient(client.base_url)
        r_art_login = temp_client.post("api/auth/login", expected=[200],
            json={"username": art_username, "password": art_password})
        art_token = extract_token(r_art_login)

        r_blocked = run(suite, "Delete User — blocked by active refresh token (RULE-SEC-007 / USER_HAS_ACTIVE_REFRESH_TOKENS) [TC-ID: none]",
            client.delete(f"api/users/{art_user_id}", token=token, expected=[409]))
        if error_code_of(r_blocked) not in (None, "USER_HAS_ACTIVE_REFRESH_TOKENS"):
            print(f"      ⚠ error.code was {error_code_of(r_blocked)!r}, expected 'USER_HAS_ACTIVE_REFRESH_TOKENS'")

        # Unblock: revoke the refresh token via logout (uses temp_client's
        # own cookie jar), so Stage F's later hard-delete can succeed.
        if art_token:
            temp_client.post("api/auth/logout", token=art_token, expected=[200])

    # ── Stage E — exploratory (username: Required=Yes, maxLength=80/minLength=3;
    # password: Required=Yes, maxLength=120/minLength=6)
    r = client.post("api/users", token=token, expected=[200, 201, 400],
        json={"username": "a" * 80, "password": password})
    if (nid := extract_id(r)):
        created_ids.setdefault("User", []).append(nid)
    run_observation(observations, "Create User — username at maxLength (80 chars)",
        source="create.md username Constraints: maxLength=80", result=r)

    r = client.post("api/users", token=token, expected=[200, 201, 400],
        json={"username": "a" * 81, "password": password})
    if (nid := extract_id(r)):
        created_ids.setdefault("User", []).append(nid)
    run_observation(observations, "Create User — username over maxLength (81 chars)",
        source="create.md username Constraints: maxLength=80", result=r)

    r = client.post("api/users", token=token, expected=[200, 201, 400],
        json={"username": "ab", "password": password})
    if (nid := extract_id(r)):
        created_ids.setdefault("User", []).append(nid)
    run_observation(observations, "Create User — username under minLength (2 chars, min=3)",
        source="create.md username Constraints: minLength=3", result=r)

    r = client.post("api/users", token=token, expected=[200, 201, 400],
        json={"username": f"pwshort_{RUN_ID}", "password": "abcde"})
    if (nid := extract_id(r)):
        created_ids.setdefault("User", []).append(nid)
    run_observation(observations, "Create User — password under minLength (5 chars, min=6)",
        source="create.md password Constraints: minLength=6", result=r)

    r = client.post("api/users", token=token, expected=[200, 201, 400],
        json={"password": password})
    if (nid := extract_id(r)):
        created_ids.setdefault("User", []).append(nid)
    run_observation(observations, "Create User — omit required username",
        source="create.md username Required=Yes", result=r)

    return suite, ids


# ─── Cleanup / Teardown (best-effort — see per-entity capability notes) ──────

# Reverse of the Stage B dependency/creation order: User -> Role -> Permission
# -> Page, so FK/business-rule dependencies (role must not be in use, etc.)
# don't block deactivation/deletion of a still-referenced parent.
ENTITY_TEARDOWN_ORDER = ["User", "Role", "Permission", "Page"]

ENTITY_PATHS = {
    "User": "api/users",
    "Role": "api/roles",
    "Permission": "api/permissions",
    "Page": "api/pages",
}

# Per-entity cleanup strategy, discovered from index.md's API Catalog:
#   hard_delete     -> a real DELETE /{id} endpoint exists
#   soft_deactivate -> only a .../deactivate endpoint exists (no DELETE)
#   none            -> neither exists; records cannot be removed via the API
ENTITY_CLEANUP_STRATEGY = {
    "User": "hard_delete",        # DELETE /api/users/{userId} (delete.md)
    "Role": "hard_delete",        # DELETE /api/roles/{roleId} (deleteRole.md)
    "Permission": "none",         # no delete/deactivate endpoint in the catalog at all
    "Page": "soft_deactivate",    # only PUT /api/pages/{id}/deactivate (deactivatePage.md)
}


def cleanup(client: APIClient, token: Optional[str], created_ids: dict[str, list[int]]) -> None:
    """
    Best-effort teardown, always executed (via try/finally in main()) even if
    a test raised partway through.
    """
    print("\n[Cleanup]")
    hard_deleted = 0
    soft_deactivated = 0
    no_cleanup_path = 0

    for entity in ENTITY_TEARDOWN_ORDER:
        ids = created_ids.get(entity, [])
        path = ENTITY_PATHS.get(entity)
        strategy = ENTITY_CLEANUP_STRATEGY.get(entity, "none")
        for _id in ids:
            if _id is None or path is None:
                continue
            if strategy == "hard_delete":
                r = client.delete(f"{path}/{_id}", token=token, expected=[200, 204, 404, 409])
                if r.status_code in (200, 204):
                    hard_deleted += 1
                    print(f"  ✓ Deleted {entity} #{_id}")
                else:
                    print(f"  ⚠ Could not delete {entity} #{_id} (status {r.status_code}) — may remain, possibly still blocked by a business rule")
            elif strategy == "soft_deactivate":
                r = client.put(f"{path}/{_id}/deactivate", token=token, expected=[200, 404, 409])
                if r.status_code == 200:
                    soft_deactivated += 1
                    print(f"  ✓ Deactivated {entity} #{_id} (no hard-delete endpoint documented)")
                else:
                    print(f"  ⚠ Could not deactivate {entity} #{_id} (status {r.status_code}) — may remain active")
            else:  # "none"
                no_cleanup_path += 1
                print(f"  ⚠ {entity} #{_id} has NO delete or deactivate endpoint in the API catalog — record will persist permanently")

    if soft_deactivated:
        print(f"  ⚠ {soft_deactivated} record(s) remain in the database (soft-deactivated) — no hard-delete endpoint documented for that entity.")
    if hard_deleted:
        print(f"  ✓ {hard_deleted} record(s) permanently removed.")
    if no_cleanup_path:
        print(f"  ⚠ {no_cleanup_path} record(s) (Permission) have no cleanup path at all via the documented API — this is a real, permanent side effect of running this script, not a bug in it.")


# ─── Problems Report (Stage G — filtered, failures-only) ─────────────────────

def classify_and_collect_problems(suites: list[TestSuite]) -> list[ProblemEntry]:
    """
    🔴 Likely Real Bugs: a call that should have been rejected succeeded
        instead, or failed with a status not explained by any documented
        rule. Ambiguous cases default here (visible/flagged), never to
        "benign" by default.
    🟡 Test Assumption Mismatches: backend correctly rejected, but with a
        different status than the documented rule stated for it (e.g. the
        error.code sanity-check prints above surfaced a mismatch) — the
        expected_statuses list itself was already satisfied, so these are
        only distinguishable from the error.code warnings printed inline
        during the run; this report focuses on outright status failures.
    ⚪ Infrastructure: connection/timeout failures.
    """
    problems: list[ProblemEntry] = []
    for suite in suites:
        for r in suite.results:
            if r.passed:
                continue
            if r.error and ("Connection refused" in r.error or "timeout" in r.error.lower()):
                problems.append(ProblemEntry("infrastructure", f"[{suite.name}] {r.name}",
                    f"{r.error}", r))
            else:
                # Any pass/fail failure not explained as infrastructure defaults
                # to "Likely Real Bug" per the mandatory ambiguous-case rule —
                # never silently reclassified as benign.
                problems.append(ProblemEntry("real_bug", f"[{suite.name}] {r.name}",
                    f"Expected status in {r.expected_statuses}, got {r.status_code}", r))
    return problems


def generate_problems_report(problems: list[ProblemEntry], output_path: str) -> None:
    real_bugs = [p for p in problems if p.bucket == "real_bug"]
    mismatches = [p for p in problems if p.bucket == "assumption_mismatch"]
    infra = [p for p in problems if p.bucket == "infrastructure"]

    lines = ["# SECURITY Module — Problems Report", "",
             f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", "",
             "Only failures are listed here — see the HTML report for the full pass/fail detail.", ""]

    lines.append(f"## 🔴 Likely Real Bugs ({len(real_bugs)})")
    lines.append("")
    if real_bugs:
        for p in real_bugs:
            lines.append(f"- **{p.name}** — {p.detail}")
            if p.result.response_body:
                short = p.result.response_body[:300]
                lines.append(f"  ```\n  {short}\n  ```")
    else:
        lines.append("None.")
    lines.append("")

    lines.append(f"## 🟡 Test Assumption Mismatches ({len(mismatches)})")
    lines.append("")
    lines.append("None auto-classified into this bucket this run — see the console/error.code "
                  "warnings printed during Stage C tests above for any status/code mismatches "
                  "against registry-security.md's documented mapping; those did not fail their "
                  "`expected` status check but may still need the test's assumption corrected.")
    lines.append("")

    lines.append(f"## ⚪ Infrastructure ({len(infra)})")
    lines.append("")
    if infra:
        for p in infra:
            lines.append(f"- **{p.name}** — {p.detail}")
    else:
        lines.append("None.")
    lines.append("")

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"📄 Problems report written to: {output_path}")


# ─── HTML Report ────────────────────────────────────────────────────────────

def generate_html_report(suites: list[TestSuite], observations: list, output_path: str,
                          duration: float, base_url: str) -> None:
    total_pass = sum(s.passed for s in suites)
    total_fail = sum(s.failed for s in suites)
    total_all = sum(s.total for s in suites)
    pass_pct = round(total_pass / total_all * 100, 1) if total_all else 0

    suite_rows = ""
    for suite in suites:
        pct = round(suite.passed / suite.total * 100, 1) if suite.total else 0
        suite_rows += f"""
        <tr>
          <td>{suite.name}</td>
          <td class="num">{suite.total}</td>
          <td class="num pass">{suite.passed}</td>
          <td class="num fail">{suite.failed}</td>
          <td class="num">{pct}%</td>
        </tr>"""

    detail_sections = ""
    for suite in suites:
        rows = ""
        for r in suite.results:
            status_class = "pass" if r.passed else "fail"
            code = r.status_code or "ERR"
            expected = ", ".join(str(s) for s in r.expected_statuses)
            note_html = f'<span class="note">{r.note}</span>' if r.note else ""
            error_html = f'<div class="error-msg">{r.error}</div>' if r.error else ""
            body_html = ""
            if r.response_body:
                short = r.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(r.response_body) > 300 else ""}</pre></details>'
            rows += f"""
            <tr class="{status_class}">
              <td><span class="badge {status_class}">{r.status_label}</span></td>
              <td><span class="method {r.method.lower()}">{r.method}</span></td>
              <td class="test-name">{r.name} {note_html}</td>
              <td class="url">{r.url}</td>
              <td class="num">{code}</td>
              <td class="num">{expected}</td>
              <td class="num">{r.duration_ms:.0f}ms</td>
              <td>{error_html}{body_html}</td>
            </tr>"""
        detail_sections += f"""
        <section>
          <h2>{suite.name} — {suite.passed}/{suite.total} passed</h2>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Test</th><th>URL</th>
              <th>Got</th><th>Expected</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </section>"""

    observation_section = ""
    if observations:
        obs_rows = ""
        for o in observations:
            code = o.status_code or "ERR"
            body_html = ""
            if o.response_body:
                short = o.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(o.response_body) > 300 else ""}</pre></details>'
            obs_rows += f"""
            <tr>
              <td><span class="badge observed">OBSERVED</span></td>
              <td><span class="method {o.method.lower()}">{o.method}</span></td>
              <td class="test-name">{o.name}</td>
              <td class="url">{o.url}</td>
              <td class="num">{code}</td>
              <td class="url">{o.source}</td>
              <td class="num">{o.duration_ms:.0f}ms</td>
              <td>{body_html}</td>
            </tr>"""
        observation_section = f"""
        <section>
          <h2>⚠️ Exploratory Observations — undocumented expected outcomes, not pass/fail</h2>
          <p style="padding:0 20px;color:#666;font-size:.85rem">
            These scenarios test documented constraints (Required/maxLength/minLength/type) but
            the API's expected response for violating them isn't specified in any governance
            document. Review the observed status/body against your intended behavior — do not
            treat these as failures of the implementation.
          </p>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Scenario</th><th>URL</th>
              <th>Observed</th><th>Source (doc/field)</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{obs_rows}</tbody>
          </table>
        </section>"""

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" />
<title>SECURITY Module API Test Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
<style>
  *,*::before,*::after{{box-sizing:border-box}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;margin:0;padding:20px;background:#f4f6f9;color:#1a1a2e}}
  h1{{margin-bottom:4px}} .meta{{color:#666;font-size:.9rem;margin-bottom:24px}}
  .summary{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:28px}}
  .card{{background:#fff;border-radius:10px;padding:18px 24px;box-shadow:0 2px 6px rgba(0,0,0,.08);min-width:140px;text-align:center}}
  .card .num{{font-size:2.2rem;font-weight:700;line-height:1}} .card .label{{font-size:.8rem;color:#888;margin-top:4px}}
  .card.total .num{{color:#3a86ff}} .card.pass .num{{color:#2ec4b6}} .card.fail .num{{color:#e63946}}
  .suite-table{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  table{{width:100%;border-collapse:collapse;font-size:.875rem}}
  th{{background:#f0f2f5;text-align:left;padding:10px 14px;font-weight:600;color:#555}}
  td{{padding:8px 14px;border-top:1px solid #eef0f3;vertical-align:top}}
  tr.pass td{{background:#f6fff8}} tr.fail td{{background:#fff5f5}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:10px;font-size:.75rem;font-weight:700}}
  .badge.pass{{background:#d4f7ef;color:#1a7a6f}} .badge.fail{{background:#fde8e8;color:#b91c1c}}
  .badge.observed{{background:#fff3cd;color:#8a6314}}
  .method{{display:inline-block;padding:2px 6px;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff}}
  .method.get{{background:#3a86ff}} .method.post{{background:#2ec4b6}} .method.put{{background:#f4a261}} .method.delete{{background:#e63946}}
  .num{{text-align:center}} .url{{font-size:.75rem;color:#666;word-break:break-all;max-width:260px}}
  .test-name{{font-weight:500}} .note{{font-size:.72rem;color:#999;margin-left:6px}}
  .error-msg{{color:#b91c1c;font-size:.8rem}}
  details summary{{cursor:pointer;color:#3a86ff;font-size:.78rem;margin-top:4px}}
  pre{{background:#f8f8f8;padding:8px;border-radius:4px;font-size:.72rem;overflow-x:auto;max-width:400px;white-space:pre-wrap}}
  section{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  section h2{{padding:14px 20px;margin:0;background:#f0f2f5;font-size:1rem;border-bottom:1px solid #e0e4ea}}
</style></head>
<body>
  <h1>SECURITY Module API Test Report</h1>
  <p class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;·&nbsp;
     Base URL: {base_url} &nbsp;·&nbsp; Duration: {duration:.1f}s &nbsp;·&nbsp;
     Run ID: {RUN_ID}</p>
  <div class="summary">
    <div class="card total"><div class="num">{total_all}</div><div class="label">Total</div></div>
    <div class="card pass"><div class="num">{total_pass}</div><div class="label">Passed</div></div>
    <div class="card fail"><div class="num">{total_fail}</div><div class="label">Failed</div></div>
    <div class="card total"><div class="num">{pass_pct}%</div><div class="label">Pass Rate</div></div>
  </div>
  <div class="suite-table"><table><thead><tr><th>Suite</th><th>Total</th><th>Pass</th><th>Fail</th><th>Rate</th></tr></thead>
  <tbody>{suite_rows}</tbody></table></div>
  {detail_sections}
  {observation_section}
</body></html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"\n📄 HTML report written to: {output_path}")


# ─── Entry point ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="SECURITY module API test suite")
    parser.add_argument("--base-url", default=BASE_URL, help="Base API URL")
    parser.add_argument("--report", default="security_api_test_report.html", help="Output HTML file")
    parser.add_argument("--problems-report", default="security_problems_report.md", help="Output problems Markdown file")
    args = parser.parse_args()

    client = APIClient(args.base_url)
    start_time = time.perf_counter()

    print("=" * 60)
    print("  SECURITY Module API Test Suite")
    print(f"  Base URL: {args.base_url}")
    print(f"  Run ID:   {RUN_ID}")
    print("=" * 60)

    auth_suite, token = test_auth(client)
    admin_user_id = None  # not resolved from login response (login only returns tokens, not userId);
                          # loginWithToken's UserInfo.userId would resolve it, kept simple here.

    observations: list = []
    created_ids: dict[str, list[int]] = {"Page": [], "Permission": [], "Role": [], "User": []}

    menu_suite = TestSuite("Menu")
    page_suite = TestSuite("Page")
    permission_suite = TestSuite("Permission")
    role_suite = TestSuite("Role")
    user_suite = TestSuite("User")

    try:
        # Stage B dependency order: Page (root) -> Permission (optional FK
        # -> Page) -> Role (uses Page's pageCode for page-assignment
        # endpoints) -> User (uses Role's roleName for assignRoles).
        menu_suite = test_menu(client, token, admin_user_id)
        page_suite, page_ids = test_page(client, token, observations, created_ids)
        permission_suite, _perm_ids = test_permission(client, token, page_ids.get("id"), observations, created_ids)
        role_suite, role_ids = test_role(client, token, page_ids.get("pageCode"), observations, created_ids)
        user_suite, _user_ids = test_user(client, token, role_ids.get("roleName"), observations, created_ids)
    finally:
        # Always runs, even if a test above raised partway through.
        cleanup(client, token, created_ids)

    duration = time.perf_counter() - start_time
    suites = [auth_suite, menu_suite, page_suite, permission_suite, role_suite, user_suite]

    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    total_pass = sum(s.passed for s in suites)
    total_all = sum(s.total for s in suites)
    for s in suites:
        bar = "█" * s.passed + "░" * s.failed
        print(f"  {s.name:<20} {s.passed:>3}/{s.total:<3}  {bar}")
    print(f"\n  Total: {total_pass}/{total_all} passed  ({duration:.1f}s)")
    if observations:
        print(f"  Exploratory observations: {len(observations)} (see HTML report — not pass/fail)")

    generate_html_report(suites, observations, args.report, duration, args.base_url)
    problems = classify_and_collect_problems(suites)
    generate_problems_report(problems, args.problems_report)

    sys.exit(0 if total_pass == total_all else 1)


if __name__ == "__main__":
    main()
