#!/usr/bin/env python3
"""
Security module API test suite — generated by MODE 5 (Project 5).

Covers 49 endpoints across 8 API Catalog groups (index.md):
  Authentication, Menu Management, Page Management, Permission Management,
  Role Access Control, Security DataScope - Role Branches,
  Security DataScope - User Profiles, User Management.

⚠ GOVERNANCE OVERRIDE NOTICE (read before running)
────────────────────────────────────────────────────────────────────────────
execution-plan-SEC-gaps.md (PLAN-SEC-002) states MODE 3 (agent code
execution against the Security module) is BLOCKED pending Conflict #19
architecture-authority sign-off, for exactly the 12 new SEC-002 APIs
covered by test_user_profiles(), test_role_branches(), and
test_self_service_auth() below (signup/activate/forgot-password/
reset-password, user-profiles CRUD, role-branches CRUD).

The user explicitly instructed this script be generated for ALL 49
endpoints anyway, taking responsibility for overriding that gate. This
script does NOT resolve Conflict #19 and does NOT imply architecture
sign-off occurred — running it against a real environment is a decision
made outside this engine's scope. Traceability comments on the affected
test functions repeat this notice.
────────────────────────────────────────────────────────────────────────────

Prerequisite: admin login must hold every permission exercised below
(PAGE_CREATE/UPDATE/VIEW, ROLE_CREATE/UPDATE/VIEW/DELETE, PERMISSION_VIEW,
USER_MANAGE_ROLES) — without them the relevant calls return 403 regardless
of whether the underlying API works. The Security DataScope endpoints
(user-profiles, role-branches) are NOT permission-gated per
security-registry.md §2.8 — any authenticated user can call them today;
this is a documented, not invented, quirk.

Known out-of-module dependency: SEC_USER_PROFILE.branchIdFk and
SEC_ROLE_BRANCH.branchIdFk are HARD-FKs to ORG_BRANCH (Organization
module), which has no CRUD endpoints anywhere in this module's API
Catalog. ASSUMED_EXISTING_BRANCH_ID below is a placeholder for a branch
that must already exist in the target environment — it is NOT invented
business data, it documents an external dependency this script cannot
self-provision. If branch 1 doesn't exist / isn't active in your
environment, the profile/role-branch Create happy-paths will fail with
SEC_USER_PROFILE_BRANCH_INACTIVE — adjust the constant below.

Usage:
    python3 test_security_apis.py
    python3 test_security_apis.py --base-url http://localhost:7272
    python3 test_security_apis.py --report security_api_test_report.html
"""

import argparse
import json
import string
import sys
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("requests library not found. Install it: pip install requests")
    sys.exit(1)


# ─── Configuration (placeholders — never invent real credentials) ─────────────

BASE_URL = "http://localhost:7272"
TIMEOUT = 15  # seconds

ADMIN_USERNAME = "admin"  # CHANGE ME
ADMIN_PASSWORD = "admin"  # CHANGE ME

# External dependency placeholder (Organization module, out of this module's
# scope — see governance override notice above). Not invented business data.
ASSUMED_EXISTING_BRANCH_ID = 1

# Intended for Dev/Test environments only.


# ─── Data classes (fixed pattern — see generic-boilerplate-reference.py) ──────

@dataclass
class TestResult:
    name: str
    method: str
    url: str
    status_code: Optional[int]
    passed: bool
    expected_statuses: list
    duration_ms: float
    error: Optional[str] = None
    response_body: Optional[str] = None
    note: Optional[str] = None

    @property
    def status_label(self) -> str:
        return "PASS" if self.passed else "FAIL"


@dataclass
class TestSuite:
    name: str
    results: list = field(default_factory=list)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed(self) -> int:
        return len(self.results) - self.passed

    @property
    def total(self) -> int:
        return len(self.results)


@dataclass
class Observation:
    """
    Stage E exploratory scenario with an UNDOCUMENTED expected outcome. Never
    counted as pass/fail — records actual behavior for human review only.
    """
    name: str
    method: str
    url: str
    status_code: Optional[int]
    duration_ms: float
    source: str
    response_body: Optional[str] = None


@dataclass
class ProblemEntry:
    bucket: str  # "bug" | "assumption" | "infra"
    name: str
    detail: str


# ─── HTTP helper (fixed) ───────────────────────────────────────────────────────

class APIClient:
    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "Content-Type": "application/json",
        })

    def _make(self, method: str, path: str, token: Optional[str] = None,
              expected: Optional[list] = None, **kwargs) -> TestResult:
        url = f"{self.base_url}/{path.lstrip('/')}"
        headers = kwargs.pop("headers", {})
        if token:
            headers["Authorization"] = f"Bearer {token}"
        if expected is None:
            expected = [200]

        start = time.perf_counter()
        try:
            resp = self.session.request(method.upper(), url, headers=headers, timeout=TIMEOUT, **kwargs)
            duration = (time.perf_counter() - start) * 1000
            try:
                body = json.dumps(resp.json(), indent=2, ensure_ascii=False)
            except Exception:
                body = resp.text[:500]
            return TestResult(
                name="", method=method.upper(), url=url, status_code=resp.status_code,
                passed=resp.status_code in expected, expected_statuses=expected,
                duration_ms=round(duration, 1), response_body=body,
            )
        except requests.exceptions.ConnectionError:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1),
                error="Connection refused — is the server running?",
            )
        except Exception as exc:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1), error=str(exc),
            )

    def get(self, path, token=None, expected=None, **kw):
        return self._make("GET", path, token, expected, **kw)

    def post(self, path, token=None, expected=None, **kw):
        return self._make("POST", path, token, expected, **kw)

    def put(self, path, token=None, expected=None, **kw):
        return self._make("PUT", path, token, expected, **kw)

    def delete(self, path, token=None, expected=None, **kw):
        return self._make("DELETE", path, token, expected, **kw)


# ─── Test runner helpers (fixed) ───────────────────────────────────────────────

def run(suite: TestSuite, name: str, result: TestResult, note: str = "") -> TestResult:
    result.name = name
    result.note = note
    suite.results.append(result)
    status = "✓" if result.passed else "✗"
    code = result.status_code or "ERR"
    print(f"  {status} [{code}] {name} ({result.duration_ms:.0f}ms)")
    if not result.passed and result.error:
        print(f"      Error: {result.error}")
    return result


def run_observation(bucket: list, name: str, source: str, result: TestResult) -> None:
    obs = Observation(
        name=name, method=result.method, url=result.url, status_code=result.status_code,
        duration_ms=result.duration_ms, source=source, response_body=result.response_body,
    )
    bucket.append(obs)
    code = result.status_code or "ERR"
    print(f"  👁 [{code}] {name} — observed (source: {source})")


def data_of(result: TestResult):
    """
    Envelope shape {success, message, data, error, timestamp, correlationId}
    confirmed against index.md's Common Response Envelope (ApiResponseSecUserProfileDto).
    """
    if not result.response_body:
        return None
    try:
        return json.loads(result.response_body).get("data")
    except Exception:
        return None


def error_code_of(result: TestResult) -> Optional[str]:
    """error.code, per index.md Common Response Envelope."""
    if not result.response_body:
        return None
    try:
        body = json.loads(result.response_body)
        err = body.get("error")
        return err.get("code") if isinstance(err, dict) else None
    except Exception:
        return None


def extract_token(result: TestResult) -> Optional[str]:
    # login.md's AuthResponse / loginWithToken.md's UserInfo both put
    # accessToken directly in `data` (confirmed shape per each doc's own
    # Response section) — not nested further.
    d = data_of(result)
    return d.get("accessToken") if isinstance(d, dict) else None


def extract_field(result: TestResult, field_name: str):
    d = data_of(result)
    return d.get(field_name) if isinstance(d, dict) else None


def extract_page_first_id(result: TestResult) -> Optional[int]:
    """
    Pagination envelope per index.md: totalElements, totalPages,
    numberOfElements, first, last, pageable, size, number (NOT "page"),
    sort, empty. `content` is not listed in index.md's Pagination Envelope
    table for this module either — treated as a documentation gap, not
    proof it's absent from the real response (per Section 4A guidance).
    Flagged here rather than asserted on silently.
    """
    d = data_of(result)
    if isinstance(d, dict):
        content = d.get("content")  # unconfirmed — verify against real response
        if isinstance(content, list) and content:
            return content[0].get("id")
    return None


def rand_suffix() -> str:
    return uuid.uuid4().hex[:8]


# ─── Auth (fixed pattern) ──────────────────────────────────────────────────────

def test_auth(client: APIClient) -> tuple:
    # Covers: API from "Authentication" catalog group — login
    suite = TestSuite("Auth")
    print("\n[Auth]")
    r = run(suite, "Admin Login", client.post(
        "api/auth/login", expected=[200],
        json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
    ))
    token = extract_token(r)

    # Happy-path coverage of the other pre-existing auth endpoints that
    # don't fit the entity CRUD shape (loginWithToken, refresh — session
    # lifecycle). logout is exercised last in main() since it invalidates
    # the token every other suite depends on.
    run(suite, "Login With Token (full UserInfo)", client.post(
        "api/auth/login-token", token=token, expected=[200],
        json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
    ))
    run(suite, "Refresh Access Token", client.post("api/auth/refresh", token=token, expected=[200]))

    # Negative: malformed JSON body -> INVALID_JSON per every @RequestBody
    # endpoint's documented "Other Possible Responses" (structural, not a
    # business RULE-ID, but explicitly documented in login.md).
    r_bad = client._make("POST", "api/auth/login", token=None, expected=[400],
                          data="{not valid json", headers={"Content-Type": "application/json"})
    run(suite, "Login — malformed JSON body (structural, login.md)", r_bad)

    return suite, token


# ─── Page Management — root entity, no FK dependency ──────────────────────────
# Covers: createPage, getPageById, updatePage, deactivatePage, reactivatePage,
#         searchPages, getActivePages

def test_pages(client: APIClient, token: Optional[str], observations: list,
               created_ids: dict) -> tuple:
    suite = TestSuite("Page Management")
    ids = {}
    print("\n[Page Management]")

    page_code = f"TP{rand_suffix()[:6]}".upper()
    r = run(suite, "Create Page", client.post(
        "api/pages", token=token, expected=[200, 201],
        json={"pageCode": page_code, "nameAr": "صفحة تجريبية", "nameEn": "Test Page",
              "route": f"/test/{page_code.lower()}", "module": "SECURITY", "displayOrder": 999},
    ))
    page_id = extract_field(r, "id")
    ids["id"] = page_id
    ids["pageCode"] = extract_field(r, "pageCode") or page_code
    if page_id:
        created_ids.setdefault("Page", []).append(page_id)

    if page_id:
        run(suite, "Get Page by ID", client.get(f"api/pages/{page_id}", token=token, expected=[200]))
    run(suite, "Get Page by ID — Not Found", client.get("api/pages/999999999", token=token, expected=[404]))

    if page_id:
        run(suite, "Update Page", client.put(
            f"api/pages/{page_id}", token=token, expected=[200],
            json={"nameAr": "صفحة محدثة", "nameEn": "Updated Test Page", "route": f"/test/{page_code.lower()}"},
        ))

    run(suite, "Search Pages", client.post(
        "api/pages/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))
    run(suite, "Get Active Pages", client.get("api/pages/active", token=token, expected=[200]))

    if page_id:
        run(suite, "Deactivate Page", client.put(f"api/pages/{page_id}/deactivate", token=token, expected=[200]))
        run(suite, "Reactivate Page", client.put(f"api/pages/{page_id}/reactivate", token=token, expected=[200]))

    # Stage E — exploratory (bounded to Required=Yes / stated maxLength fields)
    # Source: pageCode field, doc states maxLength: 50 (Required=Yes)
    over_code = ("X" * 51)
    r_over = client.post("api/pages", token=token, expected=[200, 201, 400],
                          json={"pageCode": over_code, "nameAr": "x", "nameEn": "x", "route": "/x/over"})
    if (oid := extract_field(r_over, "id")):
        created_ids.setdefault("Page", []).append(oid)
    run_observation(observations, "Create Page — pageCode over maxLength (51 chars)",
                     source="createPage.md pageCode Constraints: maxLength=50", result=r_over)

    # Source: nameEn field, Required=Yes — omission test
    r_omit = client.post("api/pages", token=token, expected=[200, 201, 400],
                          json={"pageCode": f"OM{rand_suffix()[:6]}".upper(), "nameAr": "x", "route": "/x/omit"})
    if (mid := extract_field(r_omit, "id")):
        created_ids.setdefault("Page", []).append(mid)
    run_observation(observations, "Create Page — omit required nameEn",
                     source="createPage.md nameEn Required=Yes", result=r_omit)

    return suite, ids


# ─── Permission Management — depends on Page (pageId is optional FK) ──────────
# Covers: create_3, update_3, searchPermissions

def test_permissions(client: APIClient, token: Optional[str], page_id: Optional[int],
                      observations: list, created_ids: dict) -> tuple:
    suite = TestSuite("Permission Management")
    ids = {}
    print("\n[Permission Management]")

    r = run(suite, "Create Permission", client.post(
        "api/permissions", token=token, expected=[200, 201],
        json={"name": f"PERM_TEST_{rand_suffix()}", "pageId": page_id, "permissionType": "VIEW"},
    ))
    perm_id = extract_field(r, "id")
    ids["id"] = perm_id
    if perm_id:
        created_ids.setdefault("Permission", []).append(perm_id)

    if perm_id:
        run(suite, "Update Permission", client.put(
            f"api/permissions/{perm_id}", token=token, expected=[200],
            json={"name": f"PERM_TEST_UPDATED_{rand_suffix()}"},
        ))

    run(suite, "Search Permissions", client.post(
        "api/permissions/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # Stage E — Source: name field, Required=Yes — omission test
    r_omit = client.post("api/permissions", token=token, expected=[200, 201, 400],
                          json={"permissionType": "VIEW"})
    if (mid := extract_field(r_omit, "id")):
        created_ids.setdefault("Permission", []).append(mid)
    run_observation(observations, "Create Permission — omit required name",
                     source="create_3.md name Required=Yes", result=r_omit)

    # NOTE (Stage F gap, flagged not silently omitted): Permission Management
    # has no DELETE or deactivate endpoint anywhere in the API Catalog —
    # created permissions cannot be cleaned up via this API. See cleanup().
    return suite, ids


# ─── Role Access Control — root entity, no FK dependency ──────────────────────
# Covers: createRole, getRoleById, updateRole, deleteRole, toggleRoleActive,
#         searchRoles, getRolePages, syncRolePages, addPageToRole,
#         removePageFromRole, copyFromRole

def test_roles(client: APIClient, token: Optional[str], page_code: Optional[str],
               observations: list, created_ids: dict) -> tuple:
    suite = TestSuite("Role Access Control")
    ids = {}
    print("\n[Role Access Control]")

    role_code = f"TESTROLE_{rand_suffix()}".upper()
    r = run(suite, "Create Role", client.post(
        "api/roles", token=token, expected=[200, 201],
        json={"roleCode": role_code, "roleName": "Test Role", "description": "Generated by test script", "active": True},
    ))
    role_id = extract_field(r, "id")
    ids["id"] = role_id
    if role_id:
        created_ids.setdefault("Role", []).append(role_id)

    # Second role, purely to exercise copyFromRole (source role)
    role_code_2 = f"TESTROLE2_{rand_suffix()}".upper()
    r2 = run(suite, "Create Role (source, for copyFromRole)", client.post(
        "api/roles", token=token, expected=[200, 201],
        json={"roleCode": role_code_2, "roleName": "Test Source Role", "active": True},
    ))
    role_id_2 = extract_field(r2, "id")
    ids["source_id"] = role_id_2
    if role_id_2:
        created_ids.setdefault("Role", []).append(role_id_2)

    if role_id:
        run(suite, "Get Role by ID", client.get(f"api/roles/{role_id}", token=token, expected=[200]))
    run(suite, "Get Role by ID — Not Found", client.get("api/roles/999999999", token=token, expected=[404]))

    if role_id:
        run(suite, "Update Role", client.put(
            f"api/roles/{role_id}", token=token, expected=[200],
            json={"roleName": "Test Role Updated", "active": True},
        ))
        run(suite, "Toggle Role Active (deactivate)", client.put(
            f"api/roles/{role_id}/toggle-active", token=token, expected=[200], json={"active": False},
        ))
        run(suite, "Toggle Role Active (reactivate)", client.put(
            f"api/roles/{role_id}/toggle-active", token=token, expected=[200], json={"active": True},
        ))

    run(suite, "Search Roles", client.post(
        "api/roles/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    if role_id and page_code:
        run(suite, "Add Page to Role", client.post(
            f"api/roles/{role_id}/pages", token=token, expected=[200, 201],
            json={"pageCode": page_code, "permissions": ["CREATE", "UPDATE"]},
        ))
        run(suite, "Get Role Pages Matrix", client.get(f"api/roles/{role_id}/pages", token=token, expected=[200]))
        run(suite, "Bulk Sync Role Pages", client.put(
            f"api/roles/{role_id}/pages", token=token, expected=[200],
            json={"assignments": [{"pageCode": page_code, "permissions": ["CREATE", "UPDATE", "DELETE"]}]},
        ))
        if role_id_2:
            # copy-from requires the source role to actually have page permissions
            # (empty source -> documented 409 NO_PERMISSIONS_TO_COPY, not a copy bug) —
            # give role_id_2 a page assignment first so the copy has something to do.
            # NOTE: VIEW is NOT a valid value here — RoleAccessService.addPageToRole only
            # accepts CREATE/UPDATE/DELETE; VIEW is auto-granted on every page assignment
            # and deliberately rejected if requested explicitly (see CANNOT_REMOVE_VIEW_PERMISSION
            # / INVALID_PERMISSION_TYPE in messages.properties).
            run(suite, "Add Page to Role (source, for copyFromRole)", client.post(
                f"api/roles/{role_id_2}/pages", token=token, expected=[200, 201],
                json={"pageCode": page_code, "permissions": ["CREATE"]},
            ))
            run(suite, "Copy Permissions From Role", client.post(
                f"api/roles/{role_id}/copy-from/{role_id_2}", token=token, expected=[200],
            ))
        run(suite, "Remove Page From Role", client.delete(
            f"api/roles/{role_id}/pages/{page_code}", token=token, expected=[204, 200, 404],
        ))

    # Stage E — Source: roleCode field, pattern ^[A-Z][A-Z0-9_]*$ (Required=Yes)
    r_pattern = client.post("api/roles", token=token, expected=[200, 201, 400],
                             json={"roleCode": f"lowercase_{rand_suffix()}", "roleName": "Bad Pattern Role"})
    if (pid := extract_field(r_pattern, "id")):
        created_ids.setdefault("Role", []).append(pid)
    run_observation(observations, "Create Role — roleCode violates pattern (lowercase)",
                     source="createRole.md roleCode Constraints: pattern=^[A-Z][A-Z0-9_]*$", result=r_pattern)

    # Source: roleName field, Required=Yes — omission test
    r_omit = client.post("api/roles", token=token, expected=[200, 201, 400],
                          json={"roleCode": f"NONAME_{rand_suffix()}".upper()})
    if (oid := extract_field(r_omit, "id")):
        created_ids.setdefault("Role", []).append(oid)
    run_observation(observations, "Create Role — omit required roleName",
                     source="createRole.md roleName Required=Yes", result=r_omit)

    return suite, ids


# ─── User Management — root entity, no FK dependency ──────────────────────────
# Covers: create_2, all, search_2, update_2, delete_1, getUserRoles, assignRoles

def test_users(client: APIClient, token: Optional[str], role_code: Optional[str],
                observations: list, created_ids: dict) -> tuple:
    suite = TestSuite("User Management")
    ids = {}
    print("\n[User Management]")

    username = f"testuser_{rand_suffix()}"
    r = run(suite, "Create User", client.post(
        "api/users", token=token, expected=[200, 201],
        json={"username": username, "password": "TestPass123"},
    ))
    user_id = extract_field(r, "id")
    ids["id"] = user_id
    ids["username"] = username
    if user_id:
        created_ids.setdefault("User", []).append(user_id)

    run(suite, "List All Users", client.get("api/users?page=0&size=20", token=token, expected=[200]))
    run(suite, "Search Users", client.post(
        "api/users/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    if user_id:
        run(suite, "Update User", client.put(
            f"api/users/{user_id}", token=token, expected=[200], json={"enabled": True},
        ))
        run(suite, "Get User Roles", client.get(f"api/users/{user_id}/roles", token=token, expected=[200]))
        if role_code:
            run(suite, "Assign Roles to User", client.put(
                f"api/users/{user_id}/roles", token=token, expected=[200],
                json={"roleNames": [role_code]},
            ))

    # Stage E — Source: username field, maxLength:80 / minLength:3 (Required=Yes)
    r_short = client.post("api/users", token=token, expected=[200, 201, 400],
                           json={"username": "ab", "password": "TestPass123"})
    if (sid := extract_field(r_short, "id")):
        created_ids.setdefault("User", []).append(sid)
    run_observation(observations, "Create User — username under minLength (2 chars)",
                     source="create_2.md username Constraints: minLength=3", result=r_short)

    # Source: password field, minLength:6 (Required=Yes)
    r_short_pw = client.post("api/users", token=token, expected=[200, 201, 400],
                              json={"username": f"testuser_{rand_suffix()}", "password": "abc"})
    if (pid := extract_field(r_short_pw, "id")):
        created_ids.setdefault("User", []).append(pid)
    run_observation(observations, "Create User — password under minLength (3 chars)",
                     source="create_2.md password Constraints: minLength=6", result=r_short_pw)

    return suite, ids


# ─── Menu Management — read-only, depends on User for getUserMenuById ─────────
# Covers: getUserMenu, getUserMenuById

def test_menu(client: APIClient, token: Optional[str], user_id: Optional[int]) -> TestSuite:
    suite = TestSuite("Menu Management")
    print("\n[Menu Management]")
    run(suite, "Get Current User Menu", client.get("api/menu/user-menu", token=token, expected=[200]))
    if user_id:
        run(suite, "Get Menu For Specific User (Admin)", client.get(
            f"api/menu/user-menu/{user_id}", token=token, expected=[200],
        ))
    return suite


# ─── Security DataScope — User Profiles ────────────────────────────────────────
# Covers: create, getById, update, list, search (user-profiles)
# ⚠ Part of SEC-002 gap package — Conflict #19 override in effect, see header.
# Negative: RULE-SEC-034 / SEC_USER_PROFILE_BRANCH_INACTIVE (security-registry.md §2.8, confirmed runtime code)
# No DELETE endpoint per security-registry.md §2.8 — cleanup gap, flagged not silently skipped.

def test_user_profiles(client: APIClient, token: Optional[str], user_id: Optional[int],
                        observations: list, created_ids: dict, problems: list) -> TestSuite:
    suite = TestSuite("Security DataScope - User Profiles")
    print("\n[Security DataScope - User Profiles] (SEC-002 gap package — override in effect)")

    if not user_id:
        print("  ⚠ Skipped — no parent User ID available")
        return suite

    r = run(suite, "Create User Profile", client.post(
        "api/v1/security/user-profiles", token=token, expected=[200, 201],
        json={"userIdFk": user_id, "branchIdFk": ASSUMED_EXISTING_BRANCH_ID},
    ))
    # No hard-delete endpoint exists for this entity (confirmed absent in
    # security-registry.md §2.8) — track anyway so cleanup() can at least
    # report it as a leaked record rather than silently losing track.
    if r.passed:
        created_ids.setdefault("UserProfile", []).append(user_id)

    run(suite, "Get User Profile by ID", client.get(
        f"api/v1/security/user-profiles/{user_id}", token=token, expected=[200],
    ))
    run(suite, "Get User Profile by ID — Not Found", client.get(
        "api/v1/security/user-profiles/999999999", token=token, expected=[404],
    ))

    run(suite, "Update User Profile", client.put(
        f"api/v1/security/user-profiles/{user_id}", token=token, expected=[200],
        json={"branchIdFk": ASSUMED_EXISTING_BRANCH_ID, "fullNameEn": "Test User Updated"},
    ))

    run(suite, "List User Profiles", client.get(
        "api/v1/security/user-profiles?pageable=userIdFk,asc", token=token, expected=[200],
    ))
    run(suite, "Search User Profiles", client.post(
        "api/v1/security/user-profiles/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # Negative TC (RULE-SEC-034 / confirmed runtime code SEC_USER_PROFILE_BRANCH_INACTIVE,
    # security-registry.md §2.8) — non-existent branch does not resolve to an active branch.
    # Uses a FRESH user, not `user_id` above: reusing user_id would hit
    # SEC_USER_PROFILE_ALREADY_EXISTS (409) first since that profile now already exists,
    # masking the branch-validation path this test is actually meant to exercise.
    r_bad_branch_user = client.post(
        "api/users", token=token, expected=[200, 201],
        json={"username": f"testuser_{rand_suffix()}", "password": "TestPass123"},
    )
    bad_branch_user_id = extract_field(r_bad_branch_user, "id")
    if bad_branch_user_id:
        created_ids.setdefault("User", []).append(bad_branch_user_id)
    r_bad_branch = run(suite, "Create User Profile — nonexistent branchIdFk (RULE-SEC-034)", client.post(
        "api/v1/security/user-profiles", token=token, expected=[400],
        json={"userIdFk": bad_branch_user_id, "branchIdFk": 999999999},
    ))
    if r_bad_branch.passed:
        code = error_code_of(r_bad_branch)
        if code != "SEC_USER_PROFILE_BRANCH_INACTIVE":
            problems.append(ProblemEntry(
                "assumption", "Create User Profile — nonexistent branchIdFk",
                f"Expected error.code SEC_USER_PROFILE_BRANCH_INACTIVE (security-registry.md §2.8), got {code!r}",
            ))
    elif r_bad_branch.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Create User Profile — nonexistent branchIdFk",
            f"Expected 400 SEC_USER_PROFILE_BRANCH_INACTIVE per RULE-SEC-034, got status {r_bad_branch.status_code}",
        ))

    # Stage E — Source: fullNameEn field, maxLength:100
    over_name = "X" * 101
    r_over = client.put(f"api/v1/security/user-profiles/{user_id}", token=token, expected=[200, 400],
                         json={"branchIdFk": ASSUMED_EXISTING_BRANCH_ID, "fullNameEn": over_name})
    run_observation(observations, "Update User Profile — fullNameEn over maxLength (101 chars)",
                     source="update.md fullNameEn Constraints: maxLength=100", result=r_over)

    return suite


# ─── Security DataScope — Role Branches ────────────────────────────────────────
# Covers: create_1, getById_1, update_1, delete, list_1, search_1
# ⚠ Part of SEC-002 gap package — Conflict #19 override in effect, see header.
# Negative: RULE-SEC-035/036 (confirmed runtime codes, security-registry.md §2.8)

def test_role_branches(client: APIClient, token: Optional[str], role_id: Optional[int],
                        observations: list, created_ids: dict, problems: list) -> TestSuite:
    suite = TestSuite("Security DataScope - Role Branches")
    print("\n[Security DataScope - Role Branches] (SEC-002 gap package — override in effect)")

    if not role_id:
        print("  ⚠ Skipped — no parent Role ID available")
        return suite

    branch_id = ASSUMED_EXISTING_BRANCH_ID
    r = run(suite, "Assign Branch Scope to Role", client.post(
        "api/v1/security/role-branches", token=token, expected=[200, 201],
        json={"roleIdFk": role_id, "branchIdFk": branch_id, "dataAccessLevel": "BRANCH_ONLY"},
    ))
    if r.passed:
        created_ids.setdefault("RoleBranch", []).append((role_id, branch_id))

    run(suite, "Get Role-Branch Assignment", client.get(
        f"api/v1/security/role-branches/{role_id}/{branch_id}", token=token, expected=[200],
    ))
    run(suite, "Update Role-Branch Assignment", client.put(
        f"api/v1/security/role-branches/{role_id}/{branch_id}", token=token, expected=[200],
        json={"dataAccessLevel": "BRANCH_AND_CHILDREN"},
    ))
    run(suite, "List Role-Branch Assignments", client.get(
        "api/v1/security/role-branches?pageable=roleIdFk,asc", token=token, expected=[200],
    ))
    run(suite, "Search Role-Branch Assignments", client.post(
        "api/v1/security/role-branches/search", token=token, expected=[200],
        json={"filters": [], "sorts": [], "page": 0, "size": 20},
    ))

    # Negative TC (RULE-SEC-036 / confirmed runtime code SEC_ROLE_BRANCH_DUPLICATE_ASSIGNMENT)
    r_dup = run(suite, "Assign Branch Scope — duplicate (role,branch) (RULE-SEC-036)", client.post(
        "api/v1/security/role-branches", token=token, expected=[409],
        json={"roleIdFk": role_id, "branchIdFk": branch_id, "dataAccessLevel": "BRANCH_ONLY"},
    ))
    if r_dup.passed:
        code = error_code_of(r_dup)
        if code != "SEC_ROLE_BRANCH_DUPLICATE_ASSIGNMENT":
            problems.append(ProblemEntry(
                "assumption", "Assign Branch Scope — duplicate assignment",
                f"Expected error.code SEC_ROLE_BRANCH_DUPLICATE_ASSIGNMENT (security-registry.md §2.8), got {code!r}",
            ))
    elif r_dup.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Assign Branch Scope — duplicate assignment",
            f"Expected 409 SEC_ROLE_BRANCH_DUPLICATE_ASSIGNMENT per RULE-SEC-036, got status {r_dup.status_code}",
        ))

    # Negative TC (RULE-SEC-035 / confirmed runtime code SEC_ROLE_BRANCH_DATA_ACCESS_LEVEL_REQUIRED)
    r_no_lvl = run(suite, "Assign Branch Scope — omit required dataAccessLevel (RULE-SEC-035)", client.post(
        "api/v1/security/role-branches", token=token, expected=[400],
        json={"roleIdFk": role_id, "branchIdFk": 999999998},  # different branch to avoid RULE-SEC-036 overlap
    ))
    if r_no_lvl.passed:
        code = error_code_of(r_no_lvl)
        if code != "SEC_ROLE_BRANCH_DATA_ACCESS_LEVEL_REQUIRED":
            problems.append(ProblemEntry(
                "assumption", "Assign Branch Scope — omit dataAccessLevel",
                f"Expected error.code SEC_ROLE_BRANCH_DATA_ACCESS_LEVEL_REQUIRED, got {code!r}",
            ))

    return suite


# ─── Self-Service Auth (Sign Up / Activate / Forgot / Reset) ──────────────────
# ⚠ Part of SEC-002 gap package — Conflict #19 override in effect, see header.
# Covers: signup, activate, forgotPassword, resetPassword
# Negative: RULE-SEC-040/041 (confirmed runtime codes), RULE-SEC-032/033 (confirmed runtime codes)
#
# IMPORTANT LIMITATION: activation/reset tokens are issued via
# AccountActivationRequestedEvent / PasswordResetRequestedEvent (RULE-SEC-031)
# and delivered by a NotificationService subscriber that, per
# security-registry.md §2.7, does not exist yet ("no subscriber exists yet").
# No API response anywhere in this catalog returns the raw token value
# (SignupResponse = {userId, username, enabled} only). This script therefore
# CANNOT obtain a real token and cannot exercise the activate/reset HAPPY
# PATH — only the documented invalid-token negative cases, which are
# self-contained and don't require the real token value.

def test_self_service_auth(client: APIClient, observations: list, created_ids: dict,
                            problems: list) -> TestSuite:
    suite = TestSuite("Self-Service Auth")
    print("\n[Self-Service Auth] (SEC-002 gap package — override in effect)")

    username = f"selfreg_{rand_suffix()}"
    email = f"{username}@example.test"
    r = run(suite, "Signup (self-registration)", client.post(
        "api/auth/signup", expected=[200, 201],
        json={"username": username, "email": email, "password": "TestPass123"},
    ))
    signup_user_id = extract_field(r, "userId")
    if signup_user_id:
        # Signup-created accounts share the USERS table / DELETE /api/users/{id}
        # endpoint — tracked under "User" so the existing teardown path covers it.
        created_ids.setdefault("User", []).append(signup_user_id)
    if r.passed:
        enabled = extract_field(r, "enabled")
        if enabled is not False:
            problems.append(ProblemEntry(
                "bug", "Signup — enabled flag",
                f"RULE-SEC-030 requires ENABLED=0 on self-registered accounts; SignupResponse.enabled={enabled!r}",
            ))

    # Negative TC (RULE-SEC-040 / confirmed runtime code SIGNUP_USERNAME_ALREADY_EXISTS)
    r_dup_user = run(suite, "Signup — duplicate username (RULE-SEC-040)", client.post(
        "api/auth/signup", expected=[409],
        json={"username": username, "email": f"other_{rand_suffix()}@example.test", "password": "TestPass123"},
    ))
    if r_dup_user.passed:
        code = error_code_of(r_dup_user)
        if code != "SIGNUP_USERNAME_ALREADY_EXISTS":
            problems.append(ProblemEntry(
                "assumption", "Signup — duplicate username",
                f"Expected error.code SIGNUP_USERNAME_ALREADY_EXISTS (security-registry.md §2.7), got {code!r}",
            ))
    elif r_dup_user.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Signup — duplicate username",
            f"Expected 409 SIGNUP_USERNAME_ALREADY_EXISTS per RULE-SEC-040, got status {r_dup_user.status_code}",
        ))

    # Negative TC (RULE-SEC-041 / confirmed runtime code SIGNUP_EMAIL_ALREADY_EXISTS)
    r_dup_email = run(suite, "Signup — duplicate email (RULE-SEC-041)", client.post(
        "api/auth/signup", expected=[409],
        json={"username": f"other_{rand_suffix()}", "email": email, "password": "TestPass123"},
    ))
    if r_dup_email.passed:
        code = error_code_of(r_dup_email)
        if code != "SIGNUP_EMAIL_ALREADY_EXISTS":
            problems.append(ProblemEntry(
                "assumption", "Signup — duplicate email",
                f"Expected error.code SIGNUP_EMAIL_ALREADY_EXISTS (security-registry.md §2.7), got {code!r}",
            ))
    elif r_dup_email.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Signup — duplicate email",
            f"Expected 409 SIGNUP_EMAIL_ALREADY_EXISTS per RULE-SEC-041, got status {r_dup_email.status_code}",
        ))

    # Negative TC (RULE-SEC-032 / confirmed runtime code ACTIVATION_TOKEN_INVALID_OR_EXPIRED)
    # Cannot test the happy path — see docstring above.
    r_bad_activate = run(suite, "Activate — invalid/unknown token (RULE-SEC-032)", client.post(
        "api/auth/signup/activate", expected=[400],
        json={"token": f"invalid-{uuid.uuid4()}"},
    ))
    if r_bad_activate.passed:
        code = error_code_of(r_bad_activate)
        if code != "ACTIVATION_TOKEN_INVALID_OR_EXPIRED":
            problems.append(ProblemEntry(
                "assumption", "Activate — invalid token",
                f"Expected error.code ACTIVATION_TOKEN_INVALID_OR_EXPIRED (security-registry.md §2.7), got {code!r}",
            ))
    elif r_bad_activate.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Activate — invalid token",
            f"Expected 400 ACTIVATION_TOKEN_INVALID_OR_EXPIRED per RULE-SEC-032, got status {r_bad_activate.status_code}",
        ))

    # Forgot Password — RULE-SEC-038 (anti-enumeration): must ALWAYS be 200,
    # for both an existing and a non-existing email. Both are happy-path
    # assertions here (this rule has deliberately no ERR-ID / negative case).
    run(suite, "Forgot Password — existing email (RULE-SEC-038)", client.post(
        "api/auth/forgot-password", expected=[200], json={"email": email},
    ))
    run(suite, "Forgot Password — nonexistent email (RULE-SEC-038, anti-enumeration)", client.post(
        "api/auth/forgot-password", expected=[200], json={"email": f"doesnotexist_{rand_suffix()}@example.test"},
    ))

    # Negative TC (RULE-SEC-032 reset variant / confirmed runtime code RESET_TOKEN_INVALID_OR_EXPIRED)
    r_bad_reset = run(suite, "Reset Password — invalid/unknown token (RULE-SEC-032)", client.post(
        "api/auth/reset-password", expected=[400],
        json={"token": f"invalid-{uuid.uuid4()}", "newPassword": "NewTestPass123"},
    ))
    if r_bad_reset.passed:
        code = error_code_of(r_bad_reset)
        if code != "RESET_TOKEN_INVALID_OR_EXPIRED":
            problems.append(ProblemEntry(
                "assumption", "Reset Password — invalid token",
                f"Expected error.code RESET_TOKEN_INVALID_OR_EXPIRED (security-registry.md §2.7), got {code!r}",
            ))
    elif r_bad_reset.status_code is not None:
        problems.append(ProblemEntry(
            "bug", "Reset Password — invalid token",
            f"Expected 400 RESET_TOKEN_INVALID_OR_EXPIRED per RULE-SEC-032, got status {r_bad_reset.status_code}",
        ))

    # Stage E — Source: signup username/email/password constraints (signup.md)
    r_short_user = client.post("api/auth/signup", expected=[200, 201, 400],
                                json={"username": "ab", "email": f"short_{rand_suffix()}@example.test", "password": "TestPass123"})
    if (sid := extract_field(r_short_user, "userId")):
        created_ids.setdefault("User", []).append(sid)
    run_observation(observations, "Signup — username under minLength (2 chars)",
                     source="signup.md username Constraints: minLength=3", result=r_short_user)

    r_short_pw = client.post("api/auth/signup", expected=[200, 201, 400],
                              json={"username": f"su_{rand_suffix()}", "email": f"pw_{rand_suffix()}@example.test", "password": "abc"})
    if (pid := extract_field(r_short_pw, "userId")):
        created_ids.setdefault("User", []).append(pid)
    run_observation(observations, "Signup — password under minLength (3 chars)",
                     source="signup.md password Constraints: minLength=6", result=r_short_pw)

    return suite


# ─── Cleanup / Teardown (best-effort) ──────────────────────────────────────────

def cleanup(client: APIClient, token: Optional[str], created_ids: dict, problems: list) -> None:
    """
    Reverse of Stage B dependency order: RoleBranch (hard-delete, FK->Role) ->
    UserProfile (no delete endpoint exists — flagged, not removable) ->
    unassign roles from Users (pre-step, avoids deleteRole's 409) ->
    User (hard-delete, covers both admin-created and self-registration users)
    -> Role (hard-delete) -> Permission (no delete endpoint — flagged) ->
    Page (soft-deactivate only, no hard-delete endpoint).
    """
    print("\n[Cleanup]")
    hard_deleted = 0
    soft_deactivated = 0
    leaked_no_api_path = 0

    # 1. Role Branches — hard delete, composite key
    for (role_id, branch_id) in created_ids.get("RoleBranch", []):
        r = client.delete(f"api/v1/security/role-branches/{role_id}/{branch_id}", token=token,
                           expected=[200, 204, 404])
        if r.status_code in (200, 204):
            hard_deleted += 1
            print(f"  ✓ Deleted RoleBranch ({role_id},{branch_id})")
        else:
            print(f"  ⚠ Could not delete RoleBranch ({role_id},{branch_id}) (status {r.status_code})")

    # 2. User Profiles — NO delete endpoint exists (confirmed absent per
    # security-registry.md §2.8). Cannot deactivate either (update payload
    # has no isActiveFl field). This is a genuine cleanup gap in the API
    # itself, not a script limitation — surfaced explicitly, never silently
    # claimed as cleaned up.
    for _user_id in created_ids.get("UserProfile", []):
        leaked_no_api_path += 1
        print(f"  ⚠ UserProfile for user #{_user_id} has NO cleanup path via this API "
              f"(no DELETE endpoint, no isActiveFl in UpdateSecUserProfileRequest) — will remain in DB.")

    # 3. Pre-step: strip role assignments from any Users we created, so
    # deleteRole doesn't 409 on "role has user assignments".
    for _user_id in created_ids.get("User", []):
        client.put(f"api/users/{_user_id}/roles", token=token, expected=[200, 404], json={"roleNames": []})

    # 4. Users — hard delete (covers both admin-created and self-registered)
    for _user_id in created_ids.get("User", []):
        r = client.delete(f"api/users/{_user_id}", token=token, expected=[200, 204, 404, 409])
        if r.status_code in (200, 204):
            hard_deleted += 1
            print(f"  ✓ Deleted User #{_user_id}")
        elif r.status_code == 409:
            print(f"  ⚠ Could not delete User #{_user_id} — still has dependencies (status 409)")
        else:
            print(f"  ⚠ Could not delete User #{_user_id} (status {r.status_code})")

    # 5. Roles — hard delete
    for _role_id in created_ids.get("Role", []):
        r = client.delete(f"api/roles/{_role_id}", token=token, expected=[200, 204, 404, 409])
        if r.status_code in (200, 204):
            hard_deleted += 1
            print(f"  ✓ Deleted Role #{_role_id}")
        elif r.status_code == 409:
            print(f"  ⚠ Could not delete Role #{_role_id} — still has dependencies (status 409)")
        else:
            print(f"  ⚠ Could not delete Role #{_role_id} (status {r.status_code})")

    # 6. Permissions — NO delete endpoint exists anywhere in the API Catalog
    for _perm_id in created_ids.get("Permission", []):
        leaked_no_api_path += 1
        print(f"  ⚠ Permission #{_perm_id} has NO cleanup path via this API (no DELETE/deactivate endpoint) — will remain in DB.")

    # 7. Pages — soft-deactivate only (no hard-delete endpoint)
    for _page_id in created_ids.get("Page", []):
        r = client.put(f"api/pages/{_page_id}/deactivate", token=token, expected=[200, 404, 409])
        if r.status_code == 200:
            soft_deactivated += 1
            print(f"  ✓ Deactivated Page #{_page_id} (no hard-delete endpoint documented)")
        else:
            soft_deactivated += 1
            print(f"  ⚠ Could not deactivate Page #{_page_id} (status {r.status_code}) — may remain active")

    if soft_deactivated:
        print(f"  ⚠ {soft_deactivated} Page record(s) remain in the database (soft-deactivated) — "
              f"Page Management has no hard-delete endpoint per its API docs.")
    if leaked_no_api_path:
        print(f"  ⚠ {leaked_no_api_path} record(s) (UserProfile/Permission) have NO cleanup path via "
              f"this module's API at all — this is a documented API gap, not a script defect.")
        problems.append(ProblemEntry(
            "assumption", "Cleanup coverage gap",
            f"{leaked_no_api_path} UserProfile/Permission record(s) created by this run cannot be "
            f"removed or deactivated via any endpoint in this module's API Catalog.",
        ))
    if hard_deleted:
        print(f"  ✓ {hard_deleted} record(s) permanently removed.")


# ─── Problems Report (Stage G) ──────────────────────────────────────────────────

def generate_problems_report(problems: list, suites: list, output_path: str) -> None:
    bugs = [p for p in problems if p.bucket == "bug"]
    assumptions = [p for p in problems if p.bucket == "assumption"]
    infra = [p for p in problems if p.bucket == "infra"]

    # Infra failures: connection-refused style errors surfaced during the run
    for s in suites:
        for r in s.results:
            if not r.passed and r.error and "Connection refused" in r.error:
                infra.append(ProblemEntry("infra", r.name, r.error))

    lines = ["# Security Module — Problems Report", ""]
    lines.append("Filtered view: pass/fail failures only, categorized per Stage G. "
                  "Exploratory (Stage E) observations are NOT included here — see the HTML "
                  "report's 'Exploratory Observations' section instead, since their expected "
                  "outcome is undocumented by design.")
    lines.append("")
    lines.append(f"## 🔴 Likely Real Bugs ({len(bugs)})")
    lines.append("")
    if bugs:
        for p in bugs:
            lines.append(f"- **{p.name}** — {p.detail}")
    else:
        lines.append("_None._")
    lines.append("")
    lines.append(f"## 🟡 Test Assumption Mismatches ({len(assumptions)})")
    lines.append("")
    if assumptions:
        for p in assumptions:
            lines.append(f"- **{p.name}** — {p.detail}")
    else:
        lines.append("_None._")
    lines.append("")
    lines.append(f"## ⚪ Infrastructure ({len(infra)})")
    lines.append("")
    if infra:
        for p in infra:
            lines.append(f"- **{p.name}** — {p.detail}")
    else:
        lines.append("_None._")
    lines.append("")
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"📄 Problems report written to: {output_path}")


# ─── HTML Report ───────────────────────────────────────────────────────────────

def generate_html_report(suites: list, observations: list, output_path: str,
                          duration: float, base_url: str) -> None:
    total_pass = sum(s.passed for s in suites)
    total_fail = sum(s.failed for s in suites)
    total_all = sum(s.total for s in suites)
    pass_pct = round(total_pass / total_all * 100, 1) if total_all else 0

    suite_rows = ""
    for suite in suites:
        pct = round(suite.passed / suite.total * 100, 1) if suite.total else 0
        suite_rows += f"""
        <tr>
          <td>{suite.name}</td>
          <td class="num">{suite.total}</td>
          <td class="num pass">{suite.passed}</td>
          <td class="num fail">{suite.failed}</td>
          <td class="num">{pct}%</td>
        </tr>"""

    detail_sections = ""
    for suite in suites:
        rows = ""
        for r in suite.results:
            status_class = "pass" if r.passed else "fail"
            code = r.status_code or "ERR"
            expected = ", ".join(str(s) for s in r.expected_statuses)
            note_html = f'<span class="note">{r.note}</span>' if r.note else ""
            error_html = f'<div class="error-msg">{r.error}</div>' if r.error else ""
            body_html = ""
            if r.response_body:
                short = r.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(r.response_body) > 300 else ""}</pre></details>'
            rows += f"""
            <tr class="{status_class}">
              <td><span class="badge {status_class}">{r.status_label}</span></td>
              <td><span class="method {r.method.lower()}">{r.method}</span></td>
              <td class="test-name">{r.name} {note_html}</td>
              <td class="url">{r.url}</td>
              <td class="num">{code}</td>
              <td class="num">{expected}</td>
              <td class="num">{r.duration_ms:.0f}ms</td>
              <td>{error_html}{body_html}</td>
            </tr>"""
        detail_sections += f"""
        <section>
          <h2>{suite.name} — {suite.passed}/{suite.total} passed</h2>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Test</th><th>URL</th>
              <th>Got</th><th>Expected</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </section>"""

    observation_section = ""
    if observations:
        obs_rows = ""
        for o in observations:
            code = o.status_code or "ERR"
            body_html = ""
            if o.response_body:
                short = o.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(o.response_body) > 300 else ""}</pre></details>'
            obs_rows += f"""
            <tr>
              <td><span class="badge observed">OBSERVED</span></td>
              <td><span class="method {o.method.lower()}">{o.method}</span></td>
              <td class="test-name">{o.name}</td>
              <td class="url">{o.url}</td>
              <td class="num">{code}</td>
              <td class="url">{o.source}</td>
              <td class="num">{o.duration_ms:.0f}ms</td>
              <td>{body_html}</td>
            </tr>"""
        observation_section = f"""
        <section>
          <h2>⚠️ Exploratory Observations — undocumented expected outcomes, not pass/fail</h2>
          <p style="padding:0 20px;color:#666;font-size:.85rem">
            These scenarios test documented constraints (Required/maxLength/type) but the API's
            expected response for violating them isn't specified in any governance document.
            Review the observed status/body against your intended behavior — do not treat these
            as failures of the implementation.
          </p>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Scenario</th><th>URL</th>
              <th>Observed</th><th>Source (doc/field)</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{obs_rows}</tbody>
          </table>
        </section>"""

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" />
<title>Security Module API Test Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
<style>
  *,*::before,*::after{{box-sizing:border-box}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;margin:0;padding:20px;background:#f4f6f9;color:#1a1a2e}}
  h1{{margin-bottom:4px}} .meta{{color:#666;font-size:.9rem;margin-bottom:24px}}
  .override-banner{{background:#fff3cd;color:#8a6314;border-radius:10px;padding:14px 20px;margin-bottom:20px;font-size:.85rem;box-shadow:0 2px 6px rgba(0,0,0,.08)}}
  .summary{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:28px}}
  .card{{background:#fff;border-radius:10px;padding:18px 24px;box-shadow:0 2px 6px rgba(0,0,0,.08);min-width:140px;text-align:center}}
  .card .num{{font-size:2.2rem;font-weight:700;line-height:1}} .card .label{{font-size:.8rem;color:#888;margin-top:4px}}
  .card.total .num{{color:#3a86ff}} .card.pass .num{{color:#2ec4b6}} .card.fail .num{{color:#e63946}}
  .suite-table{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  table{{width:100%;border-collapse:collapse;font-size:.875rem}}
  th{{background:#f0f2f5;text-align:left;padding:10px 14px;font-weight:600;color:#555}}
  td{{padding:8px 14px;border-top:1px solid #eef0f3;vertical-align:top}}
  tr.pass td{{background:#f6fff8}} tr.fail td{{background:#fff5f5}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:10px;font-size:.75rem;font-weight:700}}
  .badge.pass{{background:#d4f7ef;color:#1a7a6f}} .badge.fail{{background:#fde8e8;color:#b91c1c}}
  .badge.observed{{background:#fff3cd;color:#8a6314}}
  .method{{display:inline-block;padding:2px 6px;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff}}
  .method.get{{background:#3a86ff}} .method.post{{background:#2ec4b6}} .method.put{{background:#f4a261}} .method.delete{{background:#e63946}}
  .num{{text-align:center}} .url{{font-size:.75rem;color:#666;word-break:break-all;max-width:260px}}
  .test-name{{font-weight:500}} .note{{font-size:.72rem;color:#999;margin-left:6px}}
  .error-msg{{color:#b91c1c;font-size:.8rem}}
  details summary{{cursor:pointer;color:#3a86ff;font-size:.78rem;margin-top:4px}}
  pre{{background:#f8f8f8;padding:8px;border-radius:4px;font-size:.72rem;overflow-x:auto;max-width:400px;white-space:pre-wrap}}
  section{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  section h2{{padding:14px 20px;margin:0;background:#f0f2f5;font-size:1rem;border-bottom:1px solid #e0e4ea}}
</style></head>
<body>
  <h1>Security Module API Test Report</h1>
  <p class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;·&nbsp;
     Base URL: {base_url} &nbsp;·&nbsp; Duration: {duration:.1f}s</p>
  <div class="override-banner">
    ⚠ <strong>Governance override in effect:</strong> execution-plan-SEC-gaps.md marks the 12
    SEC-002 gap-package APIs (Self-Service Auth, User Profiles, Role Branches suites below) as
    MODE 3 EXECUTION BLOCKED pending Conflict #19 architecture sign-off. This run was explicitly
    authorized to proceed anyway by the requester, who accepted responsibility for the override.
  </div>
  <div class="summary">
    <div class="card total"><div class="num">{total_all}</div><div class="label">Total</div></div>
    <div class="card pass"><div class="num">{total_pass}</div><div class="label">Passed</div></div>
    <div class="card fail"><div class="num">{total_fail}</div><div class="label">Failed</div></div>
    <div class="card total"><div class="num">{pass_pct}%</div><div class="label">Pass Rate</div></div>
  </div>
  <div class="suite-table"><table><thead><tr><th>Suite</th><th>Total</th><th>Pass</th><th>Fail</th><th>Rate</th></tr></thead>
  <tbody>{suite_rows}</tbody></table></div>
  {detail_sections}
  {observation_section}
</body></html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"\n📄 HTML report written to: {output_path}")


# ─── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Security module API test suite")
    parser.add_argument("--base-url", default=BASE_URL, help="Base API URL")
    parser.add_argument("--report", default="security_api_test_report.html", help="Output HTML file")
    parser.add_argument("--problems-report", default="security_problems_report.md", help="Output problems markdown file")
    args = parser.parse_args()

    client = APIClient(args.base_url)
    start_time = time.perf_counter()

    print("=" * 60)
    print("  Security Module API Test Suite")
    print("  ⚠ Conflict #19 override in effect for SEC-002 gap-package APIs")
    print(f"  Base URL: {args.base_url}")
    print("=" * 60)

    auth_suite, token = test_auth(client)
    observations: list = []
    problems: list = []
    created_ids: dict = {
        "Page": [], "Permission": [], "Role": [], "User": [],
        "UserProfile": [], "RoleBranch": [],
    }

    page_suite = TestSuite("Page Management")
    permission_suite = TestSuite("Permission Management")
    role_suite = TestSuite("Role Access Control")
    user_suite = TestSuite("User Management")
    menu_suite = TestSuite("Menu Management")
    user_profile_suite = TestSuite("Security DataScope - User Profiles")
    role_branch_suite = TestSuite("Security DataScope - Role Branches")
    self_service_suite = TestSuite("Self-Service Auth")

    try:
        # Stage B dependency order: root entities first, children threaded
        # with the parent's returned ID/code — never hardcoded.
        page_suite, page_ids = test_pages(client, token, observations, created_ids)
        permission_suite, _perm_ids = test_permissions(client, token, page_ids.get("id"), observations, created_ids)
        role_suite, role_ids = test_roles(client, token, page_ids.get("pageCode"), observations, created_ids)
        user_suite, user_ids = test_users(client, token, None, observations, created_ids)
        # role_name threaded in after Role creation completes, for assignRoles.
        # AssignRolesRequest.roleNames resolves via Role.roleName (RoleRepository.findByRoleName,
        # per UserService.assignRoles) — NOT roleCode, despite the field's plural-of-"name" look.
        if role_ids.get("id"):
            role_lookup = client.get(f"api/roles/{role_ids['id']}", token=token, expected=[200])
            role_name_val = extract_field(role_lookup, "roleName")
            if user_ids.get("id") and role_name_val:
                run(user_suite, "Assign Roles to User (post-hoc, role now available)", client.put(
                    f"api/users/{user_ids['id']}/roles", token=token, expected=[200],
                    json={"roleNames": [role_name_val]},
                ))
        menu_suite = test_menu(client, token, user_ids.get("id"))
        user_profile_suite = test_user_profiles(client, token, user_ids.get("id"), observations, created_ids, problems)
        role_branch_suite = test_role_branches(client, token, role_ids.get("id"), observations, created_ids, problems)
        self_service_suite = test_self_service_auth(client, observations, created_ids, problems)
    finally:
        cleanup(client, token, created_ids, problems)

    duration = time.perf_counter() - start_time
    suites = [auth_suite, page_suite, permission_suite, role_suite, user_suite,
              menu_suite, user_profile_suite, role_branch_suite, self_service_suite]

    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    total_pass = sum(s.passed for s in suites)
    total_all = sum(s.total for s in suites)
    for s in suites:
        bar = "█" * s.passed + "░" * s.failed
        print(f"  {s.name:<38} {s.passed:>3}/{s.total:<3}  {bar}")
    print(f"\n  Total: {total_pass}/{total_all} passed  ({duration:.1f}s)")
    if observations:
        print(f"  Exploratory observations: {len(observations)} (see HTML report — not pass/fail)")
    if problems:
        print(f"  Problems flagged for review: {len(problems)} (see problems report)")

    generate_html_report(suites, observations, args.report, duration, args.base_url)
    generate_problems_report(problems, suites, args.problems_report)
    sys.exit(0 if total_pass == total_all else 1)


if __name__ == "__main__":
    main()
