#!/usr/bin/env python3
"""
test_file_apis.py — File Service API verification script
Generated by MODE 5 (Project 5) from:
  - execution-plan.md (PLAN-ID: PLAN-FILE-001, Gate ALIGN ✓)
  - test-plan.md      (TC-FILE-001..025, JUnit/backend scope)
  - API docs: issueUploadToken, upload, issueAccessToken, download, listByOwner, delete
  - index.md (shared schema: envelope, pagination, Known Error Codes)

Intended for Dev/Test environments only.

⚠ KNOWN GAPS — see reply to user for details, summarized here for future maintainers:
  1. FileCategory (ENTITY-FILE-002) has NO Create/Update API (DRV-FILE-001 — reference
     table, DB-seeded only). FILE_CATEGORY_FK below MUST be a real, pre-existing seed
     value in your target environment — this script cannot create one.
  2. `issueAccessToken` (POST /api/v1/files/{fileDocumentPk}/access-token) is present
     in the attached API docs but is NOT mapped to any API-FILE-00X ID in
     execution-plan.md (only API-FILE-001..005 are registered, and none of their
     documented paths match). Implemented here directly from its own doc since the
     path/request/response are unambiguous, but traceability to a governed API-ID is
     unconfirmed — flagged, not silently assumed.
  3. RULE-FILE-002 (token TTL = 100 minutes, ERR-FILE-0002) is NOT exercised here —
     doing so would require waiting 100+ real minutes or manipulating server/client
     clocks, neither of which this script fabricates. TC-FILE-005/006 are therefore
     left as a manual/CI-scheduled test, not automated.
  4. RULE-FILE-007 (ownership/Admin restriction on delete, ERR-FILE-0007 / TC-FILE-014)
     and TC-FILE-023 (permission enforcement) require a second, non-owner/non-admin
     user account distinct from ADMIN_USERNAME. Optional SECOND_USER_* config below;
     if left blank, both scenarios are skipped with an explicit console note rather
     than silently omitted.

Usage:
    python3 test_file_apis.py
    python3 test_file_apis.py --base-url http://localhost:7272
    python3 test_file_apis.py --report file_api_test_report.html
"""

import argparse
import json
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("requests library not found. Install it: pip install requests")
    sys.exit(1)


# ─── Configuration (placeholders — never invent real credentials) ─────────────

BASE_URL = "http://localhost:7272"
TIMEOUT = 30  # seconds (file upload/download can be slower than plain CRUD)

ADMIN_USERNAME = "admin"  # CHANGE ME
ADMIN_PASSWORD = "admin"  # CHANGE ME

# Optional second user, distinct from ADMIN, holding at least PERM_FILE_ATTACHMENT_VIEW
# but explicitly NOT the owner of test files and NOT an Admin — needed only for
# RULE-FILE-007 (TC-FILE-014) and TC-FILE-023. Leave blank to skip those two scenarios.
SECOND_USER_USERNAME = ""  # CHANGE ME (optional)
SECOND_USER_PASSWORD = ""  # CHANGE ME (optional)

# FileCategory is a DB-seeded reference table (DRV-FILE-001) — no Create API exists.
# This MUST be a real, pre-existing fileCategoryFk in your target environment.
FILE_CATEGORY_FK = 1  # CHANGE ME — PURCHASE_ORDER_DOC / PRC, seeded by V3__file_service_schema_and_seed.sql Block 5b

OWNER_ID = 1001          # doc Example value (FileUploadTokenRequest.ownerId)
OWNER_TYPE = "PURCHASE_ORDER"  # doc Example value
MODULE_CODE = "PRC"      # doc Example value

DEFAULT_MAX_SIZE_BYTES = 5_242_880  # RULE-FILE-001 documented default ceiling (5MB)

# Intended for Dev/Test environments only.


# ─── Data classes (fixed — do not change per module) ──────────────────────────

@dataclass
class TestResult:
    name: str
    method: str
    url: str
    status_code: Optional[int]
    passed: bool
    expected_statuses: list[int]
    duration_ms: float
    error: Optional[str] = None
    response_body: Optional[str] = None
    note: Optional[str] = None

    @property
    def status_label(self) -> str:
        return "PASS" if self.passed else "FAIL"


@dataclass
class TestSuite:
    name: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed(self) -> int:
        return len(self.results) - self.passed

    @property
    def total(self) -> int:
        return len(self.results)


@dataclass
class Observation:
    """
    Stage E exploratory scenario with an UNDOCUMENTED expected outcome. Never
    counted as pass/fail — the point is to record actual behavior for human
    review, not to assert a guessed business rule.
    """
    name: str
    method: str
    url: str
    status_code: Optional[int]
    duration_ms: float
    source: str
    response_body: Optional[str] = None


# ─── HTTP helper (fixed) ───────────────────────────────────────────────────────

class APIClient:
    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "Content-Type": "application/json",
        })

    def _make(self, method: str, path: str, token: Optional[str] = None,
              expected: Optional[list[int]] = None, headers: Optional[dict] = None,
              **kwargs) -> TestResult:
        url = f"{self.base_url}/{path.lstrip('/')}"
        headers = dict(headers) if headers else {}
        if token:
            headers["Authorization"] = f"Bearer {token}"
        if expected is None:
            expected = [200]

        start = time.perf_counter()
        try:
            resp = self.session.request(method.upper(), url, headers=headers, timeout=TIMEOUT, **kwargs)
            duration = (time.perf_counter() - start) * 1000
            content_type = resp.headers.get("Content-Type", "")
            if "application/json" in content_type:
                try:
                    body = json.dumps(resp.json(), indent=2, ensure_ascii=False)
                except Exception:
                    body = resp.text[:500]
            else:
                # Binary (download) or non-JSON response — don't attempt to decode as JSON.
                body = f"<{len(resp.content)} bytes, Content-Type: {content_type}>"
            return TestResult(
                name="", method=method.upper(), url=url, status_code=resp.status_code,
                passed=resp.status_code in expected, expected_statuses=expected,
                duration_ms=round(duration, 1), response_body=body,
            )
        except requests.exceptions.ConnectionError:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1),
                error="Connection refused — is the server running?",
            )
        except Exception as exc:
            duration = (time.perf_counter() - start) * 1000
            return TestResult(
                name="", method=method.upper(), url=url, status_code=None, passed=False,
                expected_statuses=expected, duration_ms=round(duration, 1), error=str(exc),
            )

    def get(self, path, token=None, expected=None, **kw):
        return self._make("GET", path, token, expected, **kw)

    def post(self, path, token=None, expected=None, **kw):
        return self._make("POST", path, token, expected, **kw)

    def delete(self, path, token=None, expected=None, **kw):
        return self._make("DELETE", path, token, expected, **kw)

    def post_multipart(self, path, token=None, expected=None, files=None, **kw):
        """
        Multipart upload (API-FILE-002). Content-Type must NOT be the session's
        default 'application/json' — setting it to None here unsets it for this
        call only, letting `requests` compute the correct multipart boundary header.
        """
        return self._make("POST", path, token, expected,
                           headers={"Content-Type": None}, files=files, **kw)


# ─── Test runner helpers (fixed) ───────────────────────────────────────────────

def run(suite: TestSuite, name: str, result: TestResult, note: str = "") -> TestResult:
    result.name = name
    result.note = note
    suite.results.append(result)
    status = "✓" if result.passed else "✗"
    code = result.status_code or "ERR"
    print(f"  {status} [{code}] {name} ({result.duration_ms:.0f}ms)")
    if not result.passed and result.error:
        print(f"      Error: {result.error}")
    return result


def run_observation(bucket: list, name: str, source: str, result: TestResult) -> None:
    obs = Observation(
        name=name, method=result.method, url=result.url, status_code=result.status_code,
        duration_ms=result.duration_ms, source=source, response_body=result.response_body,
    )
    bucket.append(obs)
    code = result.status_code or "ERR"
    print(f"  👁 [{code}] {name} — observed (source: {source})")


def data_of(result: TestResult):
    """
    Envelope shape {success, message, data, error, timestamp, correlationId} per
    index.md's Common Response Envelope (schema: ApiResponseFileUploadResponse).
    """
    if not result.response_body or result.response_body.startswith("<"):
        return None
    try:
        return json.loads(result.response_body).get("data")
    except Exception:
        return None


def error_code_of(result: TestResult) -> Optional[str]:
    """
    Runtime error.code value (underscored, e.g. FILE_SIZE_EXCEEDED) per index.md's
    Known Error Codes table — NEVER the governance ERR-FILE-NNNN hyphenated ID.
    """
    if not result.response_body or result.response_body.startswith("<"):
        return None
    try:
        body = json.loads(result.response_body)
        err = body.get("error")
        return err.get("code") if isinstance(err, dict) else None
    except Exception:
        return None


def get_field(result: TestResult, key: str):
    d = data_of(result)
    return d.get(key) if isinstance(d, dict) else None


def extract_token(auth_result: TestResult) -> Optional[str]:
    d = data_of(auth_result)
    return d.get("accessToken") if isinstance(d, dict) else None


def make_bytes(n: int) -> bytes:
    """Deterministic filler content of exactly n bytes — not a real document, just sized data."""
    pattern = b"FILE-API-TEST-DATA-"
    reps = (n // len(pattern)) + 1
    return (pattern * reps)[:n]


def tamper_token(token: str) -> str:
    """
    Flip one character of an opaque encrypted token to simulate corruption
    (RULE-FILE-003 / ERR-FILE-0003, tampered case). Deterministic, not random,
    so failures are reproducible.
    """
    if not token:
        return token
    idx = len(token) // 2
    chars = list(token)
    alt = "x" if chars[idx] != "x" else "y"
    # Only substitute if it keeps the token the same length / charset-safe;
    # encryptedToken is URL-safe per the docs (used as a path segment).
    chars[idx] = alt
    return "".join(chars)


# ─── Auth (fixed pattern) ──────────────────────────────────────────────────────

def login(client: APIClient, username: str, password: str, label: str) -> tuple[TestSuite, Optional[str]]:
    suite = TestSuite(label)
    print(f"\n[{label}]")
    r = run(suite, f"{label} Login", client.post(
        "api/auth/login", expected=[200],
        json={"username": username, "password": password},
    ))
    token = extract_token(r)
    return suite, token


# ─── File Service test suite ───────────────────────────────────────────────────
# Covers: API-FILE-001 (issueUploadToken), API-FILE-002 (upload), API-FILE-003
# (download), API-FILE-004 (delete), API-FILE-005 (listByOwner), and
# issueAccessToken (unmapped to a governed API-ID — see header note #2).
# Negative: RULE-FILE-001/ERR-FILE-0001, RULE-FILE-003/ERR-FILE-0003,
#           RULE-FILE-004/ERR-FILE-0004, RULE-FILE-007/ERR-FILE-0007 (optional),
#           PLATFORM-STD/ERR-FILE-0008, PLATFORM-STD/ERR-FILE-0009
# Skipped (documented, not silently omitted): RULE-FILE-002/ERR-FILE-0002 (TTL)

def issue_upload_token(client, token, category_fk, expected, owner_id=OWNER_ID,
                        owner_type=OWNER_TYPE, module_code=MODULE_CODE):
    return client.post(
        "api/v1/files/upload-token", token=token, expected=expected,
        json={"ownerId": owner_id, "ownerType": owner_type,
              "moduleCode": module_code, "fileCategoryFk": category_fk},
    )


def issue_access_token(client, token, file_document_pk, action, expected):
    return client.post(
        f"api/v1/files/{file_document_pk}/access-token", token=token, expected=expected,
        params={"action": action},
    )


def upload(client, token, encrypted_token, content: bytes, filename: str, expected):
    return client.post_multipart(
        f"upload/{encrypted_token}", token=token, expected=expected,
        files={"file": (filename, content, "application/octet-stream")},
    )


def test_file_document(client: APIClient, token: Optional[str], second_token: Optional[str],
                        created_ids: dict[str, list[int]]) -> tuple[TestSuite, list]:
    suite = TestSuite("FileDocument")
    observations: list = []
    print("\n[FileDocument — File Service happy path + governed negative tests]")

    # ── Happy path lifecycle (API-FILE-001 → 002 → 005 → issueAccessToken → 003 → 004) ──
    r = run(suite, "Issue Upload Token (API-FILE-001 happy path, TC-FILE-015)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    upload_token = get_field(r, "encryptedToken")

    r = run(suite, "Upload File within size limit (API-FILE-002, TC-FILE-001/016)",
            upload(client, token, upload_token, make_bytes(2 * 1024 * 1024), "invoice.pdf", expected=[200, 201]))
    file_pk = get_field(r, "fileDocumentPk")
    if file_pk:
        created_ids.setdefault("FileDocument", []).append(file_pk)

    if file_pk:
        run(suite, "List Files for Owner (API-FILE-005, TC-FILE-019)",
            client.get(f"api/v1/files/{OWNER_ID}", token=token, expected=[200]))

        r = run(suite, "Issue Download Access Token (issueAccessToken, action=DOWNLOAD)",
                issue_access_token(client, token, file_pk, "DOWNLOAD", expected=[200, 201]))
        dl_token = get_field(r, "encryptedToken")

        run(suite, "Download File (API-FILE-003 happy path, TC-FILE-004/017)",
            client.get(f"download/{dl_token}", token=token, expected=[200]))

        r = run(suite, "Issue Delete Access Token (issueAccessToken, action=DELETE)",
                issue_access_token(client, token, file_pk, "DELETE", expected=[200, 201]))
        del_token = get_field(r, "encryptedToken")

        run(suite, "Delete File — owner (API-FILE-004 happy path, TC-FILE-013/018)",
            client.delete(f"{del_token}", token=token, expected=[200]))

        # Edge case: download of a now-DELETED file → 410 (TC-FILE-020, ERR-FILE-0008)
        r = run(suite, "Issue Download Token for DELETED file",
                issue_access_token(client, token, file_pk, "DOWNLOAD", expected=[200, 201]))
        dl_token_2 = get_field(r, "encryptedToken")
        r = run(suite, "Download DELETED file — expect 410 (TC-FILE-020, ERR-FILE-0008)",
                client.get(f"download/{dl_token_2}", token=token, expected=[410]))
        code = error_code_of(r)
        if r.passed and code and code != "FILE_NO_LONGER_AVAILABLE":
            print(f"      ⚠ Status matched but error.code was '{code}', expected FILE_NO_LONGER_AVAILABLE")

    # ── RULE-FILE-001 / ERR-FILE-0001 — oversized upload rejected (TC-FILE-002/022) ──
    r = run(suite, "Issue Upload Token (for oversized-file test)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    ov_token = get_field(r, "encryptedToken")
    r = run(suite, "Upload File exceeding size limit — expect 400 (TC-FILE-002, ERR-FILE-0001)",
            upload(client, token, ov_token, make_bytes(6 * 1024 * 1024), "toolarge.bin", expected=[400]))
    code = error_code_of(r)
    if r.passed and code and code != "FILE_SIZE_EXCEEDED":
        print(f"      ⚠ Status matched but error.code was '{code}', expected FILE_SIZE_EXCEEDED")
    oversized_pk = get_field(r, "fileDocumentPk")
    if oversized_pk:
        created_ids.setdefault("FileDocument", []).append(oversized_pk)

    # ── Boundary: exactly at default 5MB ceiling succeeds (TC-FILE-003 pattern, ──
    # source: execution-plan.md documented DEFAULT_MAX_SIZE_BYTES = 5,242,880) ──
    r = run(suite, "Issue Upload Token (for boundary-size test)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    bd_token = get_field(r, "encryptedToken")
    r = run(suite, f"Upload File at exactly {DEFAULT_MAX_SIZE_BYTES} bytes (default ceiling boundary)",
            upload(client, token, bd_token, make_bytes(DEFAULT_MAX_SIZE_BYTES), "atlimit.bin", expected=[200, 201]))
    bd_pk = get_field(r, "fileDocumentPk")
    if bd_pk:
        created_ids.setdefault("FileDocument", []).append(bd_pk)

    # ── RULE-FILE-004 / ERR-FILE-0004 — reuse of consumed token rejected (TC-FILE-009/010) ──
    r = run(suite, "Issue Upload Token (for single-use test)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    su_token = get_field(r, "encryptedToken")
    r = run(suite, "First use of fresh token succeeds (TC-FILE-009)",
            upload(client, token, su_token, make_bytes(1024), "first.txt", expected=[200, 201]))
    su_pk = get_field(r, "fileDocumentPk")
    if su_pk:
        created_ids.setdefault("FileDocument", []).append(su_pk)
    r = run(suite, "Reuse of already-consumed token rejected (TC-FILE-010, ERR-FILE-0004)",
            upload(client, token, su_token, make_bytes(1024), "second.txt", expected=[401]))
    code = error_code_of(r)
    if r.passed and code and code != "FILE_TOKEN_ALREADY_USED":
        print(f"      ⚠ Status matched but error.code was '{code}', expected FILE_TOKEN_ALREADY_USED")

    # ── RULE-FILE-003 / ERR-FILE-0003 — tampered token (401) & action-mismatch (403) ──
    r = run(suite, "Issue Upload Token (for tamper test)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    raw_token = get_field(r, "encryptedToken")
    corrupted = tamper_token(raw_token) if raw_token else None
    run(suite, "Tampered token rejected (TC-FILE-008a, ERR-FILE-0003, expect 401)",
        upload(client, token, corrupted, make_bytes(1024), "tampered.txt", expected=[401]))

    if file_pk:
        # file_pk was already deleted above; re-issue a download token and replay it
        # against DELETE to force an action mismatch (upload token used earlier is gone,
        # so use a fresh download-action token against the delete endpoint instead).
        r = run(suite, "Issue Upload Token (for action-mismatch test)",
                issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
        mismatch_token = get_field(r, "encryptedToken")
        run(suite, "Upload-action token replayed on DELETE — action mismatch (TC-FILE-008b, ERR-FILE-0003, expect 403)",
            client.delete(f"{mismatch_token}", token=token, expected=[403]))

    # ── RULE-FILE-007 / ERR-FILE-0007 — non-owner, non-Admin delete rejected (TC-FILE-014) ──
    if second_token:
        r = run(suite, "Issue Upload Token (for ownership test)",
                issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
        own_token = get_field(r, "encryptedToken")
        r = run(suite, "Upload file as owner (setup for ownership test)",
                upload(client, token, own_token, make_bytes(1024), "owned.txt", expected=[200, 201]))
        own_pk = get_field(r, "fileDocumentPk")
        if own_pk:
            created_ids.setdefault("FileDocument", []).append(own_pk)
            r = run(suite, "Issue Delete Access Token (as owner, for cross-user attempt)",
                    issue_access_token(client, token, own_pk, "DELETE", expected=[200]))
            cross_del_token = get_field(r, "encryptedToken")
            r = run(suite, "Non-owner, non-Admin delete rejected (TC-FILE-014, ERR-FILE-0007, expect 403)",
                    client.delete(f"{cross_del_token}", token=second_token, expected=[403]))
            code = error_code_of(r)
            if r.passed and code and code != "FILE_DELETE_NOT_AUTHORIZED":
                print(f"      ⚠ Status matched but error.code was '{code}', expected FILE_DELETE_NOT_AUTHORIZED")
    else:
        print("  ⊘ Skipped — RULE-FILE-007 (TC-FILE-014) and TC-FILE-023 need SECOND_USER_* "
              "credentials (a non-owner, non-Admin account). Set them at the top of this "
              "script to enable these two scenarios.")

    # ── PLATFORM-STD / ERR-FILE-0009 — unknown fileCategoryFk (TC-FILE-021) ──
    r = run(suite, "Upload-token request with unknown fileCategoryFk (TC-FILE-021, ERR-FILE-0009, expect 404)",
            issue_upload_token(client, token, 999999999, expected=[404]))
    code = error_code_of(r)
    if r.passed and code and code != "FILE_CATEGORY_NOT_FOUND":
        print(f"      ⚠ Status matched but error.code was '{code}', expected FILE_CATEGORY_NOT_FOUND")

    # ── Edge case: empty list result → 200, not 404 (TC-FILE-024) ──
    run(suite, "List Files for owner with zero files — expect 200, empty content (TC-FILE-024)",
        client.get("api/v1/files/999888", token=token, expected=[200]))

    # ── TC-FILE-025 — SQL injection resistance via filename ──
    r = run(suite, "Issue Upload Token (for SQLi filename test)",
            issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201]))
    sqli_token = get_field(r, "encryptedToken")
    r = run(suite, "Upload with SQLi-shaped filename — expect 201, stored literally (TC-FILE-025)",
            upload(client, token, sqli_token, make_bytes(1024), "test' OR '1'='1.txt", expected=[200, 201]))
    sqli_pk = get_field(r, "fileDocumentPk")
    if sqli_pk:
        created_ids.setdefault("FileDocument", []).append(sqli_pk)
        stored_name = get_field(r, "fileNameOriginal")
        if stored_name and stored_name != "test' OR '1'='1.txt":
            print(f"      ⚠ fileNameOriginal stored as '{stored_name}', expected literal preservation")

    # ── RULE-FILE-002 / ERR-FILE-0002 — TTL expiry: NOT AUTOMATED (see header note #3) ──
    print("  ⊘ Skipped — RULE-FILE-002 (TC-FILE-005/006, token TTL=100min) requires a "
          "100+ minute wait or clock manipulation; not automated by this script.")

    # ── Stage E — exploratory scenarios (bounded, sourced, undocumented outcomes) ──
    # Source: issueUploadToken.md — ownerType Constraints: maxLength=100
    r = issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201, 400],
                            owner_type="X" * 100)
    run_observation(observations, "Issue Upload Token — ownerType at maxLength (100 chars)",
                     source="issueUploadToken.md ownerType Constraints: maxLength=100", result=r)

    r = issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201, 400],
                            owner_type="X" * 101)
    run_observation(observations, "Issue Upload Token — ownerType over maxLength (101 chars)",
                     source="issueUploadToken.md ownerType Constraints: maxLength=100", result=r)

    # Source: issueUploadToken.md — moduleCode Constraints: maxLength=20
    r = issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201, 400],
                            module_code="X" * 20)
    run_observation(observations, "Issue Upload Token — moduleCode at maxLength (20 chars)",
                     source="issueUploadToken.md moduleCode Constraints: maxLength=20", result=r)

    r = issue_upload_token(client, token, FILE_CATEGORY_FK, expected=[200, 201, 400],
                            module_code="X" * 21)
    run_observation(observations, "Issue Upload Token — moduleCode over maxLength (21 chars)",
                     source="issueUploadToken.md moduleCode Constraints: maxLength=20", result=r)

    # Source: issueUploadToken.md — required-field omissions (Required=Yes)
    for omitted_field in ("ownerId", "ownerType", "moduleCode", "fileCategoryFk"):
        payload = {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                   "moduleCode": MODULE_CODE, "fileCategoryFk": FILE_CATEGORY_FK}
        del payload[omitted_field]
        r = client.post("api/v1/files/upload-token", token=token, expected=[200, 201, 400],
                         json=payload)
        run_observation(observations, f"Issue Upload Token — omit required '{omitted_field}'",
                         source=f"issueUploadToken.md {omitted_field} Required=Yes", result=r)

    # Source: issueUploadToken.md — fileCategoryFk Type: integer (int64)
    r = client.post("api/v1/files/upload-token", token=token, expected=[200, 201, 400],
                     json={"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                           "moduleCode": MODULE_CODE, "fileCategoryFk": "not-an-integer"})
    run_observation(observations, "Issue Upload Token — fileCategoryFk type mismatch (string, not int64)",
                     source="issueUploadToken.md fileCategoryFk Type: integer (int64)", result=r)

    return suite, observations


# ─── Cleanup / Teardown ─────────────────────────────────────────────────────────
# FileDocument has a real terminal DELETE, but — unlike a plain REST DELETE /{id} —
# it requires a freshly-issued, single-use access token (issueAccessToken, action=
# DELETE) rather than the id itself. This diverges from the generic boilerplate's
# id-based delete/deactivate pattern; adapted here rather than force-fit.
#
# FileCategory is never created by this script (DRV-FILE-001 — reference table,
# DB-seeded), so there is nothing to tear down for it.

def cleanup(client: APIClient, token: Optional[str], created_ids: dict[str, list[int]]) -> None:
    print("\n[Cleanup]")
    deleted, already_gone, failed = 0, 0, 0
    for file_pk in created_ids.get("FileDocument", []):
        if file_pk is None:
            continue
        r_tok = client.post(f"api/v1/files/{file_pk}/access-token", token=token,
                             expected=[200, 404, 410], params={"action": "DELETE"})
        del_token = get_field(r_tok, "encryptedToken")
        if not del_token:
            # Likely already deleted (404/410 on token issuance) — nothing further to do.
            already_gone += 1
            print(f"  ✓ FileDocument #{file_pk} — already gone or inaccessible, skipping")
            continue
        r_del = client.delete(f"{del_token}", token=token, expected=[200, 404, 410])
        if r_del.status_code == 200:
            deleted += 1
            print(f"  ✓ Deleted FileDocument #{file_pk}")
        elif r_del.status_code in (404, 410):
            already_gone += 1
            print(f"  ✓ FileDocument #{file_pk} — already deleted")
        else:
            failed += 1
            print(f"  ⚠ Could not delete FileDocument #{file_pk} (status {r_del.status_code})")

    print(f"  Summary: {deleted} deleted, {already_gone} already gone, {failed} failed")
    if failed:
        print("  ⚠ Some test records may remain in the database — review manually.")


# ─── Stage G — Problems Report (filtered, categorized) ─────────────────────────

def generate_problems_report(suites: list[TestSuite], output_path: str) -> int:
    likely_bugs, mismatches, infra = [], [], []
    for suite in suites:
        for r in suite.results:
            if r.passed:
                continue
            if r.error and ("Connection refused" in r.error or "timeout" in r.error.lower()):
                infra.append((suite.name, r))
            else:
                # Ambiguous failures default to "Likely Real Bug" per governance —
                # never silently classified as benign without a documented RULE/ERR
                # explaining why the observed status is actually correct.
                likely_bugs.append((suite.name, r))

    lines = ["# File Service — Problems Report", ""]
    lines.append(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append(f"🔴 Likely Real Bugs: {len(likely_bugs)}")
    lines.append(f"🟡 Test Assumption Mismatches: {len(mismatches)}")
    lines.append(f"⚪ Infrastructure: {len(infra)}")
    lines.append("")

    def section(title, items):
        out = [f"## {title}", ""]
        if not items:
            out.append("_None._\n")
            return out
        for suite_name, r in items:
            out.append(f"- **[{suite_name}] {r.name}**")
            out.append(f"  - `{r.method} {r.url}`")
            out.append(f"  - Got: `{r.status_code or 'ERR'}`, Expected: `{r.expected_statuses}`")
            if r.error:
                out.append(f"  - Error: {r.error}")
            out.append("")
        return out

    lines += section("🔴 Likely Real Bugs", likely_bugs)
    lines += section("🟡 Test Assumption Mismatches", mismatches)
    lines += section("⚪ Infrastructure", infra)

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"📄 Problems report written to: {output_path}")
    return len(likely_bugs) + len(mismatches) + len(infra)


# ─── HTML Report ────────────────────────────────────────────────────────────────

def generate_html_report(suites: list[TestSuite], observations: list, output_path: str,
                          duration: float, base_url: str) -> None:
    total_pass = sum(s.passed for s in suites)
    total_fail = sum(s.failed for s in suites)
    total_all = sum(s.total for s in suites)
    pass_pct = round(total_pass / total_all * 100, 1) if total_all else 0

    suite_rows = ""
    for suite in suites:
        pct = round(suite.passed / suite.total * 100, 1) if suite.total else 0
        suite_rows += f"""
        <tr>
          <td>{suite.name}</td>
          <td class="num">{suite.total}</td>
          <td class="num pass">{suite.passed}</td>
          <td class="num fail">{suite.failed}</td>
          <td class="num">{pct}%</td>
        </tr>"""

    detail_sections = ""
    for suite in suites:
        rows = ""
        for r in suite.results:
            status_class = "pass" if r.passed else "fail"
            code = r.status_code or "ERR"
            expected = ", ".join(str(s) for s in r.expected_statuses)
            note_html = f'<span class="note">{r.note}</span>' if r.note else ""
            error_html = f'<div class="error-msg">{r.error}</div>' if r.error else ""
            body_html = ""
            if r.response_body:
                short = r.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(r.response_body) > 300 else ""}</pre></details>'
            rows += f"""
            <tr class="{status_class}">
              <td><span class="badge {status_class}">{r.status_label}</span></td>
              <td><span class="method {r.method.lower()}">{r.method}</span></td>
              <td class="test-name">{r.name} {note_html}</td>
              <td class="url">{r.url}</td>
              <td class="num">{code}</td>
              <td class="num">{expected}</td>
              <td class="num">{r.duration_ms:.0f}ms</td>
              <td>{error_html}{body_html}</td>
            </tr>"""
        detail_sections += f"""
        <section>
          <h2>{suite.name} — {suite.passed}/{suite.total} passed</h2>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Test</th><th>URL</th>
              <th>Got</th><th>Expected</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </section>"""

    observation_section = ""
    if observations:
        obs_rows = ""
        for o in observations:
            code = o.status_code or "ERR"
            body_html = ""
            if o.response_body:
                short = o.response_body[:300]
                body_html = f'<details><summary>Response body</summary><pre>{short}{"..." if len(o.response_body) > 300 else ""}</pre></details>'
            obs_rows += f"""
            <tr>
              <td><span class="badge observed">OBSERVED</span></td>
              <td><span class="method {o.method.lower()}">{o.method}</span></td>
              <td class="test-name">{o.name}</td>
              <td class="url">{o.url}</td>
              <td class="num">{code}</td>
              <td class="url">{o.source}</td>
              <td class="num">{o.duration_ms:.0f}ms</td>
              <td>{body_html}</td>
            </tr>"""
        observation_section = f"""
        <section>
          <h2>⚠️ Exploratory Observations — undocumented expected outcomes, not pass/fail</h2>
          <p style="padding:0 20px;color:#666;font-size:.85rem">
            These scenarios test documented constraints (Required/maxLength/type) but the API's
            expected response for violating them isn't specified in any governance document.
            Review the observed status/body against your intended behavior — do not treat these
            as failures of the implementation.
          </p>
          <table>
            <thead><tr><th>Status</th><th>Method</th><th>Scenario</th><th>URL</th>
              <th>Observed</th><th>Source (doc/field)</th><th>Time</th><th>Details</th></tr></thead>
            <tbody>{obs_rows}</tbody>
          </table>
        </section>"""

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" />
<title>File Service API Test Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
<style>
  *,*::before,*::after{{box-sizing:border-box}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;margin:0;padding:20px;background:#f4f6f9;color:#1a1a2e}}
  h1{{margin-bottom:4px}} .meta{{color:#666;font-size:.9rem;margin-bottom:24px}}
  .summary{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:28px}}
  .card{{background:#fff;border-radius:10px;padding:18px 24px;box-shadow:0 2px 6px rgba(0,0,0,.08);min-width:140px;text-align:center}}
  .card .num{{font-size:2.2rem;font-weight:700;line-height:1}} .card .label{{font-size:.8rem;color:#888;margin-top:4px}}
  .card.total .num{{color:#3a86ff}} .card.pass .num{{color:#2ec4b6}} .card.fail .num{{color:#e63946}}
  .suite-table{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  table{{width:100%;border-collapse:collapse;font-size:.875rem}}
  th{{background:#f0f2f5;text-align:left;padding:10px 14px;font-weight:600;color:#555}}
  td{{padding:8px 14px;border-top:1px solid #eef0f3;vertical-align:top}}
  tr.pass td{{background:#f6fff8}} tr.fail td{{background:#fff5f5}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:10px;font-size:.75rem;font-weight:700}}
  .badge.pass{{background:#d4f7ef;color:#1a7a6f}} .badge.fail{{background:#fde8e8;color:#b91c1c}}
  .badge.observed{{background:#fff3cd;color:#8a6314}}
  .method{{display:inline-block;padding:2px 6px;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff}}
  .method.get{{background:#3a86ff}} .method.post{{background:#2ec4b6}} .method.delete{{background:#e63946}}
  .num{{text-align:center}} .url{{font-size:.75rem;color:#666;word-break:break-all;max-width:260px}}
  .test-name{{font-weight:500}} .note{{font-size:.72rem;color:#999;margin-left:6px}}
  .error-msg{{color:#b91c1c;font-size:.8rem}}
  details summary{{cursor:pointer;color:#3a86ff;font-size:.78rem;margin-top:4px}}
  pre{{background:#f8f8f8;padding:8px;border-radius:4px;font-size:.72rem;overflow-x:auto;max-width:400px;white-space:pre-wrap}}
  section{{background:#fff;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,.08);margin-bottom:28px;overflow:hidden}}
  section h2{{padding:14px 20px;margin:0;background:#f0f2f5;font-size:1rem;border-bottom:1px solid #e0e4ea}}
</style></head>
<body>
  <h1>File Service API Test Report</h1>
  <p class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;·&nbsp;
     Base URL: {base_url} &nbsp;·&nbsp; Duration: {duration:.1f}s</p>
  <div class="summary">
    <div class="card total"><div class="num">{total_all}</div><div class="label">Total</div></div>
    <div class="card pass"><div class="num">{total_pass}</div><div class="label">Passed</div></div>
    <div class="card fail"><div class="num">{total_fail}</div><div class="label">Failed</div></div>
    <div class="card total"><div class="num">{pass_pct}%</div><div class="label">Pass Rate</div></div>
  </div>
  <div class="suite-table"><table><thead><tr><th>Suite</th><th>Total</th><th>Pass</th><th>Fail</th><th>Rate</th></tr></thead>
  <tbody>{suite_rows}</tbody></table></div>
  {detail_sections}
  {observation_section}
</body></html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"\n📄 HTML report written to: {output_path}")


# ─── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="File Service API test suite")
    parser.add_argument("--base-url", default=BASE_URL, help="Base API URL")
    parser.add_argument("--report", default="file_api_test_report.html", help="Output HTML file")
    parser.add_argument("--problems-report", default="file_problems_report.md", help="Output problems .md file")
    args = parser.parse_args()

    client = APIClient(args.base_url)
    start_time = time.perf_counter()

    print("=" * 60)
    print("  File Service API Test Suite")
    print(f"  Base URL: {args.base_url}")
    print("=" * 60)

    auth_suite, token = login(client, ADMIN_USERNAME, ADMIN_PASSWORD, "Auth")
    second_token = None
    if SECOND_USER_USERNAME and SECOND_USER_PASSWORD:
        second_auth_suite, second_token = login(client, SECOND_USER_USERNAME, SECOND_USER_PASSWORD, "Auth (Second User)")
    else:
        second_auth_suite = TestSuite("Auth (Second User)")  # empty — not configured

    observations: list = []
    created_ids: dict[str, list[int]] = {"FileDocument": []}
    file_suite = TestSuite("FileDocument")

    try:
        file_suite, observations = test_file_document(client, token, second_token, created_ids)
    finally:
        # Always runs, even if a test above raised partway through — otherwise a
        # single failure would silently skip teardown and leak test data.
        cleanup(client, token, created_ids)

    duration = time.perf_counter() - start_time
    suites = [auth_suite, second_auth_suite, file_suite]

    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    total_pass = sum(s.passed for s in suites)
    total_all = sum(s.total for s in suites)
    for s in suites:
        if s.total == 0:
            continue
        bar = "█" * s.passed + "░" * s.failed
        print(f"  {s.name:<24} {s.passed:>3}/{s.total:<3}  {bar}")
    print(f"\n  Total: {total_pass}/{total_all} passed  ({duration:.1f}s)")
    if observations:
        print(f"  Exploratory observations: {len(observations)} (see HTML report — not pass/fail)")

    generate_html_report(suites, observations, args.report, duration, args.base_url)
    problem_count = generate_problems_report(suites, args.problems_report)
    if problem_count:
        print(f"  ⚠ {problem_count} item(s) in problems report — review before considering this a clean run.")

    sys.exit(0 if total_pass == total_all else 1)


if __name__ == "__main__":
    main()
