"""
Resolves OpenAPI schema $refs into field lists (FieldSpec), and detects the
recurring response shapes generated by this codebase's stack:

  - the ApiResponse<T> envelope (success/message/data/error/timestamp),
    with the real payload living under "data"
  - Spring's Page<T> serialization (content/totalElements/... with the real
    item type under content.items)
  - a plain array response ("type": "array", "items": {$ref})

Everything here operates purely on the already-loaded OpenAPI document —
no Java source, no network calls beyond what openapi_extractor already did.
"""

from typing import Optional

from extractors import validation_extractor
from models.api_doc_model import FieldSpec

ENVELOPE_KEYS = {"success", "message", "data", "error", "timestamp"}
PAGE_KEYS = {"content", "totalElements"}


def resolve_ref(schema: dict, components: dict) -> tuple[dict, Optional[str]]:
    """Dereference a single-level $ref. Returns (resolved_schema, ref_name_or_None)."""
    if not schema:
        return {}, None
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        return components.get("schemas", {}).get(name, {}), name
    return schema, None


def schema_fields(schema: dict, components: dict, _visited: frozenset = frozenset()) -> list[FieldSpec]:
    """Field list for a resolved-or-ref'd object schema (not array/envelope aware).

    Also recursively expands any field whose own type (or array-item type) is
    itself an object schema with properties -- e.g. a search request's
    `filters: array<ContractFilter>` gets ContractFilter's own field, operator,
    value fields attached to FieldSpec.nested, instead of staying an opaque
    type name. `_visited` guards against self-referential schemas (e.g. a tree
    node's own `children` field) by marking FieldSpec.recursive_ref instead of
    expanding forever.
    """
    resolved, ref_name = resolve_ref(schema, components)
    if ref_name:
        _visited = _visited | {ref_name}
    props = resolved.get("properties", {})
    required_names = set(resolved.get("required", []))

    def _resolve(s: dict) -> tuple[dict, Optional[str]]:
        return resolve_ref(s, components)

    fields = [
        validation_extractor.build_field_spec(name, prop, name in required_names, _resolve)
        for name, prop in props.items()
    ]
    for f in fields:
        _expand_nested(f, components, _visited)
    return fields


def _expand_nested(f: FieldSpec, components: dict, visited: frozenset) -> None:
    schemas = components.get("schemas", {})
    ref_name = f.item_type if f.is_array else f.type
    ref_schema = schemas.get(ref_name) if ref_name else None
    if not ref_schema or not ref_schema.get("properties"):
        return
    if ref_name in visited:
        f.recursive_ref = ref_name
        return
    f.nested = schema_fields(ref_schema, components, visited | {ref_name})


def is_envelope_shape(resolved: dict) -> bool:
    return ENVELOPE_KEYS.issubset(resolved.get("properties", {}).keys())


def is_page_shape(resolved: dict) -> bool:
    return PAGE_KEYS.issubset(resolved.get("properties", {}).keys())


def describe_payload(schema: dict, components: dict) -> tuple[list[FieldSpec], bool, bool, Optional[str]]:
    """Unwraps the ApiResponse<T> envelope (if present) and describes the real
    payload underneath: (fields, is_array, is_page, schema_name)."""
    resolved, name = resolve_ref(schema, components)

    if is_envelope_shape(resolved):
        data_schema = resolved["properties"].get("data", {})
        return describe_payload(data_schema, components)

    if resolved.get("type") == "array":
        item_schema = resolved.get("items", {})
        _, item_name = resolve_ref(item_schema, components)
        return schema_fields(item_schema, components), True, False, item_name

    if is_page_shape(resolved):
        content_schema = resolved["properties"].get("content", {})
        item_schema = content_schema.get("items", {})
        _, item_name = resolve_ref(item_schema, components)
        return schema_fields(item_schema, components), False, True, item_name

    return schema_fields(schema, components), False, False, name


def find_page_envelope(openapi: dict) -> tuple[Optional[str], list[FieldSpec]]:
    """Finds the first Spring Page<T> wrapper schema and describes its own
    bookkeeping fields (totalElements, totalPages, size, number, ...),
    excluding "content" since that's the per-endpoint item list already
    covered by each endpoint's own Response section. Returns (schema_name,
    fields), or (None, []) if no Page-shaped schema exists anywhere."""
    components = openapi.get("components", {})
    schemas = components.get("schemas", {})

    for name, schema in schemas.items():
        if not is_page_shape(schema):
            continue

        def _resolve(s: dict) -> tuple[dict, Optional[str]]:
            return resolve_ref(s, components)

        props = schema.get("properties", {})
        fields = [
            validation_extractor.build_field_spec(key, prop, False, _resolve)
            for key, prop in props.items()
            if key != "content"
        ]
        return name, fields

    return None, []
